Repository istio/proxy, pull requests merged in 2018-11, with the labels that each got.

#2015 Fix mac test fail: remove tests to compare signature values
  src/istio/mixerclient/referenced_test.cc
Labels: approved, cla: yes, lgtm

#2014 Use string map instead of opaque struct for dynamic metadata
  include/istio/control/http/report_data.h
  include/istio/control/tcp/report_data.h
  include/istio/utils/attribute_names.h
  include/istio/utils/attributes_builder.h
  src/envoy/http/mixer/report_data.h
  src/envoy/tcp/mixer/filter.cc
  src/envoy/tcp/mixer/filter.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/mock_report_data.h
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/tcp/attributes_builder.cc
  src/istio/control/tcp/attributes_builder_test.cc
  src/istio/control/tcp/mock_report_data.h
  src/istio/control/tcp/request_handler_impl_test.cc
  src/istio/utils/attribute_names.cc
  src/istio/utils/utils.h
Labels: approved, cla: yes, lgtm

#2017 Add a new TCP cluster rewrite filter
  WORKSPACE
  include/istio/mixerclient/check_response.h
  include/istio/mixerclient/environment.h
  istio.deps
  repositories.bzl
  src/envoy/BUILD
  src/envoy/tcp/tcp_cluster_rewrite/BUILD
  src/envoy/tcp/tcp_cluster_rewrite/config.cc
  src/envoy/tcp/tcp_cluster_rewrite/config.h
  src/envoy/tcp/tcp_cluster_rewrite/config_test.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite.h
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite_test.cc
  src/istio/mixerclient/attribute_compressor.h
  src/istio/mixerclient/referenced.h
  test/integration/istio_http_integration_test.cc
Labels: approved, cla: yes, lgtm

#2018 Add a new TCP cluster rewrite filter (#2017)
  WORKSPACE
  include/istio/mixerclient/check_response.h
  include/istio/mixerclient/environment.h
  istio.deps
  repositories.bzl
  src/envoy/BUILD
  src/envoy/tcp/tcp_cluster_rewrite/BUILD
  src/envoy/tcp/tcp_cluster_rewrite/config.cc
  src/envoy/tcp/tcp_cluster_rewrite/config.h
  src/envoy/tcp/tcp_cluster_rewrite/config_test.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite.h
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite_test.cc
  src/istio/mixerclient/attribute_compressor.h
  src/istio/mixerclient/referenced.h
  test/integration/istio_http_integration_test.cc
Labels: approved, cla: yes, lgtm

#2019 Update TCP Cluster Rewrite filter name
  src/envoy/tcp/tcp_cluster_rewrite/config.h
Labels: approved, cla: yes, lgtm

#2020 Update TCP Cluster Rewrite filter name (#2019)
  src/envoy/tcp/tcp_cluster_rewrite/config.h
Labels: approved, cla: yes, lgtm

#2021 Enable TCP Cluster Rewrite filter registration
  src/envoy/BUILD
Labels: approved, cla: yes, lgtm

#2022 Enable TCP Cluster Rewrite filter registration (#2021)
  src/envoy/BUILD
Labels: approved, cla: yes, lgtm

#2023 Update Envoy SHA to 4ef8562b
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#2024 Update Envoy SHA to 4ef8562b (#2023)
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#2026 Update Envoy SHA to 74de08a0
  WORKSPACE
  istio.deps
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/jwt_auth/http_filter.cc
  src/envoy/http/mixer/filter.cc
Labels: approved, cla: yes, lgtm

#2027 update istio api
  istio.deps
  repositories.bzl
Labels: cla: yes, lgtm

#2029 Update Envoy SHA to c41fa7118e69a0872074d7a685a62331c5d5c17e
  WORKSPACE
  istio.deps
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/jwt_auth/http_filter.cc
  src/envoy/http/mixer/filter.cc
Labels: approved, cla: yes, lgtm

#2031 Merge master into release-1.1
  prow/proxy-postsubmit-periodic.sh
  src/envoy/http/jwt_auth/README.md
  src/envoy/http/jwt_auth/sample/envoy.conf
  src/istio/mixerclient/referenced_test.cc
Labels: approved, lgtm

#2032 Merge release-1.1 to master
  WORKSPACE
  include/istio/control/http/report_data.h
  include/istio/control/tcp/report_data.h
  include/istio/utils/attributes_builder.h
  istio.deps
  src/envoy/http/mixer/report_data.h
  src/envoy/tcp/mixer/filter.cc
  src/envoy/tcp/mixer/filter.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/mock_report_data.h
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/tcp/attributes_builder.cc
  src/istio/control/tcp/attributes_builder_test.cc
  src/istio/control/tcp/mock_report_data.h
  src/istio/control/tcp/request_handler_impl_test.cc
  src/istio/utils/utils.h
Labels: approved, cla: no, lgtm

#2034 bazel: Allow to distdir all dependencies
  Makefile
  WORKSPACE
  cc_gogo_protobuf.bzl
  googleapis.bzl
  protobuf.bzl
  repositories.bzl
  script/check-repositories
  x_tools_imports.bzl
Labels: approved, cla: yes, lgtm, ok-to-test

#2035 bazel: Remove BoringSSL repository
  repositories.bzl
Labels: approved, cla: yes, lgtm, ok-to-test

#2037 Update Envoy SHA to fcc68f1
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#2038 Merge master to release-1.1
  Makefile
  WORKSPACE
  cc_gogo_protobuf.bzl
  googleapis.bzl
  istio.deps
  protobuf.bzl
  repositories.bzl
  script/check-repositories
  x_tools_imports.bzl
Labels: approved, cla: yes, lgtm

#2041 update envoy SHA to 48b161ee02f4ca77b8c26959c4058456ad3f197f
  WORKSPACE
  istio.deps
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite_test.cc
Labels: approved, cla: yes, lgtm

#2040 Enable caching of dynamic metadata in mixer filter
  src/envoy/tcp/mixer/filter.cc
  src/envoy/tcp/mixer/filter.h
Labels: approved, cla: yes, lgtm

#2044 release-1.1: Update api sha to 1a7788d (1.1 branch latest).
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm

#2045 Forward Downstream SNI filter
  src/envoy/BUILD
  src/envoy/tcp/forward_downstream_sni/BUILD
  src/envoy/tcp/forward_downstream_sni/config.cc
  src/envoy/tcp/forward_downstream_sni/config.h
  src/envoy/tcp/forward_downstream_sni/forward_downstream_sni.cc
  src/envoy/tcp/forward_downstream_sni/forward_downstream_sni.h
  src/envoy/tcp/forward_downstream_sni/forward_downstream_sni_test.cc
Labels: approved, cla: yes, lgtm

#2047 Bump enoy version to pickup json access log fix
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm
