Repository istio/proxy, pull requests merged in 2018-02, with the labels that each got.

#1034 Update the Mixer README.md
  src/envoy/mixer/README.md
Labels: approved, cla: yes, lgtm

#1105 make istio.deps consistent with WORKSPACE
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#1104 Clean code to reach legacy mixer filter config
  src/envoy/mixer/config.cc
  src/envoy/mixer/config.h
  src/envoy/mixer/http_filter.cc
  src/envoy/mixer/mixer_control.cc
  src/envoy/mixer/mixer_control.h
  src/envoy/mixer/repositories.bzl
Labels: approved, cla: yes, lgtm

#1114 [DO NOT MERGE] Auto PR to update dependencies of proxy
  WORKSPACE
  istio.deps
  src/envoy/mixer/repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1119 Add back mixerclient stats
  src/envoy/mixer/BUILD
  src/envoy/mixer/http_filter.cc
  src/envoy/mixer/mixer_control.cc
  src/envoy/mixer/mixer_control.h
  src/envoy/mixer/stats.cc
  src/envoy/mixer/stats.h
  src/envoy/mixer/tcp_filter.cc
Labels: approved, cla: yes, lgtm

#1111 Update envoy to e2117cb
  WORKSPACE
  istio.deps
  prow/proxy-presubmit.sh
  src/envoy/mixer/tcp_filter.cc
Labels: approved, cla: yes, lgtm

#1128 remove mixerclient dependency
  istio.deps
Labels: approved, cla: yes, lgtm

#1130 [DO NOT MERGE] Auto PR to update dependencies of proxy
  istio.deps
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1116 Ignore unknown field when parsing proxy config.
  src/envoy/mixer/BUILD
  src/envoy/mixer/config.cc
  src/envoy/mixer/http_filter.cc
  src/envoy/mixer/utils.cc
  src/envoy/mixer/utils.h
  src/envoy/mixer/utils_test.cc
Labels: approved, cla: yes, lgtm

#1135 fix dependency file
  istio.deps
Labels: cla: yes, lgtm

#1136 [DO NOT MERGE] Auto PR to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1140 Move envoy code to src/envoy/http folder
  src/envoy/BUILD
  src/envoy/http/jwt_auth/BUILD
  src/envoy/http/jwt_auth/ImplementationNotes.md
  src/envoy/http/jwt_auth/README.md
  src/envoy/http/jwt_auth/auth_store.h
  src/envoy/http/jwt_auth/config.proto
  src/envoy/http/jwt_auth/http_filter.cc
  src/envoy/http/jwt_auth/http_filter.h
  src/envoy/http/jwt_auth/http_filter_factory.cc
  src/envoy/http/jwt_auth/integration_test/envoy.conf
  src/envoy/http/jwt_auth/integration_test/envoy.conf.jwk
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt.h
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator.h
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/jwt_auth/jwt_test.cc
  src/envoy/http/jwt_auth/pubkey_cache.h
  src/envoy/http/jwt_auth/sample/correct_jwt
  src/envoy/http/jwt_auth/sample/envoy.conf
  src/envoy/http/jwt_auth/sample/fake_issuer.go
  src/envoy/http/jwt_auth/sample/invalid_jwt
  src/envoy/http/jwt_auth/sample/pubkey.jwk
  src/envoy/http/mixer/BUILD
  src/envoy/http/mixer/README.md
  src/envoy/http/mixer/config.cc
  src/envoy/http/mixer/config.h
  src/envoy/http/mixer/envoy.conf.template
  src/envoy/http/mixer/envoy_lds.conf
  src/envoy/http/mixer/grpc_transport.cc
  src/envoy/http/mixer/grpc_transport.h
  src/envoy/http/mixer/http_filter.cc
  src/envoy/http/mixer/mixer_control.cc
  src/envoy/http/mixer/mixer_control.h
  src/envoy/http/mixer/start_envoy
  src/envoy/http/mixer/stats.cc
  src/envoy/http/mixer/stats.h
  src/envoy/http/mixer/tcp_filter.cc
  src/envoy/http/mixer/utils.cc
  src/envoy/http/mixer/utils.h
  src/envoy/http/mixer/utils_test.cc
Labels: approved, cla: yes, lgtm

#1152 Move TCP filter Check() call under onData().
  src/envoy/tcp/mixer/tcp_filter.cc
Labels: approved, cla: yes, lgtm

#1164 Update Istio/api SHA with new failed_network_policy
  istio.deps
  repositories.bzl
  src/control/client_context_base.cc
Labels: approved, cla: yes, lgtm

#1166 Send unique connection
  include/istio/control/tcp/check_data.h
  src/envoy/tcp/mixer/mixer_control.cc
  src/envoy/tcp/mixer/mixer_control.h
  src/envoy/tcp/mixer/tcp_filter.cc
  src/istio/control/attribute_names.cc
  src/istio/control/attribute_names.h
  src/istio/control/tcp/attributes_builder.cc
  src/istio/control/tcp/attributes_builder_test.cc
  src/istio/control/tcp/mock_check_data.h
Labels: approved, cla: yes, lgtm

#1169 [DO NOT MERGE] Auto PR to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1170 Add mTLS logging for authentication policy prototyping
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter.h
  src/envoy/http/authn/mtls_authentication.cc
  src/envoy/http/authn/mtls_authentication.h
Labels: approved, cla: yes, lgtm

#1172 [DO NOT MERGE] Auto PR to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1175 Split a big file into smaller files in http mixer
  src/envoy/http/mixer/BUILD
  src/envoy/http/mixer/check_data.cc
  src/envoy/http/mixer/check_data.h
  src/envoy/http/mixer/config.cc
  src/envoy/http/mixer/config.h
  src/envoy/http/mixer/control.cc
  src/envoy/http/mixer/control.h
  src/envoy/http/mixer/control_factory.h
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/filter.h
  src/envoy/http/mixer/filter_factory.cc
  src/envoy/http/mixer/header_update.h
  src/envoy/http/mixer/http_filter.cc
  src/envoy/http/mixer/report_data.h
Labels: approved, cla: yes, lgtm

#1177 split tcp mixer filter.
  src/envoy/tcp/mixer/BUILD
  src/envoy/tcp/mixer/config.h
  src/envoy/tcp/mixer/control.cc
  src/envoy/tcp/mixer/control.h
  src/envoy/tcp/mixer/control_factory.h
  src/envoy/tcp/mixer/filter.cc
  src/envoy/tcp/mixer/filter.h
  src/envoy/tcp/mixer/filter_factory.cc
  src/envoy/tcp/mixer/mixer_control.cc
  src/envoy/tcp/mixer/tcp_filter.cc
Labels: approved, cla: yes, lgtm

#1178 circleci: update bazel to 0.11, install clang
  .circleci/Dockerfile
  .circleci/Makefile
Labels: approved, cla: yes, lgtm
