Repository istio/proxy, pull requests merged in 2018-12, with the labels that each got.

#2050 Add sni verifier filter
  src/envoy/BUILD
  src/envoy/tcp/sni_verifier/BUILD
  src/envoy/tcp/sni_verifier/config.cc
  src/envoy/tcp/sni_verifier/config.h
  src/envoy/tcp/sni_verifier/sni_verifier.cc
  src/envoy/tcp/sni_verifier/sni_verifier.h
  src/envoy/tcp/sni_verifier/sni_verifier_test.cc
Labels: approved, cla: yes, lgtm, ok-to-test

#2053 Handle inflight request canceling properly
  src/envoy/utils/grpc_transport.cc
Labels: approved, cla: yes, lgtm

#2065 Add Venil to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm

#2069 Fix build issue with bazel 0.20 (charry-pick #2068)
  WORKSPACE
Labels: approved, cla: yes, lgtm

#2068 make build work with bazel 0.20
  WORKSPACE
Labels: approved, cla: yes, lgtm

#2067 Clarify log messages (cherry-pick #2066)
  src/envoy/http/mixer/control.cc
  src/envoy/tcp/mixer/control.cc
  src/envoy/utils/mixer_control.cc
Labels: cla: yes
