Repository istio/proxy, pull requests merged in 2018-10, with the labels that each got.

#1986 Revert "To share mixer client across listeners (#1972)"
  src/envoy/http/mixer/config.h
  src/envoy/http/mixer/control_factory.h
  src/envoy/http/mixer/filter_factory.cc
  src/envoy/tcp/mixer/config.h
  src/envoy/tcp/mixer/control_factory.h
  src/envoy/tcp/mixer/filter_factory.cc
Labels: approved, cla: yes, lgtm

#1988 Fix memory leak at report batching
  src/istio/mixerclient/attribute_compressor.cc
Labels: approved, cla: yes, lgtm

#1989 reuse report protobuf instead of using arena allocation
  src/istio/mixerclient/attribute_compressor.cc
Labels: approved, cla: yes, lgtm

#1996 Fix attribute constant
  include/istio/utils/attribute_names.h
  src/istio/control/tcp/attributes_builder.cc
  src/istio/utils/attribute_names.cc
Labels: approved, cla: yes, lgtm

#1997 Update bazel for circleCI
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#1993 Update dependencies and fix compile errors.
  .circleci/config.yml
  BUILD
  WORKSPACE
  istio.deps
  protobuf.bzl
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter_test.cc
  src/envoy/http/jwt_auth/http_filter.cc
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/filter.h
  src/envoy/http/mixer/report_data.h
Labels: approved, cla: yes, lgtm

#1998 move tool/bazel.rc to .bazelrc
  .bazelrc
  tools/bazel.rc
Labels: approved, cla: yes, lgtm

#1999 update envoy SHA to point to json access log format functionality
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#2002 Improve performance by removing MD5 for check cache keys
  include/istio/utils/BUILD
  include/istio/utils/concat_hash.h
  include/istio/utils/md5.h
  src/istio/mixerclient/BUILD
  src/istio/mixerclient/referenced.cc
  src/istio/mixerclient/referenced.h
  src/istio/mixerclient/referenced_test.cc
  src/istio/utils/BUILD
  src/istio/utils/md5.cc
  src/istio/utils/md5_test.cc
Labels: approved, cla: yes, lgtm

#2003 alts: remove ALTS
  src/envoy/BUILD
  src/envoy/alts/BUILD
  src/envoy/alts/README.md
  src/envoy/alts/alts_socket.proto
  src/envoy/alts/alts_socket_factory.cc
  src/envoy/alts/alts_socket_factory.h
  src/envoy/alts/example.yaml
  src/envoy/alts/transport_security_interface_wrapper.h
  src/envoy/alts/tsi_frame_protector.cc
  src/envoy/alts/tsi_frame_protector.h
  src/envoy/alts/tsi_handshaker.cc
  src/envoy/alts/tsi_handshaker.h
  src/envoy/alts/tsi_transport_socket.cc
  src/envoy/alts/tsi_transport_socket.h
Labels: approved, cla: yes, lgtm

#2009 Use std::hash for check cache.
  include/istio/utils/concat_hash.h
  src/istio/mixerclient/check_cache.cc
  src/istio/mixerclient/check_cache.h
  src/istio/mixerclient/quota_cache.cc
  src/istio/mixerclient/quota_cache.h
  src/istio/mixerclient/referenced.cc
  src/istio/mixerclient/referenced.h
  src/istio/mixerclient/referenced_test.cc
Labels: approved, cla: yes, lgtm

#2010 bump Envoy SHA to latest
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#2012 Cherry pick PRs from master
  include/istio/utils/BUILD
  include/istio/utils/concat_hash.h
  include/istio/utils/md5.h
  src/envoy/BUILD
  src/envoy/alts/BUILD
  src/envoy/alts/README.md
  src/envoy/alts/alts_socket.proto
  src/envoy/alts/alts_socket_factory.cc
  src/envoy/alts/alts_socket_factory.h
  src/envoy/alts/example.yaml
  src/envoy/alts/transport_security_interface_wrapper.h
  src/envoy/alts/tsi_frame_protector.cc
  src/envoy/alts/tsi_frame_protector.h
  src/envoy/alts/tsi_handshaker.cc
  src/envoy/alts/tsi_handshaker.h
  src/envoy/alts/tsi_transport_socket.cc
  src/envoy/alts/tsi_transport_socket.h
  src/istio/mixerclient/BUILD
  src/istio/mixerclient/check_cache.cc
  src/istio/mixerclient/check_cache.h
  src/istio/mixerclient/quota_cache.cc
  src/istio/mixerclient/quota_cache.h
  src/istio/mixerclient/referenced.cc
  src/istio/mixerclient/referenced.h
  src/istio/mixerclient/referenced_test.cc
  src/istio/utils/BUILD
  src/istio/utils/md5.cc
  src/istio/utils/md5_test.cc
Labels: approved, cla: no, lgtm

#2013 Send dynamic metadata as part of report calls
  include/istio/control/http/report_data.h
  include/istio/control/tcp/report_data.h
  include/istio/utils/attribute_names.h
  src/envoy/http/mixer/report_data.h
  src/envoy/tcp/mixer/filter.cc
  src/envoy/tcp/mixer/filter.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/mock_report_data.h
  src/istio/control/tcp/attributes_builder.cc
  src/istio/control/tcp/attributes_builder_test.cc
  src/istio/control/tcp/mock_report_data.h
  src/istio/utils/attribute_names.cc
Labels: approved, cla: yes
