Repository istio/proxy, pull requests merged in 2018-09, with the labels that each got.

#1928 support per-path JWT validation.
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/authn/authn_utils.h
  src/envoy/http/authn/authn_utils_test.cc
  src/envoy/http/authn/filter_context.h
  src/envoy/http/authn/filter_context_test.cc
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/origin_authenticator.cc
  src/envoy/http/authn/origin_authenticator_test.cc
  src/envoy/http/authn/peer_authenticator_test.cc
Labels: approved, cla: yes, lgtm

#1959 Fix the peerIsOptional and originIsOptional for authn filter.
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter_test.cc
Labels: approved, area/security, area/security/aaa, cla: yes, lgtm

#1961 Mixer Client uses Node metadata to populate Mixer attributes
  include/istio/control/http/controller.h
  include/istio/utils/BUILD
  include/istio/utils/attribute_names.h
  include/istio/utils/local_attributes.h
  src/envoy/http/mixer/BUILD
  src/envoy/http/mixer/control.cc
  src/envoy/http/mixer/control.h
  src/envoy/http/mixer/control_factory.h
  src/envoy/utils/BUILD
  src/envoy/utils/mixer_control.cc
  src/envoy/utils/mixer_control.h
  src/envoy/utils/mixer_control_test.cc
  src/istio/control/http/client_context.cc
  src/istio/control/http/client_context.h
  src/istio/control/http/controller_impl.h
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/http/service_context.cc
  src/istio/utils/BUILD
  src/istio/utils/attribute_names.cc
  src/istio/utils/local_attributes.cc
  test/integration/istio_http_integration_test.cc
Labels: approved, cla: yes, lgtm

#1964 Update Envoy SHA to latest with TCP proxy fixes.
  WORKSPACE
  include/istio/control/http/BUILD
  istio.deps
  src/envoy/http/authn/BUILD
  src/envoy/http/mixer/control.cc
  src/envoy/tcp/mixer/control.cc
  src/envoy/utils/BUILD
  src/envoy/utils/mixer_control.cc
  src/envoy/utils/mixer_control.h
  src/istio/control/http/BUILD
Labels: approved, cla: yes, lgtm

#1966 remove not used path matcher functions
  src/istio/api_spec/path_matcher.h
  src/istio/api_spec/path_matcher_test.cc
Labels: approved, cla: yes, lgtm

#1970 Remove delta update in Report batch
  include/istio/mixerclient/options.h
  src/istio/mixerclient/BUILD
  src/istio/mixerclient/attribute_compressor.cc
  src/istio/mixerclient/attribute_compressor.h
  src/istio/mixerclient/attribute_compressor_test.cc
  src/istio/mixerclient/delta_update.cc
  src/istio/mixerclient/delta_update.h
  src/istio/mixerclient/delta_update_test.cc
  src/istio/mixerclient/report_batch.cc
  src/istio/mixerclient/report_batch_test.cc
Labels: approved, cla: yes, lgtm

#1973 Optimize report sending by re-use protobuf
  src/istio/mixerclient/attribute_compressor.cc
  src/istio/mixerclient/attribute_compressor.h
  src/istio/mixerclient/attribute_compressor_test.cc
  src/istio/mixerclient/report_batch.cc
  src/istio/mixerclient/report_batch_test.cc
Labels: approved, cla: yes, lgtm

#1972 To share mixer client across listeners
  src/envoy/http/mixer/config.h
  src/envoy/http/mixer/control_factory.h
  src/envoy/http/mixer/filter_factory.cc
  src/envoy/tcp/mixer/config.h
  src/envoy/tcp/mixer/control_factory.h
  src/envoy/tcp/mixer/filter_factory.cc
Labels: approved, cla: yes, lgtm

#1975 Update Envoy SHA.
  WORKSPACE
  istio.deps
  src/envoy/http/mixer/control.cc
  src/envoy/tcp/mixer/control.cc
Labels: approved, cla: yes, lgtm

#1976 Update SHA to enable dynamic validation context and local credential.
  WORKSPACE
  include/istio/control/http/BUILD
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/http_filter_test.cc
  src/envoy/http/mixer/control.cc
  src/envoy/tcp/mixer/control.cc
  src/envoy/utils/BUILD
  src/envoy/utils/mixer_control.cc
  src/envoy/utils/mixer_control.h
  src/istio/control/http/BUILD
Labels: cla: yes

#1977 Optimize mixer client by using protobuf arena allocator.
  repositories.bzl
  src/istio/control/client_context_base.cc
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/service_context.cc
  src/istio/control/request_context.h
  src/istio/control/tcp/attributes_builder.cc
  src/istio/control/tcp/attributes_builder_test.cc
  src/istio/control/tcp/client_context.h
  src/istio/mixerclient/attribute_compressor.cc
  src/istio/mixerclient/client_impl.cc
Labels: approved, cla: yes, lgtm

#1978 Update Proxy SHA
  WORKSPACE
  istio.deps
  src/envoy/http/authn/http_filter_test.cc
Labels: approved, cla: yes, lgtm

#1979 Update README.md
  tools/deb/README.md
Labels: approved, cla: yes, lgtm
