Repository istio/proxy, pull requests merged in 2018-05, with the labels that each got.

#1660 ignore verification if peer/origin optional fields are set
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter_test.cc
Labels: cla: yes

#1610 Create a child span for mixer check call
  src/envoy/http/mixer/control.cc
  src/envoy/http/mixer/control.h
  src/envoy/http/mixer/filter.cc
  src/envoy/utils/grpc_transport.cc
  src/envoy/utils/grpc_transport.h
  src/envoy/utils/mixer_control.cc
Labels: approved, cla: yes, lgtm

#1692 [BOT PR] to update dependencies of proxy
  istio.deps
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1734 Update Envoy sha to 2b2c299144600fb9e525d21aabf39bf48e64fb1f
  WORKSPACE
  istio.deps
  src/envoy/http/authn/http_filter_factory.cc
  src/envoy/http/jwt_auth/http_filter_factory.cc
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/mixer/filter_factory.cc
  src/envoy/tcp/mixer/filter_factory.cc
Labels: approved, cla: yes, lgtm

#1736 [BOT PR] to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: cla: yes, dependency-update, lgtm, release-note-none

#1738 Strip debug info for release
  tools/bazel.rc
Labels: approved, cla: yes, lgtm

#1740 hardcode authority header for mixer temporarily
  src/envoy/utils/grpc_transport.h
Labels: cla: yes

#1733 Use mTLS mode enum to decide authentication result.
  istio.deps
  src/envoy/http/authn/authenticator_base.cc
  src/envoy/http/authn/authenticator_base_test.cc
Labels: approved, cla: yes, lgtm

#1739 [BOT PR] to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: cla: yes, dependency-update, release-note-none

#1744 Sending full JWT claims as json string via new attribute request.auth.raw_claims
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/authn/authn_utils_test.cc
  src/envoy/http/authn/http_filter_integration_test.cc
  src/istio/authn/context.proto
  src/istio/control/attribute_names.cc
  src/istio/control/attribute_names.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
Labels: approved, cla: yes, lgtm

#1750 Merging release-0.8 to master
  WORKSPACE
  istio.deps
  src/envoy/http/authn/authenticator_base.cc
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/authn/authn_utils_test.cc
  src/envoy/http/authn/filter_context.h
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter_factory.cc
  src/envoy/http/authn/http_filter_integration_test.cc
  src/envoy/http/authn/http_filter_test.cc
  src/envoy/http/jwt_auth/http_filter_factory.cc
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/jwt_auth/token_extractor.h
  src/envoy/http/mixer/control.cc
  src/envoy/http/mixer/control.h
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/filter.h
  src/envoy/http/mixer/filter_factory.cc
  src/envoy/http/mixer/report_data.h
  src/envoy/tcp/mixer/filter_factory.cc
  src/envoy/utils/grpc_transport.cc
  src/envoy/utils/grpc_transport.h
  src/envoy/utils/mixer_control.cc
  src/istio/authn/context.proto
  src/istio/control/attribute_names.cc
  src/istio/control/attribute_names.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  tools/bazel.rc
Labels: approved, cla: yes, lgtm

#1751 Optimize Referenced::Signature function
  src/istio/mixerclient/referenced.cc
  src/istio/mixerclient/referenced.h
  src/istio/mixerclient/referenced_test.cc
Labels: approved, cla: yes, lgtm

#1752 Make release-binary script takes argument for gcs destination
  script/release-binary
Labels: approved, cla: yes, lgtm

#1760 Protect referenced_map_ read in check cache
  src/istio/mixerclient/check_cache.cc
Labels: approved, cla: yes, lgtm

#1759 Release-0.8: Update envoy sha to bb6762a058
  WORKSPACE
  istio.deps
  src/envoy/alts/alts_socket_factory.cc
  src/envoy/alts/alts_socket_factory.h
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter_integration_test.cc
  src/envoy/http/jwt_auth/http_filter.cc
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/mixer/filter.cc
Labels: approved, cla: yes, lgtm

#1767 Release-0.8: Build additional artifacts with debug symbols
  script/release-binary
  tools/bazel.rc
Labels: approved, cla: yes, lgtm

#1768 [BOT PR] to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1769 Update api version to b549a3f770c833bad8f4f3871768c43960ab7309
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm

#1770 Merge changes from branch release-0.8
  WORKSPACE
  istio.deps
  repositories.bzl
  script/release-binary
  src/envoy/alts/alts_socket_factory.cc
  src/envoy/alts/alts_socket_factory.h
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter_integration_test.cc
  src/envoy/http/jwt_auth/http_filter.cc
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/mixer/filter.cc
  tools/bazel.rc
Labels: approved, cla: yes, lgtm

#1772 Remove source auto-derivation
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/tcp/attributes_builder.cc
  src/istio/control/tcp/attributes_builder_test.cc
Labels: approved, cla: yes, lgtm

#1773 Update Envoy to c2baf348055284ac761d94e9a06bc37ebf8a3532.
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#1775 R0.8: Update api sha to 8d67e57e3612dae1a3423795bce93a372cfe4fa4
  istio.deps
  repositories.bzl
Labels: approved, cla: yes

#1776 Add forwarded_attributes to per route config
  istio.deps
  repositories.bzl
  src/istio/control/http/request_handler_impl.cc
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/http/service_context.cc
  src/istio/control/http/service_context.h
Labels: approved, cla: yes, lgtm

#1774 Per-host metadata for mixerfilter
  include/istio/control/http/report_data.h
  include/istio/control/tcp/report_data.h
  src/envoy/http/mixer/README.md
  src/envoy/http/mixer/report_data.h
  src/envoy/tcp/mixer/filter.cc
  src/envoy/tcp/mixer/filter.h
  src/envoy/utils/utils.cc
  src/envoy/utils/utils.h
  src/istio/control/attribute_names.cc
  src/istio/control/attribute_names.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/mock_report_data.h
  src/istio/control/tcp/attributes_builder.cc
  src/istio/control/tcp/attributes_builder_test.cc
  src/istio/control/tcp/mock_report_data.h
  src/istio/control/tcp/request_handler_impl_test.cc
Labels: approved, cla: yes, lgtm

#1780 Merge release-0.8 to master: Just update Envoy sha to c2baf348055284ac761d94e9a06bc37ebf8a3532
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#1790 Not to flush out batched report in destructor
  src/istio/mixerclient/report_batch.cc
Labels: approved, cla: yes, lgtm

#1794 Move controler to be the last object
  src/envoy/http/mixer/control.h
  src/envoy/tcp/mixer/control.h
Labels: approved, cla: yes, lgtm

#1793 Revert Not to flush out batched report in destructor (#1790)
  src/istio/mixerclient/report_batch.cc
Labels: approved, cla: yes, lgtm

#1795 Release-0.8: Move controler to be the last object
  src/envoy/http/mixer/control.h
  src/envoy/tcp/mixer/control.h
Labels: approved, cla: yes, lgtm

#1796 release-binary: add missing dash to checksum filename
  script/release-binary
Labels: approved, cla: yes, lgtm
