Repository istio/proxy, pull requests merged in 2018-03, with the labels that each got.

#1180 Switch to Skylark git_repository
  WORKSPACE
  cc_gogo_protobuf.bzl
  googleapis.bzl
  protobuf.bzl
  repositories.bzl
  x_tools_imports.bzl
Labels: approved, cla: yes, lgtm

#1131 Remove unused Dockerfiles and scripts
  docker/Dockerfile.debug
  docker/Dockerfile.release
  docker/proxy-redirection-clear
  docker/proxy-redirection-restore
  prow/proxy-postsubmit.sh
  script/build_proxy_artifacts.yaml
  script/release-docker
  tools/deb/BUILD
  tools/deb/README.md
  tools/deb/istio-iptables.sh
  tools/deb/istio-start.sh
  tools/deb/istio.service
  tools/deb/test/iptables_tests.sh
  tools/deb/test/run_iptables_test.sh
Labels: cla: yes, lgtm

#1182 use Envoy log component filter instead of http
  src/envoy/http/authn/http_filter.h
  src/envoy/http/authn/http_filter_factory.cc
  src/envoy/http/authn/mtls_authentication.h
  src/envoy/http/jwt_auth/http_filter.h
  src/envoy/http/jwt_auth/jwt_authenticator.h
  src/envoy/http/mixer/check_data.h
  src/envoy/http/mixer/control_factory.h
  src/envoy/http/mixer/filter.h
  src/envoy/http/mixer/header_update.h
  src/envoy/utils/grpc_transport.h
Labels: approved, cla: yes, lgtm

#1183 Support bypassing JWT verification for some requests.
  src/envoy/http/jwt_auth/config.proto
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator.h
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
Labels: approved, cla: yes, lgtm

#1186 Extract JWT token from custom locations.
  src/envoy/http/jwt_auth/BUILD
  src/envoy/http/jwt_auth/auth_store.h
  src/envoy/http/jwt_auth/config.proto
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt.h
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator.h
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/jwt_auth/pubkey_cache.h
  src/envoy/http/jwt_auth/token_extractor.cc
  src/envoy/http/jwt_auth/token_extractor.h
  src/envoy/http/jwt_auth/token_extractor_test.cc
Labels: approved, cla: yes, lgtm

#1185 Support es256
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt.h
  src/envoy/http/jwt_auth/jwt_test.cc
  src/envoy/http/jwt_auth/tools/jwk_generator.py
  src/envoy/http/jwt_auth/tools/jwt_generator.py
Labels: cla: yes

#1187 Enable JWT_auth flag: forward_jwt
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator.h
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
Labels: approved, cla: yes, lgtm

#1188 Update API dependencies of proxy
  istio.deps
  repositories.bzl
  src/envoy/http/authn/http_filter.cc
Labels: cla: yes

#1191 Check audience no protocol scheme
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/jwt_auth/pubkey_cache.h
Labels: approved, cla: yes, lgtm

#1176 Update envoy to 07c2bf9
  .circleci/config.yml
  Makefile
  WORKSPACE
  istio.deps
  prow/proxy-presubmit-asan.sh
  prow/proxy-presubmit-tsan.sh
  prow/proxy-presubmit.sh
  src/envoy/http/jwt_auth/http_filter.h
  src/envoy/http/mixer/control.cc
  src/envoy/http/mixer/control.h
  src/envoy/http/mixer/control_factory.h
  src/envoy/tcp/mixer/control.cc
  src/envoy/tcp/mixer/control.h
  src/envoy/tcp/mixer/control_factory.h
  src/envoy/utils/grpc_transport.cc
  src/envoy/utils/grpc_transport.h
  src/envoy/utils/mixer_control.cc
  src/envoy/utils/mixer_control.h
Labels: approved, cla: yes, lgtm

#1202 Fix env vars in Makefile
  .circleci/config.yml
  Makefile
Labels: cla: yes

#1203 Pubkey kid alg optional
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt.h
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/jwt_auth/jwt_test.cc
Labels: approved, cla: no, lgtm

#1171 Boilerplate for istio authn filter.
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/authenticator_base.cc
  src/envoy/http/authn/authenticator_base.h
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/context.proto
  src/envoy/http/authn/filter_context.cc
  src/envoy/http/authn/filter_context.h
  src/envoy/http/authn/filter_context_test.cc
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter.h
  src/envoy/http/authn/http_filter_factory.cc
  src/envoy/http/authn/http_filter_integration_test.cc
  src/envoy/http/authn/http_filter_test.cc
  src/envoy/http/authn/origin_authenticator.cc
  src/envoy/http/authn/origin_authenticator.h
  src/envoy/http/authn/origin_authenticator_test.cc
  src/envoy/http/authn/peer_authenticator.cc
  src/envoy/http/authn/peer_authenticator.h
  src/envoy/http/authn/peer_authenticator_test.cc
  src/envoy/http/authn/test_utils.h
  src/envoy/http/authn/testdata/envoy_empty.conf
  src/envoy/http/authn/testdata/envoy_peer_mtls.conf
Labels: approved, cla: yes, lgtm

#1204 Add authentication result to header if authentication success.
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter.h
  src/envoy/http/authn/http_filter_test.cc
Labels: approved, cla: yes, lgtm

#1205 Upgrade Envoy to newest on master - pre cluster-warming
  WORKSPACE
  istio.deps
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/mixer/report_data.h
  src/envoy/utils/grpc_transport.cc
Labels: approved, cla: yes, lgtm

#1207 Upgrade Envoy to pick up cluster warming feature
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#1208 Workaround for gRPC cluster delivered by CDS
  src/envoy/utils/mixer_control.cc
Labels: cla: yes

#1209 Add tests for validateX509
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/authenticator_base_test.cc
Labels: approved, cla: yes, lgtm

#1211 fix envoy_config used by start_envoy
  src/envoy/http/mixer/envoy.conf.template
Labels: cla: yes

#1218 Update clang version and fix format.
  include/istio/prefetch/quota_prefetch.h
  include/istio/utils/attributes_builder.h
  include/istio/utils/status.h
  script/check-style
  src/envoy/http/authn/http_filter_factory.cc
  src/envoy/http/authn/http_filter_test.cc
  src/envoy/http/authn/origin_authenticator_test.cc
  src/envoy/http/authn/peer_authenticator_test.cc
  src/envoy/http/jwt_auth/http_filter.cc
  src/envoy/http/jwt_auth/http_filter.h
  src/envoy/http/jwt_auth/http_filter_factory.cc
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/jwt_auth/token_extractor_test.cc
  src/envoy/http/mixer/control_factory.h
  src/envoy/http/mixer/filter_factory.cc
  src/envoy/tcp/mixer/control_factory.h
  src/envoy/tcp/mixer/filter_factory.cc
  src/envoy/utils/grpc_transport.cc
  src/envoy/utils/mixer_control.cc
  src/envoy/utils/utils_test.cc
  src/istio/api_spec/http_api_spec_parser_impl.cc
  src/istio/api_spec/http_api_spec_parser_test.cc
  src/istio/api_spec/path_matcher_test.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/request_handler_impl.cc
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/tcp/attributes_builder_test.cc
  src/istio/control/tcp/request_handler_impl_test.cc
  src/istio/mixerclient/attribute_compressor_test.cc
  src/istio/mixerclient/check_cache.cc
  src/istio/mixerclient/check_cache_test.cc
  src/istio/mixerclient/client_impl.cc
  src/istio/mixerclient/client_impl_test.cc
  src/istio/mixerclient/delta_update.cc
  src/istio/mixerclient/quota_cache.cc
  src/istio/mixerclient/quota_cache_test.cc
  src/istio/mixerclient/referenced_test.cc
  src/istio/mixerclient/report_batch.cc
  src/istio/mixerclient/report_batch_test.cc
  src/istio/prefetch/quota_prefetch_test.cc
  src/istio/quota_config/config_parser_impl.cc
  src/istio/quota_config/config_parser_impl_test.cc
Labels: approved, cla: yes, lgtm

#1219 Add support for v1 config.
  src/envoy/http/mixer/filter_factory.cc
  src/envoy/tcp/mixer/filter_factory.cc
  src/envoy/utils/config.cc
  src/envoy/utils/config.h
Labels: approved, cla: yes, lgtm

#1220 Update Envoy SHA to version 1.6.0
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#1221 Move authn context to istio/authn for sharing between filters.
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/authenticator_base.cc
  src/envoy/http/authn/authenticator_base.h
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/filter_context.cc
  src/envoy/http/authn/filter_context.h
  src/envoy/http/authn/filter_context_test.cc
  src/envoy/http/authn/http_filter_test.cc
  src/envoy/http/authn/origin_authenticator.cc
  src/envoy/http/authn/origin_authenticator.h
  src/envoy/http/authn/origin_authenticator_test.cc
  src/envoy/http/authn/peer_authenticator.cc
  src/envoy/http/authn/peer_authenticator.h
  src/envoy/http/authn/peer_authenticator_test.cc
  src/envoy/http/authn/test_utils.h
  src/istio/authn/BUILD
  src/istio/authn/context.proto
Labels: approved, cla: yes, lgtm

#1223 Use bazel --batch
  Makefile
Labels: approved, cla: yes, lgtm

#1222 Fix pre-commit to use clang 5.0
  script/pre-commit
Labels: approved, cla: yes, lgtm

#1234 Add notification for duplication
  src/envoy/http/mixer/README.md
Labels: approved, cla: yes, lgtm

#1235 Fix typo in header guard.
  include/istio/prefetch/quota_prefetch.h
Labels: approved, cla: yes, lgtm

#1237 Let tests build on macOS.
  src/envoy/http/authn/testdata/envoy_empty.conf
  src/envoy/http/authn/testdata/envoy_peer_mtls.conf
  src/envoy/http/jwt_auth/integration_test/envoy.conf.jwk
  src/istio/mixerclient/BUILD
Labels: approved, cla: yes, lgtm

#1236 Remove pessimizing move.
  src/istio/control/http/service_context.cc
Labels: approved, cla: yes, lgtm

#1245 Fix change in authn policy api.
  repositories.bzl
  src/envoy/http/authn/authenticator_base.cc
  src/envoy/http/authn/authenticator_base.h
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/filter_context.cc
  src/envoy/http/authn/filter_context.h
  src/envoy/http/authn/filter_context_test.cc
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/origin_authenticator.cc
  src/envoy/http/authn/origin_authenticator.h
  src/envoy/http/authn/origin_authenticator_test.cc
  src/envoy/http/authn/peer_authenticator.cc
Labels: approved, cla: yes, lgtm

#1244 Run buildifier on all BUILD and bzl files.
  cc_gogo_protobuf.bzl
  googleapis.bzl
  include/istio/utils/BUILD
  protobuf.bzl
  src/envoy/BUILD
  src/envoy/http/authn/BUILD
  src/envoy/http/jwt_auth/BUILD
  src/envoy/http/mixer/BUILD
  src/envoy/tcp/mixer/BUILD
  src/envoy/utils/BUILD
  src/istio/api_spec/BUILD
  src/istio/control/BUILD
  src/istio/control/http/BUILD
  src/istio/control/tcp/BUILD
  src/istio/mixerclient/BUILD
  src/istio/prefetch/BUILD
  src/istio/quota_config/BUILD
  src/istio/utils/BUILD
Labels: approved, cla: yes, lgtm

#1242 Check quota cache hit
  include/istio/mixerclient/BUILD
  include/istio/mixerclient/check_response.h
  include/istio/mixerclient/client.h
  include/istio/mixerclient/environment.h
  src/istio/control/attribute_names.cc
  src/istio/control/attribute_names.h
  src/istio/control/client_context_base.cc
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/mock_mixer_client.h
  src/istio/control/tcp/request_handler_impl_test.cc
  src/istio/mixerclient/client_impl.cc
  src/istio/mixerclient/client_impl.h
  src/istio/mixerclient/client_impl_test.cc
Labels: approved, cla: yes, lgtm

#1216 Validate JWTs in Istio authentication policy using the output of jwt-auth
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/authenticator_base.cc
  src/envoy/http/authn/authenticator_base.h
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/authn/authn_utils.h
  src/envoy/http/authn/http_filter_integration_test.cc
  src/envoy/http/authn/origin_authenticator_test.cc
  src/envoy/http/authn/peer_authenticator_test.cc
  src/envoy/http/authn/testdata/envoy_origin_jwt_authn_only.conf
Labels: approved, cla: yes, lgtm

#1281 [BOT PR] to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1261 Add the allow_missing_or_failed option to jwt-auth
  src/envoy/http/jwt_auth/config.proto
  src/envoy/http/jwt_auth/http_filter.h
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
Labels: approved, cla: yes, lgtm

#1289 [BOT PR] to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1291 [BOT PR] to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1239 Change mixer filter to use authn result data if available
  include/istio/control/http/BUILD
  include/istio/control/http/check_data.h
  include/istio/utils/attributes_builder.h
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter.h
  src/envoy/http/authn/http_filter_test.cc
  src/envoy/http/mixer/BUILD
  src/envoy/http/mixer/check_data.cc
  src/envoy/http/mixer/check_data.h
  src/envoy/utils/BUILD
  src/envoy/utils/authn.cc
  src/envoy/utils/authn.h
  src/envoy/utils/authn_test.cc
  src/istio/control/attribute_names.cc
  src/istio/control/attribute_names.h
  src/istio/control/http/BUILD
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder.h
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/mock_check_data.h
  src/istio/control/tcp/attributes_builder.cc
Labels: approved, cla: yes, lgtm

#1317 [BOT PR] to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1215 Add ALTS support
  WORKSPACE
  src/envoy/BUILD
  src/envoy/alts/BUILD
  src/envoy/alts/README.md
  src/envoy/alts/alts_socket.proto
  src/envoy/alts/alts_socket_factory.cc
  src/envoy/alts/alts_socket_factory.h
  src/envoy/alts/example.yaml
  src/envoy/alts/tsi_frame_protector.cc
  src/envoy/alts/tsi_frame_protector.h
  src/envoy/alts/tsi_handshaker.cc
  src/envoy/alts/tsi_handshaker.h
  src/envoy/alts/tsi_transport_socket.cc
  src/envoy/alts/tsi_transport_socket.h
Labels: approved, cla: yes, lgtm

#1284 Add aud to claims and check it in the tests
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/authn/authn_utils.h
  src/envoy/http/authn/authn_utils_test.cc
  src/envoy/http/authn/http_filter_integration_test.cc
  src/istio/authn/context.proto
Labels: approved, cla: yes, lgtm

#1318 Use StopIterationAndWatermark instead of StopIterationAndBuffer
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/jwt_auth/http_filter.cc
  src/envoy/http/mixer/filter.cc
Labels: approved, cla: yes, lgtm

#1320 build: fix compiler error from gRPC headers
  src/envoy/alts/BUILD
  src/envoy/alts/alts_socket_factory.cc
  src/envoy/alts/transport_security_interface_wrapper.h
  src/envoy/alts/tsi_frame_protector.h
  src/envoy/alts/tsi_handshaker.h
Labels: cla: yes

#1327 Add destination ip and port to report data
  include/istio/control/http/report_data.h
  include/istio/utils/attributes_builder.h
  src/envoy/http/mixer/report_data.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/mock_report_data.h
Labels: approved, cla: yes, lgtm

#1329 Switch authn filter config to envoy facing api
  repositories.bzl
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter.h
  src/envoy/http/authn/http_filter_factory.cc
  src/envoy/http/authn/http_filter_test.cc
  src/envoy/http/authn/testdata/envoy_origin_jwt_authn_only.conf
  src/envoy/http/authn/testdata/envoy_peer_mtls.conf
Labels: approved, cla: yes, lgtm

#1350 Use a bazel.rc for build
  prow/proxy-postsubmit.sh
  prow/proxy-presubmit-asan.sh
  prow/proxy-presubmit-tsan.sh
  prow/proxy-presubmit.sh
  tools/bazel.rc.ci
  tools/bazel.rc.travis
Labels: approved, cla: yes, lgtm

#1338 Update Envoy dependency to support transparent listeners
  WORKSPACE
  istio.deps
Labels: cla: no

#1353 [BOT PR] to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#1352 use bazel --batch for release script
  script/release-binary
Labels: approved, cla: yes, lgtm
