Repository istio/proxy, pull requests merged in 2019-05, with the labels that each got.

#2164 Fix mixer report options documentation
  include/istio/mixerclient/options.h
  src/envoy/http/mixer/README.md
Labels: cla: yes, lgtm, ok-to-test

#2182 Retrieve tracing header from request headers during report
  include/istio/control/http/report_data.h
  include/istio/utils/attributes_builder.h
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/report_data.h
  src/envoy/utils/BUILD
  src/envoy/utils/trace_headers.h
  src/envoy/utils/utils.cc
  src/envoy/utils/utils.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/mock_report_data.h
  test/integration/istio_http_integration_test.cc
Labels: cla: yes, lgtm

#2209 Resolve CI failing: remove bazel shutdown command
  Makefile
Labels: approved, cla: yes, lgtm

#2214 Update Envoy SHA to latest.
  Makefile
  WORKSPACE
  cc_gogo_protobuf.bzl
  googleapis.bzl
  istio.deps
  protobuf.bzl
  repositories.bzl
  test/integration/int_client.cc
  test/integration/int_server.cc
  tsan.suppressions
Labels: approved, cla: yes, lgtm

#2216 repo: add silentdai to owner
  OWNERS
Labels: approved, cla: yes, lgtm

#2217 [BOT PR] to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#2197 Retrieve tracing header from request headers during report
  include/istio/control/http/report_data.h
  include/istio/utils/attributes_builder.h
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/report_data.h
  src/envoy/utils/BUILD
  src/envoy/utils/trace_headers.h
  src/envoy/utils/utils.cc
  src/envoy/utils/utils.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/mock_report_data.h
  test/integration/istio_http_integration_test.cc
Labels: approved, cla: yes, lgtm

#2195 allow batch report to be tuned by either max_entries or max_time
  include/istio/mixerclient/options.h
  src/istio/control/client_context_base.cc
Labels: approved, cla: yes, lgtm, ok-to-test

#2225 Cleanup after bad merge.
  protobuf.bzl
Labels: approved, cla: yes, lgtm

#2226 Update Envoy SHA to latest.
  WORKSPACE
  istio.deps
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/jwt_auth/http_filter.cc
  src/envoy/http/mixer/filter.cc
Labels: cla: yes

#2228 Pull in latest istio/api
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm

#2241 Replace qiwzhang who has left the project with crazyxy.
  OWNERS
Labels: approved, cla: yes, lgtm

#2245 Replace qiwzhang who has left the project with crazyxy. (#2241)
  OWNERS
Labels: approved, cla: yes, lgtm

#2246 remove bazel shutdown command (#2209)
  Makefile
Labels: approved, cla: yes

#2247 Replace qiwzhang who has left the project with crazyxy. (#2241)
  OWNERS
Labels: cla: yes

#2251 Import common files into this repo.
  .commonfiles.sha
  .golangci.yml
  BUGS-AND-FEATURE-REQUESTS.md
  CONTRIBUTING.md
  LICENSE
  Makefile
  Makefile.common.mk
  SUPPORT.md
  prow/proxy-postsubmit.sh
  script/check-license-headers
  scripts/build_proxy_artifacts.yaml
  scripts/check-repository.sh
  scripts/check-style.sh
  scripts/check_license.sh
  scripts/pre-commit
  scripts/push-debian.sh
  scripts/release-binary.sh
  scripts/run_gofmt.sh
  scripts/run_golangci.sh
Labels: approved, cla: yes, lgtm
