Repository istio/proxy, pull requests merged in 2019-02, with the labels that each got.

#2110 Update software in the build image used by CircleCI.
  .circleci/Dockerfile
  .circleci/Makefile
Labels: approved, cla: yes, lgtm

#2111 Add flag indicating current semantics of report batch
  repositories.bzl
  src/istio/mixerclient/attribute_compressor.cc
  src/istio/mixerclient/attribute_compressor_test.cc
Labels: cla: yes, lgtm

#2108 Update Envoy SHA to latest with deterministic hash (master).
  .bazelrc
  .circleci/config.yml
  Makefile
  WORKSPACE
  istio.deps
  script/release-binary
Labels: approved, cla: yes, lgtm

#2109 Update Envoy SHA to latest with deterministic hash (release-1.1).
  .bazelrc
  .circleci/config.yml
  Makefile
  WORKSPACE
  istio.deps
  script/release-binary
Labels: approved, cla: yes, lgtm

#2112 remove unused bytestring include from sni_verifier for openssl
  src/envoy/tcp/sni_verifier/sni_verifier.cc
  src/envoy/tcp/sni_verifier/sni_verifier.h
Labels: approved, cla: yes, lgtm, ok-to-test

#2114 Warn user of using mTLS PERMISSIVE mode and suggest to upgrade to STRICT mode
  src/envoy/http/authn/http_filter.cc
Labels: approved, cla: yes, lgtm

#2115 Update to latest istio/api on release-1.1 branch
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm

#2116 Added simple logging abstraction so mixer client logs can be relayed to envoy logs.
  src/envoy/http/mixer/control_factory.h
  src/istio/control/client_context_base.cc
  src/istio/mixerclient/check_cache.cc
  src/istio/mixerclient/quota_cache.cc
  src/istio/mixerclient/report_batch.cc
  src/istio/prefetch/BUILD
  src/istio/prefetch/quota_prefetch.cc
  src/istio/utils/BUILD
  src/istio/utils/logger.cc
  src/istio/utils/logger.h
  src/istio/utils/logger_test.cc
Labels: approved, cla: yes, lgtm

#2117 Coalesce all memory for checks and reports into shared pointers
  include/istio/mixerclient/check_response.h
  include/istio/mixerclient/client.h
  include/istio/utils/attributes_builder.h
  include/istio/utils/simple_lru_cache_inl.h
  src/envoy/http/mixer/filter.cc
  src/envoy/tcp/mixer/filter.cc
  src/envoy/utils/utils.cc
  src/envoy/utils/utils_test.cc
  src/istio/control/BUILD
  src/istio/control/client_context_base.cc
  src/istio/control/client_context_base.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder.h
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/request_handler_impl.cc
  src/istio/control/http/request_handler_impl.h
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/http/service_context.cc
  src/istio/control/http/service_context.h
  src/istio/control/mock_mixer_client.h
  src/istio/control/request_context.h
  src/istio/control/tcp/attributes_builder.cc
  src/istio/control/tcp/attributes_builder.h
  src/istio/control/tcp/attributes_builder_test.cc
  src/istio/control/tcp/client_context.h
  src/istio/control/tcp/request_handler_impl.cc
  src/istio/control/tcp/request_handler_impl.h
  src/istio/control/tcp/request_handler_impl_test.cc
  src/istio/mixerclient/BUILD
  src/istio/mixerclient/check_cache.h
  src/istio/mixerclient/check_context.h
  src/istio/mixerclient/client_impl.cc
  src/istio/mixerclient/client_impl.h
  src/istio/mixerclient/client_impl_test.cc
  src/istio/mixerclient/quota_cache.h
  src/istio/mixerclient/report_batch.cc
  src/istio/mixerclient/report_batch.h
  src/istio/mixerclient/report_batch_test.cc
  src/istio/mixerclient/shared_attributes.h
Labels: approved, cla: yes, lgtm

#2118 Additional counters for mixer policy check
  include/istio/mixerclient/client.h
  src/envoy/utils/stats.cc
  src/envoy/utils/stats.h
  src/istio/mixerclient/client_impl.cc
  src/istio/mixerclient/client_impl.h
  src/istio/mixerclient/client_impl_test.cc
Labels: approved, cla: yes, lgtm

#2113 Add retries to policy checks on failed transport error
  Makefile
  include/istio/control/http/request_handler.h
  include/istio/control/tcp/request_handler.h
  include/istio/mixerclient/client.h
  include/istio/mixerclient/options.h
  istio.deps
  repositories.bzl
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/filter.h
  src/envoy/tcp/mixer/filter.cc
  src/envoy/tcp/mixer/filter.h
  src/envoy/utils/utils_test.cc
  src/istio/control/client_context_base.cc
  src/istio/control/client_context_base.h
  src/istio/control/http/request_handler_impl.cc
  src/istio/control/http/request_handler_impl.h
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/mock_mixer_client.h
  src/istio/control/tcp/request_handler_impl.cc
  src/istio/control/tcp/request_handler_impl.h
  src/istio/control/tcp/request_handler_impl_test.cc
  src/istio/mixerclient/check_context.h
  src/istio/mixerclient/client_impl.cc
  src/istio/mixerclient/client_impl.h
  src/istio/mixerclient/client_impl_test.cc
  src/istio/mixerclient/report_batch.cc
  test/integration/BUILD
  test/integration/mixer_fault_test.cc
Labels: approved, cla: yes, lgtm

#2120 Import latest release-1.1 istio/api
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm

#2121 Add Joshua into OWNERS.
  OWNERS
Labels: approved, cla: yes

#2125 log authn permissive mode only when config is received
  src/envoy/http/authn/http_filter.cc
  src/envoy/http/authn/http_filter_factory.cc
Labels: approved, cla: yes, lgtm

#2123 clang-6/gcc: compiler barking fix
  src/envoy/http/mixer/control_factory.h
Labels: cla: yes, lgtm

#2128 Add additional telemetry report counters
  include/istio/mixerclient/client.h
  src/envoy/utils/stats.cc
  src/envoy/utils/stats.h
  src/istio/mixerclient/BUILD
  src/istio/mixerclient/client_impl.cc
  src/istio/mixerclient/report_batch.cc
  src/istio/mixerclient/report_batch.h
  src/istio/mixerclient/status_util.cc
  src/istio/mixerclient/status_util.h
  test/integration/mixer_fault_test.cc
Labels: approved, cla: yes, lgtm

#2130 New api sha for proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm

#2131 API sha just changed, changing it again for proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm
