Repository istio/proxy, pull requests merged in 2019-06, with the labels that each got.

#2252 Use envoy-wasm as upstream
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
  WORKSPACE
Labels: approved, cla: yes, lgtm

#2257 Build 1.1.8
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#2259 Build 1.1.8 part 2
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#2262 Add a simple setup for testing communication between 2 envoys
  test/envoye2e/basic_flow/basic_flow_test.go
  test/envoye2e/basic_flow/doc.go
  test/envoye2e/env/envoy.go
  test/envoye2e/env/envoy_conf.go
  test/envoye2e/env/http_client.go
  test/envoye2e/env/http_server.go
  test/envoye2e/env/ports.go
  test/envoye2e/env/setup.go
  test/envoye2e/env/utils.go
Labels: approved, cla: yes, lgtm

#2268 Switch from envoyproxy/envoy to istio/envoy before shipping Istio 1.2
  WORKSPACE
  istio.deps
Labels: approved, cla: yes

#2269 Pick up three istio/envoy cherrypicks for 1.2rc1.
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#2165 [Cherry pick] "Add the support of bypassing JWT authn for CORS requests" to release 1.1
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
Labels: cla: yes, lgtm

#2274 Update istio/envoy to pick up https://github.com/envoyproxy/envoy/pul…
  WORKSPACE
  istio.deps
Labels: approved, cla: yes

#2273 Update Envoy SHA to latest with option to select WASM runtimes.
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm

#2270 Report StopIteration if connection is closed
  src/envoy/tcp/mixer/filter.cc
Labels: approved, cla: yes, lgtm

#2275 add insufficient include
  src/istio/utils/logger.cc
Labels: approved, cla: yes, lgtm

#2279 Format filter.cc
  src/envoy/tcp/mixer/filter.cc
Labels: approved, cla: yes, lgtm

#2277 Report StopIteration if connection is closed (#2270)
  src/envoy/tcp/mixer/filter.cc
Labels: approved, cla: yes

#2278 Report StopIteration if connection is closed (#2270)
  src/envoy/tcp/mixer/filter.cc
Labels: approved, cla: yes

#2280 Update common files.
  .commonfiles.sha
  .golangci.yml
  BUGS-AND-FEATURE-REQUESTS.md
  LICENSE
  Makefile.common.mk
  scripts/check_license.sh
  scripts/run_gofmt.sh
  scripts/run_golangci.sh
Labels: approved, cla: yes, lgtm

#2281 Set Istio authn filter to prefer using Envoy jwt filter if found
  src/envoy/http/authn/filter_context.cc
  src/envoy/http/authn/filter_context.h
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  test/integration/BUILD
  test/integration/istio_http_integration_test_with_envoy_jwt_filter.cc
Labels: approved, cla: yes, lgtm

#2287 Fix checks.
  .circleci/config.yml
  Makefile
  prow/proxy-presubmit.sh
  src/envoy/http/authn/filter_context.cc
  src/envoy/http/authn/filter_context.h
  test/integration/istio_http_integration_test_with_envoy_jwt_filter.cc
Labels: approved, cla: yes, lgtm

#2289 Limit resource usage on Prow.
  .circleci/Dockerfile
  .circleci/config.yml
  Makefile
  prow/proxy-postsubmit.sh
  prow/proxy-presubmit-asan.sh
  prow/proxy-presubmit-tsan.sh
  prow/proxy-presubmit.sh
  scripts/release-binary.sh
  tools/bazel.rc.ci
Labels: approved, cla: yes, lgtm

#2286 Update Envoy WASM sha to the latest
  .circleci/Makefile
  WORKSPACE
  repositories.bzl
  src/envoy/http/jwt_auth/http_filter_factory.cc
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/utils/grpc_transport.cc
  src/envoy/utils/grpc_transport.h
  src/envoy/utils/mixer_control.cc
  src/istio/control/client_context_base.cc
  test/integration/int_server.cc
  test/integration/int_server.h
Labels: approved, cla: yes, lgtm

#2291 Fix header parsing in JWT filter
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt.h
  src/envoy/http/jwt_auth/jwt_test.cc
Labels: approved, cla: yes, lgtm

#2292 [1.2] Fix header parsing in JWT filter
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt.h
  src/envoy/http/jwt_auth/jwt_test.cc
Labels: cla: yes

#2293 [1.1] Fix header parsing in JWT filter
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt.h
  src/envoy/http/jwt_auth/jwt_test.cc
Labels: cla: yes, lgtm

#2294 [1.0] Fix header parsing in JWT filter
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt.h
  src/envoy/http/jwt_auth/jwt_test.cc
Labels: cla: yes

#2295 Update Envoy-WASM SHA to latest.
  .bazelrc
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
  WORKSPACE
  istio.deps
  src/envoy/utils/grpc_transport.cc
  src/envoy/utils/grpc_transport.h
Labels: approved, cla: yes, lgtm

#2296 build: update clang and clang-format to version 8.0.0.
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
  Makefile
  scripts/check-style.sh
  scripts/pre-commit
  scripts/release-binary.sh
  src/istio/prefetch/quota_prefetch.cc
  test/integration/int_server.cc
  test/integration/int_server.h
Labels: approved, cla: yes, lgtm
