Repository istio/proxy, pull requests merged in 2019-10, with the labels that each got.

#2427 fix(metadata filter): update metadata exchange filter to new EnvoyFilter API
  extensions/stats/testdata/istio/metadata-exchange_filter.yaml
Labels: cla: yes, size/M

#2325 Metadata Exchange Filter
  src/envoy/BUILD
  src/envoy/tcp/metadata_exchange/BUILD
  src/envoy/tcp/metadata_exchange/config.cc
  src/envoy/tcp/metadata_exchange/config.h
  src/envoy/tcp/metadata_exchange/config/BUILD
  src/envoy/tcp/metadata_exchange/config/metadata_exchange.proto
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange.h
  src/envoy/tcp/metadata_exchange/metadata_exchange_initial_header.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange_initial_header.h
  src/envoy/tcp/metadata_exchange/metadata_exchange_test.cc
  test/envoye2e/basic_tcp_flow/basic_tcp_flow_test.go
  test/envoye2e/env/ports.go
  test/envoye2e/env/setup.go
  test/envoye2e/env/tcp_envoy_conf.go
  test/envoye2e/env/tcp_server.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
  test/envoye2e/tcp_metadata_exchange/cert-chain.pem
  test/envoye2e/tcp_metadata_exchange/doc.go
  test/envoye2e/tcp_metadata_exchange/key.pem
  test/envoye2e/tcp_metadata_exchange/root-cert.pem
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: cla: yes, size/XXL

#2440 fix(api dep): update to latest istio/api commit
  repositories.bzl
Labels: cla: yes, size/XS

#2442 Clean up a TODO about opencensus library
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/XS

#2433 Add metadata exchange filter yaml file with wasm
  extensions/stats/testdata/istio/metadata-exchange_with_wasm_filter.yaml
Labels: cla: yes, size/M

#2444 update istio/api to latest commit
  repositories.bzl
Labels: cla: yes, size/S

#2446 [1.2] mixer: calculate header size if cache invalidated
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/report_data.h
  test/integration/int_client.cc
Labels: cla: yes, size/S

#2448 Fix mixerv2 filter names
  extensions/stats/testdata/istio/metadata-exchange_filter.yaml
  extensions/stats/testdata/istio/stats_filter.yaml
Labels: cla: yes, size/XS

#2439 feat(edges): add support for meshtelemetry edge export
  extensions/common/context.cc
  extensions/common/node_info.proto
  extensions/stackdriver/common/BUILD
  extensions/stackdriver/edges/BUILD
  extensions/stackdriver/edges/TODO
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter.h
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/edges/edges.proto
  extensions/stackdriver/edges/mesh_edges_service_client.cc
  extensions/stackdriver/edges/mesh_edges_service_client.h
Labels: cla: yes, size/XL

#2445 update envoy-wasm
  WORKSPACE
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/istio/metadata-exchange_filter.yaml
  extensions/stats/testdata/istio/stats_filter.yaml
  extensions/stats/testdata/server.yaml
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/L

#2449 Sync .bazelrc with upstream.
  .bazelrc
  Makefile
  WORKSPACE
Labels: cla: yes, size/M

#2451 Publish release binary with symbols and AddressSanitizer.
  scripts/release-binary.sh
Labels: cla: yes, size/S

#2447 [1.1] mixer: calculate header size if cache invalidated
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/report_data.h
  test/integration/int_client.cc
Labels: cla: yes, size/S

#2455 Update envoy SHA for istio/istio#17699.
  WORKSPACE
Labels: cla: yes, size/XS

#2457 fix server.yaml with correct name
  Makefile
  extensions/stats/testdata/server.yaml
Labels: cla: yes, size/XS

#2450 add alpn http filter
  src/envoy/BUILD
  src/envoy/http/alpn/BUILD
  src/envoy/http/alpn/alpn_filter.cc
  src/envoy/http/alpn/alpn_filter.h
  src/envoy/http/alpn/alpn_test.cc
  src/envoy/http/alpn/config.cc
  src/envoy/http/alpn/config.h
  src/envoy/http/alpn/config_test.cc
  src/envoy/utils/filter_names.cc
  src/envoy/utils/filter_names.h
Labels: cla: yes, size/L

#2456 mixer: add hash policy for maglev
  WORKSPACE
  include/istio/control/http/BUILD
  src/envoy/http/authn/BUILD
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/report_data.h
  src/envoy/utils/BUILD
  src/envoy/utils/grpc_transport.cc
  src/istio/control/http/BUILD
  test/integration/int_client.cc
  test/integration/int_server.cc
Labels: cla: yes, size/M

#2463 Fix root context
  extensions/stats/plugin.h
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/istio/stats_filter.yaml
  extensions/stats/testdata/server.yaml
Labels: cla: yes, size/M

#2461 Mixerless metric label parity
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stats/plugin.h
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/server.yaml
  test/envoye2e/env/envoy_conf.go
  test/envoye2e/stackdriver_plugin/fake_stackdriver/timeseries.go
Labels: cla: yes, size/L

#2464 Update Envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2458 Add usage of sd logger and an e2e test
  extensions/stackdriver/BUILD
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/log/exporter.h
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  test/envoye2e/stackdriver_plugin/fake_stackdriver/data.go
  test/envoye2e/stackdriver_plugin/fake_stackdriver/fake_stackdriver.go
  test/envoye2e/stackdriver_plugin/fake_stackdriver/timeseries.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/XL

#2462 feat(forwarded attributes): add support for ignore_forwarded_attributes
  src/istio/control/http/request_handler_impl.cc
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/http/service_context.h
Labels: cla: yes, size/M

#2452 Use FilterState instead of DynamicMetadata in Metadata Exchange Filter
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/context_test.cc
  extensions/metadata_exchange/BUILD
  extensions/metadata_exchange/plugin.cc
  src/envoy/tcp/metadata_exchange/BUILD
  src/envoy/tcp/metadata_exchange/config.cc
  src/envoy/tcp/metadata_exchange/config/metadata_exchange.proto
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange.h
  src/envoy/tcp/metadata_exchange/metadata_exchange_test.cc
  test/envoye2e/env/setup.go
  test/envoye2e/env/tcp_envoy_conf.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: cla: yes, size/L

#2465 feat(stackdriver): add support for gce_instance MR
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/metric/registry.cc
  extensions/stackdriver/metric/registry_test.cc
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/L

#2466 Fix SD filter root context and update e2e test
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  test/envoye2e/env/envoy_conf.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/M

#2471 Remove extra inbound listener from envoy config in sd test
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/S

#2469 Run go tests with sanitizers.
  Makefile
  prow/proxy-presubmit.inc
  prow/proxy-presubmit.sh
Labels: cla: yes, size/S

#2470 Update Envoy-WASM SHA to latest.
  .bazelrc
  WORKSPACE
  test/integration/int_server.h
Labels: cla: yes, size/S

#2473 remove config time build metric
  extensions/stats/plugin.cc
Labels: cla: yes, size/XS

#2476 - Preparing release 1.2.8
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2475 Retire Linux jobs for istio/proxy on CircleCI.
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
Labels: cla: yes, size/L

#2478 Update Clang and libc++ to version 9.0.
  Makefile
  scripts/release-binary.sh
Labels: cla: yes, size/XS

#2474 Fix building extensions as WebAssembly modules.
  extensions/metadata_exchange/Makefile
  extensions/metadata_exchange/build_wasm.sh
  extensions/metadata_exchange/plugin.cc
  extensions/stats/build_wasm.sh
  extensions/stats/plugin.cc
Labels: cla: yes, size/S

#2482 remove response header and not request header
  extensions/metadata_exchange/plugin.cc
Labels: cla: yes, size/XS

#2479 use different alpn override for different upstream protocol
  repositories.bzl
  src/envoy/http/alpn/BUILD
  src/envoy/http/alpn/alpn_filter.cc
  src/envoy/http/alpn/alpn_filter.h
  src/envoy/http/alpn/alpn_test.cc
  src/envoy/http/alpn/config.cc
  src/envoy/http/alpn/config.h
  src/envoy/http/alpn/config_test.cc
Labels: cla: yes, size/L

#2481 Update Envoy-WASM SHA to latest.
  .bazelrc
  WORKSPACE
  extensions/metadata_exchange/Makefile
  extensions/metadata_exchange/build_wasm.sh
  extensions/stats/Makefile
  extensions/stats/build_wasm.sh
  src/envoy/http/mixer/filter_factory.cc
Labels: cla: yes, size/S

#2468 feat(edges): enable edge reporting in stackdriver extension
  extensions/stackdriver/BUILD
  extensions/stackdriver/config/v1alpha1/BUILD
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/edges/TODO
  extensions/stackdriver/edges/mesh_edges_service_client.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
Labels: cla: yes, size/M

#2483 Expose GCS build and artifact buckets as variables
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/XS

#2485 Update release-binary.sh
  scripts/release-binary.sh
Labels: cla: yes, size/XS

#2484 Update the Envoy SHA.
  WORKSPACE
Labels: cla: yes, size/XS

#2489 Use the same Envoy SHA in istio.deps as in WORKSPACE for consistency
  istio.deps
Labels: cla: yes, size/XS

#2491 Add Prow presubmit verifying that the release scripts work.
  prow/proxy-common.inc
  prow/proxy-postsubmit.sh
  prow/proxy-presubmit-asan.sh
  prow/proxy-presubmit-release.sh
  prow/proxy-presubmit-tsan.sh
  prow/proxy-presubmit.sh
Labels: cla: yes, size/M

#2480 ci: add docker push postsubmit
  .bazelrc
  WORKSPACE
  scripts/release-binary.sh
  tools/bazel_get_workspace_status
  tools/docker/BUILD
Labels: cla: yes, size/L

#2487 Make onconfigure work with multiple calls
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/stackdriver.cc
  extensions/stats/plugin.wasm
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/L

#2493 Update Envoy-WASM SHA to latest.
  .bazelrc
  WORKSPACE
  test/integration/int_server.h
Labels: cla: yes, size/S

#2495 release: fix the bash script
  scripts/release-binary.sh
Labels: cla: yes, size/XS

#2494 Add mesh_uid to sd metrics and log
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/metric/record.cc
  test/envoye2e/stackdriver_plugin/fake_stackdriver/data.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/S

#2497 wasm: use raw bytes for filter state, add custom struct parser
  WORKSPACE
  extensions/common/BUILD
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/context_speed_test.cc
  extensions/common/context_test.cc
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange.h
Labels: cla: yes, size/L

#2486 fix(edges reporting): fix error in reporting logic
  extensions/stackdriver/edges/BUILD
  extensions/stackdriver/edges/TODO
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/stackdriver.h
  go.mod
  go.sum
  test/envoye2e/stackdriver_plugin/edges/edges.pb.go
  test/envoye2e/stackdriver_plugin/edges/go.mod
  test/envoye2e/stackdriver_plugin/fake_stackdriver/fake_stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/L

#2492 Avoid capturing logger pointer in callback lambda
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/log/exporter.h
Labels: cla: yes, size/S

#2499 Update Envoy-WASM SHA to latest.
  WORKSPACE
Labels: cla: yes, size/XS

#2454 Move node_info_cache to common
  extensions/common/BUILD
  extensions/common/node_info_cache.cc
  extensions/common/node_info_cache.h
  extensions/stackdriver/BUILD
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stats/BUILD
  extensions/stats/config.proto
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/L

#2500 Update Envoy-WASM SHA to latest.
  WORKSPACE
Labels: cla: yes, size/XS

#2501 Fix sd plugin typo
  extensions/stackdriver/stackdriver.cc
Labels: cla: yes, size/XS
