Repository istio/proxy, pull requests merged in 2019-12, with the labels that each got.

#2588 [release-1.4] Update release binary script
  Makefile.core.mk
  scripts/release-binary.sh
Labels: cla: yes, size/S

#2589 update envoy-wasm to latest
  WORKSPACE
  src/envoy/http/alpn/config.cc
  src/envoy/http/alpn/config.h
  src/envoy/http/authn/http_filter_factory.cc
  src/envoy/http/jwt_auth/http_filter_factory.cc
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/jwt_auth/jwt_test.cc
  src/envoy/http/mixer/filter_factory.cc
  src/envoy/tcp/forward_downstream_sni/config.cc
  src/envoy/tcp/forward_downstream_sni/config.h
  src/envoy/tcp/metadata_exchange/config.h
  src/envoy/tcp/mixer/filter_factory.cc
  src/envoy/tcp/sni_verifier/config.cc
  src/envoy/tcp/sni_verifier/config.h
  src/envoy/tcp/tcp_cluster_rewrite/config.cc
  src/envoy/tcp/tcp_cluster_rewrite/config.h
  src/istio/utils/BUILD
  test/integration/int_client_server_test.cc
  test/integration/int_server.cc
  test/integration/int_server.h
  test/integration/mixer_fault_test.cc
Labels: cla: yes, size/L

#2590 update envoyproxy/envoy-wasm
  WORKSPACE
Labels: cla: yes, size/XS

#2592 fix(edges): remove unknown defaults
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
Labels: cherrypick/release-1.4, cla: yes, size/M

#2591 expose service port in stats
  extensions/stats/plugin.h
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/server.yaml
  test/envoye2e/stats_plugin/stats_plugin_test.go
  testdata/bootstrap/stats.yaml.tmpl
  testdata/metric/client_request_total.yaml.tmpl
  testdata/metric/server_request_total.yaml.tmpl
Labels: cla: yes, size/S

#2597 Update Envoy SHA to HEAD of istio/envoy:release-1.3
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2599 Cherrypick 1.4.2 and increase mixer fault test timeout
  WORKSPACE
  test/integration/mixer_fault_test.cc
Labels: cla: yes, size/XS

#2600 Update envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2593 fix(edges): remove unknown defaults
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
Labels: cla: yes, size/M

#2594 Add options to build envoy in tsan and asan mode for local testing
  Makefile.core.mk
Labels: cla: yes, size/XS

#2601 Increase OC interval to 60s
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/stackdriver.cc
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
Labels: cla: yes, size/S

#2603 Update proxy to latest envoy-wasm
  WORKSPACE
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/report_data.h
  src/envoy/utils/grpc_transport.cc
Labels: cla: yes, size/S

#2604 Increase OC interval to 60s (#2601)
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/stackdriver.cc
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
Labels: cla: yes, size/S

#2605 Use SimpleAtoi instead of std::atoi to convert interval
  extensions/stackdriver/stackdriver.cc
Labels: cla: yes, size/XS

#2548 Extract service name from request host and cluster name
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/metric/record.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  scripts/check-style.sh
  testdata/metric/client_request_total.yaml.tmpl
  testdata/stackdriver/client_request_count.yaml.tmpl
Labels: cherrypick/release-1.4, cla: yes, size/L

#2607 Try deflake lru cache test
  src/istio/utils/simple_lru_cache_test.cc
Labels: cla: yes, size/XS

#2611 update common file
  Makefile
  Makefile.core.mk
  Makefile.overrides.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
  common/scripts/report_build_info.sh
  scripts/check-build-tools-proxy.sh
Labels: cla: yes, size/M

#2613 Avoid an expensive copy of ReportRequest.
  src/istio/mixerclient/report_batch.cc
Labels: cla: yes, ok-to-test, size/XS
