Repository istio/proxy, pull requests merged in 2019-01, with the labels that each got.

#2075 address comment
  src/envoy/http/jwt_auth/token_extractor.cc
Labels: approved, cla: yes, lgtm

#2074 update envoy sha
  WORKSPACE
  istio.deps
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/jwt_auth/integration_test/envoy.conf.jwk
  src/envoy/http/jwt_auth/integration_test/envoy_allow_missing_or_failed_jwt.conf.jwk
  src/envoy/http/jwt_auth/token_extractor.cc
Labels: approved, cla: yes, lgtm

#2076 rename rbac permissive related attributes key due to envoy recent change
  src/envoy/http/mixer/report_data.h
Labels: approved, cla: yes, lgtm

#2078 Merge release-1.1 into master
  WORKSPACE
  istio.deps
  repositories.bzl
  src/envoy/BUILD
  src/envoy/http/authn/authenticator_base.cc
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/authn/authn_utils.h
  src/envoy/http/authn/sample/APToken/APToken-example1.jwt
  src/envoy/http/authn/sample/APToken/aptoken-envoy.conf
  src/envoy/http/authn/sample/APToken/guide.txt
  src/envoy/http/jwt_auth/integration_test/envoy.conf.jwk
  src/envoy/http/jwt_auth/integration_test/envoy_allow_missing_or_failed_jwt.conf.jwk
  src/envoy/http/jwt_auth/token_extractor.cc
  src/envoy/http/jwt_auth/token_extractor_test.cc
  src/envoy/http/mixer/report_data.h
  src/envoy/tcp/mixer/filter.cc
  src/envoy/tcp/mixer/filter.h
  src/envoy/tcp/sni_verifier/BUILD
  src/envoy/tcp/sni_verifier/config.cc
  src/envoy/tcp/sni_verifier/config.h
  src/envoy/tcp/sni_verifier/sni_verifier.cc
  src/envoy/tcp/sni_verifier/sni_verifier.h
  src/envoy/tcp/sni_verifier/sni_verifier_test.cc
  src/envoy/utils/grpc_transport.cc
  test/integration/BUILD
  test/integration/exchanged_token_integration_test.cc
Labels: cla: yes, lgtm

#2080 Removes dangling pointer in capture list of lambda function.
  src/envoy/http/jwt_auth/auth_store.h
  src/envoy/http/mixer/control_factory.h
  src/envoy/tcp/mixer/control_factory.h
Labels: approved, cla: yes, lgtm

#2083 Use shared_ptr to protect members which are passed to capture list of lambda function.
  src/envoy/http/jwt_auth/auth_store.h
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/mixer/control.cc
  src/envoy/http/mixer/control.h
  src/envoy/http/mixer/control_factory.h
  src/envoy/tcp/mixer/control.cc
  src/envoy/tcp/mixer/control.h
  src/envoy/tcp/mixer/control_factory.h
Labels: approved, cla: yes, lgtm

#2082 Update Envoy SHA to latest with protobuf.Any configs (release-1.1).
  WORKSPACE
  istio.deps
  protobuf.bzl
  src/envoy/http/jwt_auth/integration_test/envoy.conf
  src/envoy/http/jwt_auth/integration_test/envoy.conf.jwk
  src/envoy/http/jwt_auth/integration_test/envoy_allow_missing_or_failed_jwt.conf.jwk
Labels: approved, cla: yes, lgtm

#2084 Update Istio API to latest (1.1 branch)
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm

#2085 Merge release-1.1 into master
  WORKSPACE
  istio.deps
  protobuf.bzl
  repositories.bzl
  src/envoy/http/jwt_auth/auth_store.h
  src/envoy/http/jwt_auth/integration_test/envoy.conf
  src/envoy/http/jwt_auth/integration_test/envoy.conf.jwk
  src/envoy/http/jwt_auth/integration_test/envoy_allow_missing_or_failed_jwt.conf.jwk
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/mixer/control.cc
  src/envoy/http/mixer/control.h
  src/envoy/http/mixer/control_factory.h
  src/envoy/tcp/mixer/control.cc
  src/envoy/tcp/mixer/control.h
  src/envoy/tcp/mixer/control_factory.h
Labels: approved, cla: yes, lgtm

#2087 use route directive regardless of rpc status
  src/envoy/http/mixer/filter.cc
  src/istio/mixerclient/check_cache.h
Labels: approved, cla: yes, lgtm

#2088 Run buildifier on the build files and add it to "make check".
  BUILD
  WORKSPACE
  cc_gogo_protobuf.bzl
  googleapis.bzl
  include/istio/mixerclient/BUILD
  include/istio/utils/BUILD
  protobuf.bzl
  script/check-style
  src/envoy/BUILD
  src/envoy/http/authn/BUILD
  src/envoy/http/jwt_auth/BUILD
  src/envoy/tcp/forward_downstream_sni/BUILD
  src/envoy/tcp/sni_verifier/BUILD
  src/envoy/tcp/tcp_cluster_rewrite/BUILD
  src/envoy/utils/BUILD
  src/istio/control/tcp/BUILD
  src/istio/utils/BUILD
  test/integration/BUILD
  tools/deb/BUILD
  x_tools_imports.bzl
Labels: approved, cla: yes, lgtm

#2090 Fix build on macOS.
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#1987 [typo-fix] typo of the variable use_count -> wrote use_cound instead
  src/istio/mixerclient/check_cache.h
Labels: approved, cla: yes, lgtm

#2091 Upgrade Envoy to b3be5713f
  .circleci/config.yml
  WORKSPACE
  istio.deps
  src/envoy/http/mixer/filter.h
  src/envoy/tcp/sni_verifier/BUILD
  src/envoy/tcp/sni_verifier/sni_verifier_test.cc
Labels: approved, cla: yes, lgtm

#2094 Fix macOS build
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#2093 add mixer error details into metadata
  src/envoy/http/mixer/filter.cc
  src/envoy/tcp/mixer/filter.cc
  src/envoy/tcp/mixer/filter.h
  src/envoy/utils/BUILD
  src/envoy/utils/utils.cc
  src/envoy/utils/utils.h
  src/envoy/utils/utils_test.cc
Labels: approved, cla: yes, lgtm

#2095 Merge release-1.1 into master. (Final batch)
  WORKSPACE
  istio.deps
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/filter.h
  src/envoy/tcp/mixer/filter.cc
  src/envoy/tcp/mixer/filter.h
  src/envoy/tcp/sni_verifier/BUILD
  src/envoy/tcp/sni_verifier/sni_verifier_test.cc
  src/envoy/utils/BUILD
  src/envoy/utils/utils.cc
  src/envoy/utils/utils.h
  src/envoy/utils/utils_test.cc
  src/istio/mixerclient/check_cache.h
Labels: cla: yes

#2097 Forwarded attributes override statically configured Local Attributes
  Makefile
  include/istio/utils/attribute_names.h
  src/istio/control/http/attributes_builder.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/http/request_handler_impl.cc
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/utils/attribute_names.cc
Labels: approved, cla: yes, lgtm

#2098 ignore istio.mixer in report
  include/istio/utils/attributes_builder.h
  src/envoy/utils/utils.cc
  src/istio/control/http/attributes_builder_test.cc
  src/istio/control/tcp/attributes_builder_test.cc
Labels: approved, cla: yes, lgtm

#2100 Whitelist kSourceNamespace attribute
  src/istio/control/http/attributes_builder.cc
Labels: approved, cla: yes, lgtm

#2101 fix conflicted
  .circleci/Dockerfile
  .circleci/Makefile
  Makefile
  WORKSPACE
Labels: approved, cla: yes, lgtm
