Repository istio/proxy, pull requests merged in 2019-08, with the labels that each got.

#2328 Update envoy sha
  WORKSPACE
  extensions/stackdriver/opencensus/io_opencensus_cpp_null.patch
  extensions/stackdriver/opencensus/opencensus.bzl
  repositories.bzl
Labels: approved, cla: yes, lgtm, size/L

#2335 Add a CODEOWNERS, will delete OWNERS separately.
  CODEOWNERS
Labels: cla: yes, size/XS

#2336 Delete obsolete OWNERS file.
  OWNERS
Labels: cla: yes, size/S

#2334 Adding gcloud auth to fix the test
  prow/proxy-postsubmit.sh
Labels: approved, cla: yes, lgtm, size/XS

#2337 Fix missing GIT_SHA from post submit
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/XS

#2338 using sha instead of of git_sha
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/XS

#2340 Revert "Update common files. (#2339)"
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  scripts/check_dockerfiles.sh
  scripts/run_gobindata.sh
Labels: cla: yes, size/L

#2341 Add myself to CODEOWNERS.
  CODEOWNERS
Labels: cla: yes, size/XS

#2342 Fix static linking.
  .bazelrc
  src/envoy/http/authn/http_filter_integration_test.cc
Labels: approved, cla: yes, size/M

#2344 Stop publishing release binaries as debug binaries.
  scripts/release-binary.sh
Labels: cla: yes, size/S

#2345 Fix postsubmit.
  scripts/push-debian.sh
Labels: cla: yes, size/XS

#2343 Revert "using sha instraf of git_sha (#2338)"
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/XS

#2346 Update Envoy-WASM SHA to latest.
  WORKSPACE
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/common/context.h
  extensions/stackdriver/metric/registry.h
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stats/plugin.cc
  istio.deps
  src/envoy/http/metadata_exchange/config.cc
  src/envoy/http/metadata_exchange/config.h
  test/integration/int_client.cc
  test/integration/int_server.cc
Labels: cla: yes, size/L

#2347 Properly export PATH, CC and CXX variables to Bazel.
  .bazelrc
  Makefile
  scripts/release-binary.sh
Labels: cla: yes, size/M

#2322 Add function to record SD metrics
  extensions/stackdriver/BUILD
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/config/v1alpha1/BUILD
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/metric/BUILD
  extensions/stackdriver/metric/record.cc
  extensions/stackdriver/metric/record.h
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
Labels: cla: yes, size/L

#2349 Migrate SD to use extension common package
  extensions/stackdriver/BUILD
  extensions/stackdriver/common/BUILD
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/context.cc
  extensions/stackdriver/common/context.h
  extensions/stackdriver/common/context_test.cc
  extensions/stackdriver/common/node_info.proto
  extensions/stackdriver/metric/BUILD
  extensions/stackdriver/metric/record.cc
  extensions/stackdriver/metric/record.h
  extensions/stackdriver/metric/registry.cc
  extensions/stackdriver/metric/registry.h
  extensions/stackdriver/metric/registry_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
Labels: cla: yes, size/L

#2350 Update Envoy-WASM SHA to latest.
  .bazelrc
  WORKSPACE
  istio.deps
Labels: cla: yes, size/S

#2348 Always publish release packages.
  Makefile
  scripts/push-debian.sh
Labels: cla: yes, size/S

#2351 Fix previous commit.
  Makefile
Labels: cla: yes, size/XS

#2352 Test the release scripts.
  .circleci/config.yml
  Makefile
  prow/proxy-postsubmit.sh
  scripts/push-debian.sh
  scripts/release-binary.sh
Labels: cla: yes, size/L

#2353 Remove hardcoded defaults from the release scripts.
  .circleci/config.yml
  Makefile
  prow/proxy-postsubmit.sh
  scripts/build_proxy_artifacts.yaml
  scripts/release-binary.sh
Labels: cla: yes, size/M

#2355 Update Envoy-WASM SHA to latest with security fixes.
  WORKSPACE
  extensions/common/BUILD
  extensions/common/context.cc
  extensions/stackdriver/BUILD
  extensions/stackdriver/stackdriver.h
  extensions/stackdriver/stackdriver_plugin_factory.cc
  extensions/stats/BUILD
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  istio.deps
  src/envoy/http/metadata_exchange/BUILD
  src/envoy/http/metadata_exchange/config.cc
  src/envoy/http/metadata_exchange/config.h
  test/integration/int_server.cc
  test/integration/int_server.h
Labels: cla: yes, size/M

#2356 Set release managers as CODEOWNERS for release-1.3
  CODEOWNERS
Labels: area/test and release, cla: yes, size/XS

#2360 fix a logging issue in authN filter
  src/envoy/http/authn/authenticator_base.cc
Labels: action/merge-to-release-1.3-branch, cla: yes, size/XS

#2357 Always link against libc++.
  .bazelrc
  Makefile
  scripts/push-debian.sh
  scripts/release-binary.sh
Labels: cla: yes, size/M

#2361 [1.3] fix a logging issue in authN filter (#2360)
  src/envoy/http/authn/authenticator_base.cc
Labels: cla: yes, size/XS

#2362 Update envoy-wasm SHA
  WORKSPACE
  istio.deps
Labels: cla: yes, size/S

#2354 Expose telemetry on TCP new Connection callback
  include/istio/control/tcp/request_handler.h
  src/envoy/tcp/mixer/filter.cc
  src/istio/control/tcp/request_handler_impl.cc
  src/istio/control/tcp/request_handler_impl.h
  src/istio/control/tcp/request_handler_impl_test.cc
Labels: cla: yes, size/S

#2366 Deprecate HTTP API Spec
  include/istio/api_spec/BUILD
  include/istio/api_spec/http_api_spec_parser.h
  src/istio/api_spec/BUILD
  src/istio/api_spec/http_api_spec_parser_impl.cc
  src/istio/api_spec/http_api_spec_parser_impl.h
  src/istio/api_spec/http_api_spec_parser_test.cc
  src/istio/api_spec/http_template.cc
  src/istio/api_spec/http_template.h
  src/istio/api_spec/http_template_test.cc
  src/istio/api_spec/path_matcher.h
  src/istio/api_spec/path_matcher_node.cc
  src/istio/api_spec/path_matcher_node.h
  src/istio/api_spec/path_matcher_test.cc
  src/istio/control/http/BUILD
  src/istio/control/http/request_handler_impl.cc
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/http/service_context.cc
  src/istio/control/http/service_context.h
Labels: cla: yes, size/XXL

#2368 Update Envoy-WASM SHA to latest with security fixes. (#2355)
  WORKSPACE
  extensions/common/BUILD
  extensions/common/context.cc
  extensions/stackdriver/BUILD
  extensions/stackdriver/stackdriver.h
  extensions/stackdriver/stackdriver_plugin_factory.cc
  extensions/stats/BUILD
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  istio.deps
  src/envoy/http/metadata_exchange/BUILD
  src/envoy/http/metadata_exchange/config.cc
  src/envoy/http/metadata_exchange/config.h
  test/integration/int_server.cc
  test/integration/int_server.h
Labels: cla: yes, size/M

#2369 Always link against libc++. (#2357)
  .bazelrc
  Makefile
  scripts/push-debian.sh
  scripts/release-binary.sh
Labels: cla: yes, size/M

#2372 Update Envoy SHA to point to same commit in istio/envoy:release-1.3
  WORKSPACE
  istio.deps
Labels: cla: yes, size/S

#2365 update metadata exchange for the new bootstrap format
  src/envoy/http/metadata_exchange/config.cc
  src/envoy/http/metadata_exchange/config.h
  src/envoy/http/metadata_exchange/testdata/client.yaml
  src/envoy/http/metadata_exchange/testdata/server.yaml
Labels: cla: yes, size/L

#2373 change username
  CODEOWNERS
Labels: cla: yes, size/XS

#2371 Use Bazelisk launcher for Bazel.
  .bazelversion
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
Labels: cla: yes, size/M

#2376 Use Bazelisk launcher for Bazel. (#2371)
  .bazelversion
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
Labels: cla: yes, size/M

#2375 Update to clang/libc++ 8 and Bazelisk launcher for Bazel.
  .bazelversion
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
  Makefile
  prow/proxy-presubmit-asan.sh
  prow/proxy-presubmit-tsan.sh
  prow/proxy-presubmit.sh
  script/release-binary
Labels: cla: yes, size/M

#2374 Update to clang/libc++ 8 and Bazelisk launcher for Bazel.
  .bazelversion
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
  Makefile
  prow/proxy-presubmit-asan.sh
  prow/proxy-presubmit-tsan.sh
  prow/proxy-presubmit.sh
  script/release-binary
Labels: cla: yes, size/L

#2377 Update Envoy SHA to latest with memory access fixes.
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2379 Update Envoy SHA to latest with memory access fixes.
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2381 [release-1.3] Expose telemetry on TCP new Connection callback
  include/istio/control/tcp/request_handler.h
  src/envoy/tcp/mixer/filter.cc
  src/istio/control/tcp/request_handler_impl.cc
  src/istio/control/tcp/request_handler_impl.h
  src/istio/control/tcp/request_handler_impl_test.cc
Labels: cla: yes, size/S

#2380 Sync istio/api SHA in istio.deps to match repositories.bzl
  istio.deps
Labels: cla: yes, size/XS

#2378 Update Envoy SHA to latest with memory access fixes.
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2367 Fix separator, stat_prefix and listener.traffic_direction
  WORKSPACE
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/context_test.cc
  extensions/common/node_info.proto
  extensions/stackdriver/metric/registry.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stats/config.proto
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/run_test.sh
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/server.yaml
  src/envoy/http/metadata_exchange/config.cc
  test/integration/mixer_fault_test.cc
Labels: cla: yes, size/L

#2383 Cherry pick exchange metadata updates and statname fixes.
  WORKSPACE
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/context_test.cc
  extensions/common/node_info.proto
  extensions/stackdriver/metric/registry.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stats/config.proto
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/run_test.sh
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/server.yaml
  istio.deps
  src/envoy/http/metadata_exchange/config.cc
  src/envoy/http/metadata_exchange/config.h
  src/envoy/http/metadata_exchange/testdata/client.yaml
  src/envoy/http/metadata_exchange/testdata/server.yaml
  test/integration/mixer_fault_test.cc
Labels: cla: yes, size/XL

#2384 Update istio.api to release-1.3:tip
  istio.deps
  repositories.bzl
Labels: cla: yes, size/XS

#2386 Update Envoy SHA to latest with HTTP/2 upgrade fixes.
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2387 Build 1.1.14
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2388 Update envoy sha to pickup npe fix
  WORKSPACE
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/testdata/istio/metadata-exchange_filter.yaml
  extensions/stats/testdata/istio/stats_filter.yaml
  istio.deps
  src/envoy/http/metadata_exchange/config.cc
Labels: cla: yes, size/L

#2391 Update sha to pick up Null pointer fix
  WORKSPACE
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/testdata/istio/metadata-exchange_filter.yaml
  extensions/stats/testdata/istio/stats_filter.yaml
  istio.deps
  repositories.bzl
  src/envoy/http/metadata_exchange/config.cc
Labels: cla: yes, size/L

#2400 Update build image to prowbazel:0.5.10.
  .bazelrc
Labels: cla: yes, size/XS

#2402 Provide Bazel configs for RBE and Docker Sandbox. (#2397, #2400)
  .bazelrc
Labels: cla: yes, size/M

#2401 Add ability to fail_open (allow) when quota backend is unavailable
  src/istio/mixerclient/client_impl.cc
  src/istio/mixerclient/client_impl_test.cc
  src/istio/mixerclient/quota_cache.cc
  src/istio/mixerclient/quota_cache_test.cc
Labels: cherrypick/release-1.3, cla: yes, size/M

#2404 [release-1.3] Add ability to fail_open (allow) when quota backend is unavailable
  src/istio/mixerclient/client_impl.cc
  src/istio/mixerclient/client_impl_test.cc
  src/istio/mixerclient/quota_cache.cc
  src/istio/mixerclient/quota_cache_test.cc
Labels: cla: yes, size/M

#2405 Update destination service label
  extensions/stats/plugin.h
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/server.yaml
Labels: cherrypick/release-1.3, cla: yes, size/S

#2406 [release-1.3] Update destination service label
  extensions/stats/plugin.h
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/server.yaml
Labels: cla: yes, size/S

#2403 Use .bazelrc as part of CircleCI's cache key.
  .circleci/config.yml
Labels: cherrypick/release-1.3, cla: yes, size/S

#2407 [release-1.3] Use .bazelrc as part of CircleCI's cache key.
  .circleci/config.yml
Labels: cla: yes, size/S
