Repository istio/proxy, pull requests merged in 2019-07, with the labels that each got.

#2298 Fix jwt crash on invalid RSA public keys
  src/envoy/http/jwt_auth/auth_store.h
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt_test.cc
  src/envoy/http/jwt_auth/pubkey_cache.h
Labels: approved, cla: yes, lgtm, ok-to-test

#2306 Update Envoy-WASM SHA to latest.
  WORKSPACE
  istio.deps
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/http_filter_integration_test.cc
  src/envoy/http/authn/origin_authenticator_test.cc
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  test/integration/exchanged_token_integration_test.cc
  test/integration/istio_http_integration_test.cc
  test/integration/istio_http_integration_test_with_envoy_jwt_filter.cc
Labels: approved, cla: yes, lgtm

#2309 Fixing prow-presubmit test
  prow/proxy-presubmit.sh
Labels: approved, cla: yes, lgtm

#2310 changing proxy tests to run with updated pod utils set up in prow
  prow/proxy-postsubmit.sh
  prow/proxy-presubmit-asan.sh
  prow/proxy-presubmit-tsan.sh
Labels: approved, cla: yes, lgtm

#2297 Add scaffolding code for stackdriver wasm native plugin
  .bazelrc
  WORKSPACE
  extensions/stackdriver/BUILD
  extensions/stackdriver/opencensus/io_opencensus_cpp_null.patch
  extensions/stackdriver/opencensus/opencensus.bzl
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stackdriver/stackdriver_plugin_factory.cc
  src/envoy/BUILD
Labels: approved, cla: yes, lgtm

#2311 Pass istio.io/metadata between peers using HTTP headers
  src/envoy/BUILD
  src/envoy/http/metadata_exchange/BUILD
  src/envoy/http/metadata_exchange/config.cc
  src/envoy/http/metadata_exchange/config.h
  src/envoy/http/metadata_exchange/envoy.yaml
Labels: approved, cla: yes, lgtm

#2312 Update Envoy-WASM SHA to latest.
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm, size/S

#2315 Add NodeInfo and RequestInfo into Stackdriver plugin
  extensions/stackdriver/BUILD
  extensions/stackdriver/common/BUILD
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/context.cc
  extensions/stackdriver/common/context.h
  extensions/stackdriver/common/context_test.cc
  extensions/stackdriver/common/node_info.proto
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
Labels: approved, cla: yes, lgtm, size/XL

#2313 validate trust domain in authentication filter
  istio.deps
  repositories.bzl
  src/envoy/http/authn/authenticator_base.cc
  src/envoy/http/authn/authenticator_base.h
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/utils/BUILD
  src/envoy/utils/utils.cc
  src/envoy/utils/utils.h
  src/envoy/utils/utils_test.cc
Labels: approved, cla: yes, lgtm, size/L

#2316 Update metadata exchange filter
  .bazelrc
  src/envoy/http/metadata_exchange/config.cc
  src/envoy/http/metadata_exchange/config.h
  src/envoy/http/metadata_exchange/envoy.yaml
  tools/bazel.rc
Labels: approved, cla: yes, lgtm, size/L

#2282 Always use Bazel-0.22 for macOS on CircleCI (release-1.1).
  .circleci/config.yml
Labels: approved, cla: yes, lgtm

#2283 Always use Bazel-0.25 for macOS on CircleCI (release-1.2).
  .circleci/Dockerfile
  .circleci/Makefile
  .circleci/config.yml
Labels: cla: yes, lgtm

#2319 Fix mx filter broken in the last commit
  src/envoy/http/metadata_exchange/config.cc
  src/envoy/http/metadata_exchange/config.h
  src/envoy/http/metadata_exchange/testdata/client.yaml
  src/envoy/http/metadata_exchange/testdata/server.yaml
Labels: approved, cla: yes, lgtm, size/L

#2321 Update Envoy-WASM SHA to latest
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm, size/XS

#2305 Add support for RS384 and RS512 algorithms in JWT filter (#15380) (#2301)
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/jwt_auth/jwt_test.cc
Labels: approved, cla: human-approved, cla: yes, ok-to-test, size/L

#2323 Add bianpengyuan into owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2304 [1.2] Fix jwt crash on invalid RSA public keys
  src/envoy/http/jwt_auth/auth_store.h
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt_test.cc
  src/envoy/http/jwt_auth/pubkey_cache.h
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2324 fixing postsubmit test
  scripts/release-binary.sh
Labels: approved, cla: yes, lgtm, size/S

#2326 Copy data to /home/bootstrap
  scripts/release-binary.sh
Labels: approved, cla: yes, lgtm, size/S

#2327 update istio/envoy to pick up https://github.com/envoyproxy/envoy/com…
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, size/XS

#2329 Updating API sha for proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm, size/XS

#2330 Release 1.2.3
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm, size/XS

#2320 authn_wasm: Add skeleton authn filter in WASM.
  src/envoy/BUILD
  src/envoy/http/authn_wasm/BUILD
  src/envoy/http/authn_wasm/README.md
  src/envoy/http/authn_wasm/config.cc
  src/envoy/http/authn_wasm/config.h
  src/envoy/http/authn_wasm/envoy.yaml
Labels: cla: yes, lgtm, size/L

#2333 Revert envoy changes
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2332 Revert "update istio/envoy to pick up https://github.com/envoyproxy/envoy/com…"
  WORKSPACE
  istio.deps
Labels: approved, cla: yes, lgtm, size/XS
