Repository istio/proxy, pull requests merged in 2019-09, with the labels that each got.

#2409 Correct unit in duration metric name
  extensions/stats/plugin.cc
Labels: cherrypick/release-1.3, cla: yes, size/XS

#2410 [release-1.3] Correct unit in duration metric name
  extensions/stats/plugin.cc
Labels: cla: yes, size/XS

#2411 Update to 6577606a43d799e8d60be81258efa21d78eafe96 for h2c fix.
  WORKSPACE
Labels: cla: yes, size/XS

#2412 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS

#2413 Update istio.deps SHA
  istio.deps
Labels: cla: yes, size/XS

#2408 Use per filter config in route instead of route entry
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/filter.h
Labels: cherrypick/release-1.3, cla: yes, size/M

#2416 update istio/envoy sha
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2423 Istio 1.2.6 dependency fix
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2424 jwt: extract claim with whitespce as list
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/authn/authn_utils_test.cc
Labels: area/security, cla: yes, size/M

#2425 Update envoy SHA for https://github.com/istio/envoy/pull/105.
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2426 Update SHA for WASM Segv and jwt_verify_lib (#189) (#107) (#106)
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2417 [release-1.3] Use per filter config in route instead of route entry
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/filter.h
Labels: cla: yes, size/M

#2428 fix(stats filter): update stats filter config to new EnvoyFilter API
  extensions/stats/testdata/istio/stats_filter.yaml
Labels: cla: yes, size/M

#2418 Create .wasm files for metadata exchange and stats plugins.
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stats/Makefile
  extensions/stats/README.md
  extensions/stats/build_wasm.sh
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/plugin_test.cc
  src/envoy/http/metadata_exchange/BUILD
  src/envoy/http/metadata_exchange/Makefile
  src/envoy/http/metadata_exchange/README.md
  src/envoy/http/metadata_exchange/base64.h
  src/envoy/http/metadata_exchange/build_wasm.sh
  src/envoy/http/metadata_exchange/config.cc
  src/envoy/http/metadata_exchange/plugin.cc
  src/envoy/http/metadata_exchange/plugin.h
Labels: cherrypick/release-1.3, cla: yes, size/XL

#2430 [release-1.3] Create .wasm files for metadata exchange and stats plugins.
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stats/Makefile
  extensions/stats/README.md
  extensions/stats/build_wasm.sh
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/plugin_test.cc
  src/envoy/http/metadata_exchange/BUILD
  src/envoy/http/metadata_exchange/Makefile
  src/envoy/http/metadata_exchange/README.md
  src/envoy/http/metadata_exchange/base64.h
  src/envoy/http/metadata_exchange/build_wasm.sh
  src/envoy/http/metadata_exchange/config.cc
  src/envoy/http/metadata_exchange/plugin.cc
  src/envoy/http/metadata_exchange/plugin.h
Labels: cla: yes, size/XL

#2421 wasm: use filter state instead of metadata
  .bazelversion
  .circleci/config.yml
  WORKSPACE
  extensions/common/context.cc
  extensions/common/context.h
  extensions/metadata_exchange/BUILD
  extensions/metadata_exchange/Makefile
  extensions/metadata_exchange/README.md
  extensions/metadata_exchange/base64.h
  extensions/metadata_exchange/build_wasm.sh
  extensions/metadata_exchange/config.cc
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stackdriver/stackdriver_plugin_factory.cc
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/testdata/client.yaml
  src/envoy/BUILD
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/metadata_exchange/testdata/client.yaml
  src/envoy/http/metadata_exchange/testdata/server.yaml
  src/envoy/utils/utils.cc
  src/envoy/utils/utils_test.cc
  test/envoye2e/stackdriver_plugin/fake_stackdriver/timeseries.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
  test/integration/int_server.cc
  test/integration/int_server.h
Labels: cla: yes, size/XL

#2431 feat(stats): add istio_build metric to prom extension
  extensions/common/node_info.proto
  extensions/stats/plugin.cc
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/server.yaml
Labels: cla: yes, size/S
