Repository istio/proxy, pull requests merged in 2019-11, with the labels that each got.

#2496 Make envoy archive configurable from environment.
  .bazelrc
  WORKSPACE
  envoy_repository_rule.bzl
Labels: cla: yes, size/M

#2503 test: add TLS SD validation
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/metric/record.cc
  extensions/stats/plugin.h
  test/envoye2e/basic_flow/basic_xds_test.go
  test/envoye2e/driver/envoy.go
  test/envoye2e/driver/resource.go
  test/envoye2e/driver/scenario.go
  test/envoye2e/driver/stackdriver.go
  test/envoye2e/env/ports.go
  test/envoye2e/env/setup.go
  test/envoye2e/env/tcp_server.go
  test/envoye2e/stackdriver_plugin/fake_stackdriver/data.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  testdata/bootstrap/client.yaml.tmpl
  testdata/certs/cert-chain.pem
  testdata/certs/client-key.cert
  testdata/certs/client.cert
  testdata/certs/generate.sh
  testdata/certs/key.pem
  testdata/certs/root-cert.pem
  testdata/certs/root.cert
  testdata/certs/root.key
  testdata/certs/server-key.cert
  testdata/certs/server.cert
  testdata/stackdriver/client_request_count.yaml.tmpl
  testdata/stackdriver/server_access_log.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
  testdata/transport_socket/client.yaml.tmpl
  testdata/transport_socket/server.yaml.tmpl
Labels: cla: yes, size/XL

#2502 Use destination service name in stackdriver metric label
  extensions/common/context.cc
  extensions/stackdriver/metric/record.cc
  testdata/stackdriver/client_request_count.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
Labels: cla: yes, size/XS

#2504 Update Envoy-WASM SHA to latest based on Envoy v1.12.0.
  .bazelrc
  WORKSPACE
Labels: cla: yes, size/S

#2508 Update Envoy-WASM SHA to latest with wee8 v7.9.317.14.
  WORKSPACE
Labels: cla: yes, size/XS

#2505 Revert "Make envoy archive configurable from environment."
  .bazelrc
  WORKSPACE
  envoy_repository_rule.bzl
Labels: cla: yes, size/M

#2509 Use RBE in Prow jobs.
  .bazelrc
  Makefile.core.mk
  prow/proxy-common.inc
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/S

#2512 Release 1.4 codeowners
  CODEOWNERS
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_clean_repo.sh
  common/scripts/report_build_info.sh
  tools/deb/test/run_pilot_test.sh
Labels: cla: yes, size/M

#2513 metadata: skip sending metadata for explicit inbound/outbound
  extensions/common/context.cc
  extensions/common/context.h
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  extensions/stackdriver/stackdriver.cc
  extensions/stats/plugin.cc
Labels: cla: yes, size/M

#2514 Tolerate missing field in node metadata platform metadata
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/stackdriver.cc
Labels: cherrypick/release-1.4, cla: yes, size/M

#2477 Stats Plugin Test
  go.mod
  go.sum
  test/envoye2e/basic_flow/basic_flow_test.go
  test/envoye2e/basic_tcp_flow/basic_tcp_flow_test.go
  test/envoye2e/env/envoy_conf.go
  test/envoye2e/env/ports.go
  test/envoye2e/env/setup.go
  test/envoye2e/env/tcp_envoy_conf.go
  test/envoye2e/stats_plugin/doc.go
  test/envoye2e/stats_plugin/stats_plugin_test.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: cla: yes, size/L

#2516 [release-1.4] Tolerate missing field in node metadata platform metadata
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/stackdriver.cc
Labels: cla: yes, size/M

#2518 Disable RBE in postsubmit until docker-credential-gcloud is fixed.
  prow/proxy-common.inc
  prow/proxy-postsubmit.sh
Labels: cherrypick/release-1.4, cla: yes, size/XS

#2521 fix(edges): use service name (instead of host) in edge reporting
  extensions/stackdriver/edges/TODO
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
  go.mod
  go.sum
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
  test/envoye2e/stats_plugin/stats_plugin_test.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
  testdata/stackdriver/client_request_count.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
Labels: cherrypick/release-1.4, cla: yes, size/M

#2519 [release-1.4] Disable RBE in postsubmit until docker-credential-gcloud is fixed.
  prow/proxy-common.inc
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/XS

#2522 [release-1.4] fix(edges): use destination service name instead of hos…
  extensions/stackdriver/edges/TODO
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
  go.mod
  go.sum
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
  testdata/stackdriver/client_request_count.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
Labels: cla: yes, size/M

#2507 add stats XDS test
  test/envoye2e/driver/envoy.go
  test/envoye2e/driver/resource.go
  test/envoye2e/driver/stats.go
  test/envoye2e/env/http_client.go
  test/envoye2e/env/ports.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  test/envoye2e/stats/stats_xds_test.go
  testdata/bootstrap/client.yaml.tmpl
  testdata/bootstrap/server.yaml.tmpl
  testdata/bootstrap/stats.yaml.tmpl
  testdata/metric/client_request_total.yaml.tmpl
  testdata/metric/server_request_total.yaml.tmpl
Labels: cla: yes, size/XL

#2511 Save cache before running tests for macOS on CircleCI.
  .circleci/config.yml
Labels: cla: yes, size/XS

#2510 Stop building Debian packages and Docker images in tests.
  Makefile.core.mk
Labels: cla: yes, size/XS

#2526 Fix environment variable passing in makefile
  Makefile
Labels: cla: yes, size/S

#2525 Use istio/envoy instead of envoy-wasm
  WORKSPACE
Labels: cla: yes, size/S

#2529 [release-1.4] update istio/envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2531 add FALLTHRU; cycle VMs in stats test
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
  test/envoye2e/stats/stats_xds_test.go
Labels: cla: yes, size/XS

#2530 [release-1.4] metadata: skip sending metadata for explicit inbound/outbound
  extensions/common/context.cc
  extensions/common/context.h
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  extensions/stackdriver/stackdriver.cc
  extensions/stats/plugin.cc
Labels: cla: yes, size/M

#2532 Update envoy SHA for istio/envoy#118.
  WORKSPACE
  istio.deps
Labels: cla: yes, size/XS

#2488 Update common files.
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/check_clean_repo.sh
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/M

#2527 Fill response flag for stats plugin
  extensions/common/BUILD
  extensions/common/context.cc
  extensions/common/util.cc
  extensions/common/util.h
  extensions/common/util_test.cc
  extensions/stats/plugin.h
  testdata/stackdriver/server_access_log.yaml.tmpl
Labels: cherrypick/release-1.4, cla: yes, size/L

#2534 [release-1.4] Fill response flag for stats plugin
  extensions/common/BUILD
  extensions/common/context.cc
  extensions/common/util.cc
  extensions/common/util.h
  extensions/common/util_test.cc
  extensions/stats/plugin.h
  testdata/stackdriver/server_access_log.yaml.tmpl
Labels: cla: yes, size/L

#2528 Fix building extensions as WebAssembly modules (again).
  .gitignore
  Makefile.core.mk
  extensions/common/node_info_cache.cc
  extensions/metadata_exchange/build_wasm.sh
  extensions/metadata_exchange/plugin.h
  extensions/stats/Makefile
  extensions/stats/build_wasm.sh
  extensions/stats/plugin.wasm
Labels: cherrypick/release-1.4, cla: yes, size/S

#2537 [1.4] update envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2539 Update metadata exchange filter config
  extensions/stats/testdata/istio/metadata-exchange_filter.yaml
Labels: cherrypick/release-1.4, cla: yes, size/M

#2538 [release-1.4] Fix building extensions as WebAssembly modules (again).
  .gitignore
  Makefile.core.mk
  extensions/common/node_info_cache.cc
  extensions/metadata_exchange/build_wasm.sh
  extensions/metadata_exchange/plugin.h
  extensions/stats/Makefile
  extensions/stats/build_wasm.sh
  extensions/stats/plugin.wasm
Labels: cla: yes, size/S

#2541 Revert "Update metadata exchange filter config"
  extensions/stats/testdata/istio/metadata-exchange_filter.yaml
Labels: cla: yes, size/M

#2535 fix(edges): use unknown for missing metadata instance values
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
Labels: cherrypick/release-1.4, cla: yes, size/M

#2543 add stackdriver test data
  extensions/stackdriver/testdata/stackdriver_filter.yaml
Labels: cherrypick/release-1.4, cla: yes, size/M

#2542 [release-1.4] fix(edges): use unknown for missing metadata instance values
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
Labels: cla: yes, size/M

#2544 [release-1.4] add stackdriver test data
  extensions/stackdriver/testdata/stackdriver_filter.yaml
Labels: cla: yes, size/M

#2515 validate single proxy metadata exchange and stack driver
  test/envoye2e/basic_flow/basic_xds_test.go
  test/envoye2e/driver/stackdriver.go
  test/envoye2e/driver/xds.go
  test/envoye2e/env/ports.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  testdata/cluster/server.yaml.tmpl
  testdata/stackdriver/gateway_access_log.yaml.tmpl
Labels: cla: yes, size/L

#2546 v2: Add ability to control host header fallback
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stackdriver/testdata/stackdriver_filter.yaml
  extensions/stats/config.proto
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/testdata/istio/stats_filter.yaml
  test/envoye2e/env/http_server.go
  test/envoye2e/env/setup.go
  test/envoye2e/stats_plugin/stats_plugin_test.go
Labels: cla: yes, size/L

#2547 v2: Add ability to control host header fallback + needed cherry-picks
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stackdriver/testdata/stackdriver_filter.yaml
  extensions/stats/config.proto
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/testdata/istio/stats_filter.yaml
  go.mod
  go.sum
  test/envoye2e/basic_flow/basic_flow_test.go
  test/envoye2e/basic_tcp_flow/basic_tcp_flow_test.go
  test/envoye2e/env/envoy_conf.go
  test/envoye2e/env/http_server.go
  test/envoye2e/env/ports.go
  test/envoye2e/env/setup.go
  test/envoye2e/env/tcp_envoy_conf.go
  test/envoye2e/stats_plugin/doc.go
  test/envoye2e/stats_plugin/stats_plugin_test.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: cla: yes, size/L

#2545 Add readme file for sd plugin
  extensions/stackdriver/README.md
Labels: cherrypick/release-1.4, cla: yes, size/M

#2550 [release-1.4] Add readme file for sd plugin
  extensions/stackdriver/README.md
Labels: cla: yes, size/M

#2549 Update Envoy-WASM SHA to latest with HTTP inspector fixes.
  WORKSPACE
Labels: cla: yes, size/XS

#2552 Update Envoy-WASM SHA to latest with WasmState ALS fix
  WORKSPACE
Labels: cla: yes, size/XS

#2554 using request path when it is grpc request
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/metric/record.cc
Labels: cla: yes, size/S

#2551 update common file
  Makefile
  Makefile.overrides.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
Labels: cla: yes, size/S

#2435 Add trust domain and trust domain aliases to mTLS API
  src/istio/authn/context.proto
Labels: cla: yes, lifecycle/needs-triage, size/S

#2553 using request path when it is grpc request
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/metric/record.cc
Labels: cla: yes, size/S

#2506 sync bazelrc and doc how to override
  .bazelrc
  .gitignore
  WORKSPACE
  envoy.bazelrc
Labels: cla: yes, size/L

#2523 fix(edges): add debug log for generated requests
  extensions/stackdriver/edges/mesh_edges_service_client.cc
Labels: cla: yes, size/XS

#2555 Enable envoy repo override w/ ENVOY_REPOSITORY, ENVOY_SHA, ENVOY_PREFIX
  prow/proxy-common.inc
Labels: cla: yes, size/XS

#2556 Allow ENVOY_SHA to be the same as one defined in WORKSPACE
  prow/proxy-common.inc
Labels: cla: yes, size/XS

#2557 Minor fix in metadataexchange filter
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
Labels: cla: yes, size/XS

#2562 [release-1.4] Enable envoy repo override w/ ENVOY_REPOSITORY, ENVOY_SHA, ENVOY_PREFIX
  prow/proxy-common.inc
Labels: cla: yes, size/XS

#2563 [release-1.4] Allow ENVOY_SHA to be the same as one defined in WORKSPACE
  prow/proxy-common.inc
Labels: cla: yes, size/XS

#2558 istio_authn: bypass CORS preflight request
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/http_filter_integration_test.cc
  src/envoy/http/authn/origin_authenticator.cc
  src/envoy/http/authn/origin_authenticator_test.cc
Labels: cherrypick/release-1.4, cla: yes, size/M

#2564 [release-1.4] istio_authn: bypass CORS preflight request
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/http_filter_integration_test.cc
  src/envoy/http/authn/origin_authenticator.cc
  src/envoy/http/authn/origin_authenticator_test.cc
Labels: cla: yes, size/M

#2565 Use struct value in setfilterstate in metadata exchange filter
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
Labels: cla: yes, size/XS

#2568 Add golang lint
  Makefile.core.mk
  go.sum
  src/envoy/http/jwt_auth/sample/fake_issuer.go
  test/backend/echo/echo.go
  test/envoye2e/basic_tcp_flow/basic_tcp_flow_test.go
  test/envoye2e/driver/envoy.go
  test/envoye2e/driver/stackdriver.go
  test/envoye2e/env/ports.go
  test/envoye2e/env/setup.go
  test/envoye2e/env/tcp_envoy_conf.go
  test/envoye2e/env/tcp_server.go
  test/envoye2e/stackdriver_plugin/fake_stackdriver/fake_stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
  test/envoye2e/stats/stats_xds_test.go
  test/envoye2e/stats_plugin/stats_plugin_test.go
  test/envoye2e/tcp_metadata_exchange/doc.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: cla: yes, size/L

#2559 Update envoy-wasm sha
  .bazelrc
  WORKSPACE
  extensions/common/context.cc
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  extensions/stackdriver/.stackdriver.cc.swp
  extensions/stackdriver/edges/mesh_edges_service_client.cc
  extensions/stackdriver/edges/mesh_edges_service_client.h
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/log/exporter.h
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stackdriver/testdata/stackdriver_filter.yaml
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/istio/metadata-exchange_filter.yaml
  extensions/stats/testdata/istio/stats_filter.yaml
  extensions/stats/testdata/server.yaml
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  test/envoye2e/stats/stats_xds_test.go
  test/envoye2e/stats_plugin/stats_plugin_test.go
Labels: cla: yes, size/L

#2570 misc: fixes gitignore and style check
  .clang-format
  .gitignore
  extensions/stackdriver/.stackdriver.cc.swp
  scripts/check-style.sh
Labels: cla: yes, size/XS

#2571 ci: enable RBE in postfix again
  prow/proxy-postsubmit.sh
  scripts/release-binary.sh
  tools/docker/BUILD
Labels: cla: yes, size/S

#2574 ci: fix RBE
  .bazelrc
Labels: cla: yes, size/XS

#2572 Update stackdriver config with edges
  extensions/stackdriver/testdata/stackdriver_filter.yaml
Labels: cla: yes, size/XS

#2579 Update envoy wasm sha
  WORKSPACE
  extensions/stackdriver/stackdriver.cc
Labels: cla: yes, size/XS

#2578 fix bazel calls when using local envoy and --override_repository
  Makefile.core.mk
  prow/proxy-common.inc
  scripts/push-debian.sh
  scripts/release-binary.sh
Labels: cherrypick/release-1.4, cla: yes, size/M

#2581 Update Envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2580 [release-1.4] fix bazel calls when using local envoy and --override_repository
  Makefile.core.mk
  prow/proxy-common.inc
  scripts/push-debian.sh
  scripts/release-binary.sh
Labels: cla: yes, needs-rebase, size/M

#2576 Add option to skip pushing docker image in release-binary
  scripts/release-binary.sh
Labels: cherrypick/release-1.4, cla: yes, size/S

#2586 [release-1.4] Add option to skip pushing docker image in release-binary
  scripts/release-binary.sh
Labels: cla: yes, size/S

#2587 Update release binary script
  Makefile.core.mk
  scripts/release-binary.sh
Labels: cherrypick/release-1.4, cla: yes, size/S
