Repository istio/proxy, pull requests merged in 2019-04, with the labels that each got.

#2158 update envoy to latest
  WORKSPACE
  istio.deps
  protobuf.bzl
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/mixer/control.cc
  src/envoy/tcp/mixer/control.cc
  src/envoy/utils/utils.cc
  src/istio/mixerclient/BUILD
  src/istio/mixerclient/status_util.cc
  test/integration/int_client.cc
  test/integration/int_server.cc
  test/integration/int_server.h
Labels: approved, cla: yes, lgtm

#2166 release 1.1: Update envoy to enable path normalization
  .bazelrc
  WORKSPACE
  istio.deps
Labels: approved, cla: yes

#2168 envoy: proxy release 1.0 should use the istio/envoy with cve fix
  WORKSPACE
  istio.deps
Labels: cla: yes

#2170 Sync istio/api for 1.1.3
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm

#2178 [BOT PR] to update dependencies of proxy
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, dependency-update, lgtm, release-note-none

#2179 Update envoy sha and fix bulid break
  WORKSPACE
  istio.deps
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/authn/authn_utils.h
  src/envoy/http/authn/authn_utils_test.cc
  src/envoy/http/authn/http_filter_integration_test.cc
  src/envoy/http/authn/http_filter_test.cc
  src/envoy/http/authn/origin_authenticator.cc
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/token_extractor.cc
  src/envoy/http/mixer/check_data.cc
  src/envoy/http/mixer/report_data.h
  src/envoy/utils/utils.cc
  test/integration/exchanged_token_integration_test.cc
  test/integration/int_client.cc
  test/integration/int_server.cc
  test/integration/istio_http_integration_test.cc
Labels: approved, cla: yes, lgtm

#2181 Updating API sha for proxy.
  istio.deps
  repositories.bzl
Labels: approved, cla: yes, lgtm
