Repository istio/proxy, pull requests merged in 2020-11, with the labels that each got.

#3070 Update envoy dep
  .bazelrc
  .bazelversion
  Makefile.core.mk
  WORKSPACE
  envoy.bazelrc
  scripts/check-style.sh
  scripts/release-binary.sh
Labels: cla: yes, size/M

#3081 Automator: update envoy@release-1.8 in istio/proxy@release-1.8
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3078 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3080 Automator: update common-files@release-1.8 in istio/proxy@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3085 Update envoy to 11/03
  WORKSPACE
Labels: cla: yes, size/XS

#3082 [Release-1.7] Fix useragent in stackdriver access log (#3076)
  extensions/common/context.cc
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry_sampled.yaml.tmpl
Labels: cla: yes, size/S

#3083 [Release-1.6] Fix useragent in stackdriver access log (#3076)
  extensions/common/context.cc
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
Labels: cla: yes, size/XS

#3087 Allow master in envoy download
  test/envoye2e/driver/envoy.go
Labels: cla: yes, size/XS

#3086 Automator: update envoy@release-1.8 in istio/proxy@release-1.8
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3088 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3089 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3090 Automator: update envoy@release-1.8 in istio/proxy@release-1.8
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3092 Fix export cache
  Makefile.core.mk
Labels: cla: yes, size/XS

#3093 Clean up build files
  repositories.bzl
  tsan.suppressions
  x_tools_imports.bzl
Labels: cla: yes, size/M

#3094 Clean up gogo proto from repository imports
  repositories.bzl
Labels: cla: yes, size/M

#3095 Bump proxy
  WORKSPACE
Labels: cla: yes, size/XS

#3091 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3096 Automator: update envoy@release-1.8 in istio/proxy@release-1.8
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3098 Automator: update common-files@release-1.7 in istio/proxy@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3099 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3097 Automator: update common-files@release-1.8 in istio/proxy@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3100 Add Rbac Access Denied Policy Info in Access logs
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  go.mod
  scripts/check-style.sh
  test/envoye2e/inventory.go
  test/envoye2e/stackdriver_plugin/stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/filters/rbac.yaml.tmpl
  testdata/stackdriver/client_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
Labels: cla: yes, size/L

#3104 [release-1.6] Update common files
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#3103 Automator: update common-files@release-1.8 in istio/proxy@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3105 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3101 Update Envoy SHA to latest with Proxy-Wasm backports.
  WORKSPACE
  envoy.bazelrc
  extensions/BUILD
Labels: cla: yes, size/S

#3107 Wrap Wasm related library import into a rule
  WORKSPACE
  bazel/BUILD
  bazel/repositories.bzl
  bazel/wasm.bzl
Labels: cla: yes, size/M

#3109 [release-1.8] Clean up build files
  repositories.bzl
  tsan.suppressions
  x_tools_imports.bzl
Labels: cla: yes, release-notes-none, size/M

#3108 [release-1.8] Wrap Wasm related library import into a rule
  WORKSPACE
  bazel/BUILD
  bazel/repositories.bzl
  bazel/wasm.bzl
Labels: cla: yes, release-notes-none, size/M

#3111 Update envoy sha
  WORKSPACE
  envoy.bazelrc
  extensions/access_log_policy/BUILD
  extensions/attributegen/BUILD
  extensions/attributegen/plugin_test.cc
  extensions/common/BUILD
  extensions/metadata_exchange/BUILD
  extensions/stackdriver/BUILD
  extensions/stackdriver/common/BUILD
  extensions/stackdriver/edges/BUILD
  extensions/stackdriver/log/BUILD
  extensions/stats/BUILD
Labels: cla: yes, size/M

#3112 Automator: update common-files@release-1.8 in istio/proxy@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3113 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3114 Automator: update common-files@release-1.7 in istio/proxy@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
