Repository istio/proxy, pull requests merged in 2020-10, with the labels that each got.

#3030 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.yamllint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3023 Update sha to include https://github.com/istio/envoy/pull/263
  WORKSPACE
Labels: cla: yes, size/XS

#3033 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3034 Bump Envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#3036 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes, size/XS

#3029 [1.7] Update sha for CVE-2020-25017 (#32)
  test/envoye2e/driver/envoy.go
  test/envoye2e/env/utils.go
  test/envoye2e/stats_plugin/README.md
  test/envoye2e/stats_plugin/stats_test.go
Labels: cla: yes, size/M

#3038 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3037 Update proxy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#3039 Remove basic auth filter from proxy repo
  Makefile.core.mk
  extensions/BUILD
  extensions/basic_auth/BUILD
  extensions/basic_auth/config.cc
  extensions/basic_auth/config.pb.html
  extensions/basic_auth/config.proto
  extensions/basic_auth/plugin.cc
  extensions/basic_auth/plugin.h
  scripts/release-binary.sh
  src/envoy/BUILD
  test/envoye2e/basic_auth/basic_auth_test.go
  test/envoye2e/inventory.go
  testdata/filters/basicauth.yaml.tmpl
  testdata/filters/basicauth_configuration_data.json
Labels: cla: yes, size/XL

#3032 update envoy-wasm
  WORKSPACE
  extensions/attributegen/config.pb.html
  extensions/common/BUILD
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/proto_util.cc
  extensions/common/proto_util.h
  extensions/common/proto_util_speed_test.cc
  extensions/common/proto_util_test.cc
  extensions/metadata_exchange/plugin.cc
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.pb.html
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stats/config.pb.html
  extensions/stats/config.proto
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  src/envoy/extensions/wasm/BUILD
  src/envoy/extensions/wasm/wasm.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
  src/envoy/tcp/tcp_cluster_rewrite/BUILD
  testdata/testdata.gen.go
Labels: cla: yes, size/XL

#3031 Add Client Side Sampling Support
  extensions/access_log_policy/plugin.cc
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/stackdriver/client_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_access_log_entry_sampled.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry_sampled.yaml.tmpl
Labels: cla: yes, size/M

#3041 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  testdata/testdata.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/L

#3000 Minor additions to Access Logs
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  testdata/stackdriver/client_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_tcp_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_tcp_access_log_entry_on_open.yaml.tmpl
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry_on_open.yaml.tmpl
Labels: cla: yes, size/L

#3043 update envoy-wasm (upstream Envoy v1.16)
  WORKSPACE
  envoy.bazelrc
  extensions/attributegen/plugin_test.cc
Labels: cla: yes, size/M

#3045 jwt: support nested claims
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/authn/authn_utils_test.cc
Labels: cla: yes, size/L

#3049 cleanup: fix TODOs waiting for c++17
  extensions/common/context.h
  extensions/stats/plugin.cc
Labels: cla: yes, size/M

#3050 Remove mac test
  .circleci/config.yml
  .drone.yml
  .travis.yml
Labels: cla: yes, size/L

#3042 test: validate route_name
  testdata/bootstrap/stats.yaml.tmpl
  testdata/listener/client.yaml.tmpl
  testdata/listener/server.yaml.tmpl
  testdata/metric/client_request_total_customized.yaml.tmpl
  testdata/stackdriver/client_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
  testdata/stats/client_config_customized.yaml.tmpl
Labels: cla: yes, size/S

#3052 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3053 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3048 grpc: add streaming metrics
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  go.mod
  go.sum
  test/envoye2e/driver/grpc.go
  test/envoye2e/env/grpc.go
  test/envoye2e/env/grpc_echo/grpc_echo.pb.go
  test/envoye2e/env/grpc_echo/grpc_echo.proto
  test/envoye2e/env/grpc_echo/grpc_echo_grpc.pb.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/filters/grpc_stats.yaml
  testdata/metric/client_request_messages.yaml.tmpl
  testdata/metric/client_response_messages.yaml.tmpl
  testdata/metric/server_request_messages.yaml.tmpl
  testdata/metric/server_response_messages.yaml.tmpl
  testdata/stats/client_config.yaml
  testdata/stats/client_config_customized.yaml.tmpl
  testdata/stats/client_config_disable_header_fallback.yaml
  testdata/stats/request_classification_config.yaml
  testdata/stats/server_config.yaml
Labels: cla: yes, size/L

#3051 Parse workload and service from resource labels
  WORKSPACE
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stats/plugin.cc
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/bootstrap/client.yaml.tmpl
  testdata/bootstrap/server.yaml.tmpl
  testdata/cluster/server.yaml.tmpl
  testdata/cluster/tcp_client.yaml.tmpl
  testdata/cluster/tcp_server.yaml.tmpl
  testdata/listener/client.yaml.tmpl
  testdata/listener/server.yaml.tmpl
  testdata/metric/client_request_total_endpoint_labels.yaml.tmpl
  testdata/stackdriver/client_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_tcp_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_tcp_access_log_entry_on_open.yaml.tmpl
  testdata/stackdriver/client_tcp_connection_count.yaml.tmpl
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
  testdata/testdata.gen.go
Labels: cla: yes, size/L

#3046 Automator: update common-files@release-1.7 in istio/proxy@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3055 use istio envoy release-1.8 instead of envoy-wasm
  .bazelrc
Labels: cla: yes, ok-to-test, size/XS

#3056 fix: implement metadata fallback on the special value
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/stackdriver.cc
  extensions/stats/config.proto
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
Labels: cla: yes, size/M

#3057 update istio/envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#3059 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  testdata/testdata.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/S

#3047 Add customized access logging support for stackdriver access logs
  extensions/stackdriver/BUILD
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.pb.html
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger.h
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/filters/stackdriver_outbound.yaml.tmpl
  testdata/stackdriver/client_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_config_customized.yaml.tmpl
Labels: cla: yes, size/L

#3060 Make TCP workload metadata writable
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
Labels: cherrypick/release-1.8, cla: yes, size/XS

#3062 [release-1.8] Make TCP workload metadata writable
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
Labels: cla: yes, release-notes-none, size/XS

#3061 [release-1.8] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#3063 [release-1.8] Add customized access logging support for stackdriver access logs
  extensions/stackdriver/BUILD
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.pb.html
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger.h
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/filters/stackdriver_outbound.yaml.tmpl
  testdata/stackdriver/client_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_config_customized.yaml.tmpl
Labels: cla: yes, release-notes-none, size/L

#3064 Automator: update common-files@release-1.8 in istio/proxy@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3058 generalize interval reporting to HTTP
  extensions/common/context.cc
  extensions/common/context.h
  extensions/metadata_exchange/plugin.h
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/metric/record.cc
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  test/envoye2e/driver/grpc.go
  test/envoye2e/driver/scenario.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/metric/client_request_messages.yaml.tmpl
  testdata/metric/client_response_messages.yaml.tmpl
  testdata/stats/client_config.yaml
  testdata/stats/client_config_customized.yaml.tmpl
  testdata/stats/client_config_disable_header_fallback.yaml
  testdata/stats/client_config_grpc.yaml.tmpl
  testdata/stats/request_classification_config.yaml
  testdata/stats/server_config.yaml
  testdata/stats/server_config_grpc.yaml.tmpl
Labels: cherrypick/release-1.8, cla: yes, size/XL

#3065 [release-1.8] generalize interval reporting to HTTP
  extensions/common/context.cc
  extensions/common/context.h
  extensions/metadata_exchange/plugin.h
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/metric/record.cc
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  test/envoye2e/driver/grpc.go
  test/envoye2e/driver/scenario.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/metric/client_request_messages.yaml.tmpl
  testdata/metric/client_response_messages.yaml.tmpl
  testdata/stats/client_config.yaml
  testdata/stats/client_config_customized.yaml.tmpl
  testdata/stats/client_config_disable_header_fallback.yaml
  testdata/stats/client_config_grpc.yaml.tmpl
  testdata/stats/request_classification_config.yaml
  testdata/stats/server_config.yaml
  testdata/stats/server_config_grpc.yaml.tmpl
Labels: cla: yes, release-notes-none, size/XL

#3066 Clean up exchange keys
  extensions/attributegen/testdata/server.yaml
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/server.yaml
  src/envoy/tcp/metadata_exchange/metadata_exchange_test.cc
  testdata/client_node_metadata.json.tmpl
  testdata/gce_client_node_metadata.json.tmpl
  testdata/gce_server_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
  tools/extensionserver/envoy.yaml
Labels: cla: yes, size/XS

#3067 build: use gperftoos tcmalloc
  .bazelrc
Labels: cherrypick/release-1.8, cla: yes, size/XS

#3068 [release-1.8] build: use gperftoos tcmalloc
  .bazelrc
Labels: cla: yes, release-notes-none, size/XS

#3069 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3054 test: set timeout
  Makefile.core.mk
Labels: cla: yes, size/XS

#3072 update envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#3074 Update update_envoy as it had a second value for sha256
  scripts/update_envoy.sh
Labels: cla: yes, size/XS

#3075 [release-1.8] Manually update envoy in WORKSPACE
  WORKSPACE
Labels: cla: yes, size/XS

#3076 Fix useragent in stackdriver access log
  extensions/common/context.cc
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/stackdriver/client_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_audit_log_entry.yaml.tmpl
Labels: cherrypick/release-1.6, cherrypick/release-1.7, cherrypick/release-1.8, cla: yes, size/S

#3077 [release-1.8] Fix useragent in stackdriver access log
  extensions/common/context.cc
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/stackdriver/client_access_log_entry.yaml.tmpl
  testdata/stackdriver/client_gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_audit_log_entry.yaml.tmpl
Labels: cla: yes, release-notes-none, size/S
