Repository istio/proxy, pull requests merged in 2020-05, with the labels that each got.

#2837 Make magic mismatch condition a warning and actionable
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
Labels: cla: yes, size/XS

#2838 [release-1.6] Make magic mismatch condition a warning and actionable
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
Labels: cla: yes, size/XS

#2836 Change log level in metadata exchange filter
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
Labels: cla: yes, size/XS

#2820 [test cleanup] Move all configuration out of go source file
  extensions/stackdriver/common/utils.cc
  test/backend/echo/README.md
  test/backend/echo/echo.go
  test/envoye2e/basic_flow/basic_test.go
  test/envoye2e/driver/stackdriver.go
  test/envoye2e/http_metadata_exchange/exchange_test.go
  test/envoye2e/http_metadata_exchange/http_metadata_exchange_test.go
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  test/envoye2e/stats_plugin/stats_test.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  testdata/cluster/server.yaml.tmpl
  testdata/filters/access_log_policy.yaml.tmpl
  testdata/filters/client_mx_network_filter.yaml.tmpl
  testdata/filters/client_stats_network_filter.yaml.tmpl
  testdata/filters/server_mx_network_filter.yaml.tmpl
  testdata/filters/server_stats_network_filter.yaml.tmpl
  testdata/filters/stackdriver_inbound.yaml.tmpl
  testdata/filters/stackdriver_outbound.yaml.tmpl
  testdata/filters/stats_inbound.yaml.tmpl
  testdata/filters/stats_outbound.yaml.tmpl
  testdata/listener/client.yaml.tmpl
  testdata/listener/server.yaml.tmpl
  testdata/transport_socket/client.yaml.tmpl
  testdata/transport_socket/server.yaml.tmpl
Labels: cla: yes, size/XXL

#2839 Update istio envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2842 [release-1.6] Update envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2841 fix server yaml and failure log
  extensions/attributegen/testdata/server.yaml
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  testdata/metric/client_request_total_customized.yaml.tmpl
Labels: cla: yes, size/M

#2844 clarify that . is not to be used in attributes
  extensions/attributegen/config.pb.html
  extensions/attributegen/config.proto
Labels: cherrypick/release-1.6, cla: yes, size/S

#2845 [release-1.6] fix server yaml and failure log
  extensions/attributegen/testdata/server.yaml
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  testdata/metric/client_request_total_customized.yaml.tmpl
Labels: cla: yes, size/M

#2846 [release-1.6] clarify that . is not to be used in attributes
  extensions/attributegen/config.pb.html
  extensions/attributegen/config.proto
Labels: cla: yes, size/S

#2847 [release-1.6] Update istio envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2848 Update envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2850 Update istio/envoy to add envoy PR 214
  WORKSPACE
Labels: cla: yes, size/XS

#2851 Automator: update common-files@release-1.5 in istio/proxy@release-1.5
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#2849 Update envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2854 fix(stackdriver): improve uids for GCE VMs
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/edges/edge_reporter.cc
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/gce_client_node_metadata.json.tmpl
  testdata/stackdriver/gce_client_request_count.yaml.tmpl
  testdata/stackdriver/gce_server_request_count.yaml.tmpl
  testdata/stackdriver/gce_traffic_assertion.yaml.tmpl
Labels: cla: yes, size/L

#2857 ensure that telemetry plugins do not return config errors
  extensions/access_log_policy/plugin.cc
  extensions/access_log_policy/plugin.h
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
Labels: cla: yes, size/M

#2858 MX should continue with sane defaults
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
Labels: cla: yes, size/M

#2853 Clean up test framework
  go.mod
  go.sum
  test/envoye2e/env/envoy.go
  test/envoye2e/env/envoy_conf.go
  test/envoye2e/env/http_server.go
  test/envoye2e/env/ports.go
  test/envoye2e/env/setup.go
  test/envoye2e/env/tcp_envoy_conf.go
  test/envoye2e/env/tcp_server.go
  test/envoye2e/env/utils.go
  test/envoye2e/stackdriver_plugin/cmd/main.go
  test/envoye2e/stackdriver_plugin/fake_stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  test/envoye2e/stackdriver_plugin/sts.go
  testdata/client_node_metadata.json.tmpl
  testdata/gce_client_node_metadata.json.tmpl
  testdata/gce_server_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
Labels: cla: yes, size/XXL

#2859 [1.6.1] ensure that telemetry plugins do not return config errors
  extensions/access_log_policy/plugin.cc
  extensions/access_log_policy/plugin.h
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
Labels: cla: yes, size/L

#2855 [1.6.1] Update envoy sha to pickup 2 crash fixes
  WORKSPACE
Labels: cla: yes, flag/needs-release-note, size/XS

#2856 [1.6.1] fix(stackdriver): improve uids for GCE VMs
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/edges/edge_reporter.cc
  test/envoye2e/driver/stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  testdata/gce_client_node_metadata.json.tmpl
  testdata/stackdriver/gce_client_request_count.yaml.tmpl
  testdata/stackdriver/gce_server_request_count.yaml.tmpl
  testdata/stackdriver/gce_traffic_assertion.yaml.tmpl
Labels: cla: yes, size/L

#2861 bazel_get_workspace_status: Allow users to override variables
  tools/bazel_get_workspace_status
Labels: cherrypick/release-1.6, cla: yes, size/S

#2863 [release-1.6] bazel_get_workspace_status: Allow users to override variables
  tools/bazel_get_workspace_status
Labels: cla: yes, size/S

#2864 Fix release binary script to use the correct bucket env var
  scripts/release-binary.sh
Labels: cla: yes, size/XS
