Repository istio/proxy, pull requests merged in 2020-07, with the labels that each got.

#2887 Update envoy-wasm sha
  .bazelversion
  Makefile
  Makefile.overrides.mk
  WORKSPACE
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/license-lint.yml
  common/scripts/copyright-banner-go.txt
  common/scripts/fix_copyright_banner.sh
  common/scripts/run.sh
  common/scripts/setup_env.sh
  envoy.bazelrc
  extensions/access_log_policy/plugin.cc
  extensions/attributegen/plugin.h
  extensions/attributegen/plugin_test.cc
  extensions/common/context.cc
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  go.mod
  go.sum
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/http_filter_integration_test.cc
  src/envoy/http/authn/origin_authenticator.cc
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/mixer/filter.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange.h
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite_test.cc
  test/envoye2e/stackdriver_plugin/fake_stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver.go
  test/integration/exchanged_token_integration_test.cc
  test/integration/istio_http_integration_test.cc
  test/integration/istio_http_integration_test_with_envoy_jwt_filter.cc
Labels: cla: yes, size/XXL

#2891 [release-1.6] Merge release-1.6.4 patch & update envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2871 jwt_authn: replace json processing strategy
  .circleci/config.yml
  extensions/common/json_util.cc
  extensions/common/json_util.h
  extensions/metadata_exchange/plugin.cc
  extensions/stats/plugin.cc
  src/envoy/http/jwt_auth/BUILD
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt.h
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/jwt_auth/jwt_test.cc
Labels: cla: yes, size/L

#2892 [release-1.5] Update envoy sha rel15
  WORKSPACE
  scripts/generate-wasm.sh
Labels: cla: yes, size/M

#2886 authn: config processor to use wasm json utils
  extensions/common/json_util.cc
  extensions/common/json_util.h
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/authn/authn_utils.h
  src/envoy/utils/BUILD
  src/envoy/utils/config.cc
  src/envoy/utils/config.h
Labels: cla: yes, size/L

#2897 [release-1.5] Fix generate_wasm.sh script
  WORKSPACE
  scripts/generate-wasm.sh
Labels: cla: yes, size/M

#2899 Update Envoy to pull in https://github.com/envoyproxy/envoy/pull/11921
  WORKSPACE
Labels: cla: yes, size/XS

#2900 Update Envoy to pull in https://github.com/envoyproxy/envoy/pull/11921
  WORKSPACE
Labels: cla: yes, size/XS

#2895 fix all shellcheck for files in scripts and extension directory
  Makefile.core.mk
  extensions/stats/run_test.sh
  prow/proxy-common.inc
  prow/proxy-postsubmit.sh
  prow/proxy-presubmit-asan.sh
  prow/proxy-presubmit-release.sh
  prow/proxy-presubmit-tsan.sh
  prow/proxy-presubmit-wasm.sh
  prow/proxy-presubmit.sh
  scripts/check-style.sh
  scripts/push-debian.sh
  scripts/release-binary.sh
  tools/deb/postinst.sh
  tools/deb/test/machine_setup.sh
  tools/deb/test/run_gce_test.sh
  tools/deb/test/run_pilot_test.sh
Labels: cla: yes, ok-to-test, size/L

#2905 forward port of https://github.com/istio/proxy/pull/2879
  test/envoye2e/stats_plugin/stats_test.go
Labels: cla: yes, size/L

#2903 feat(testing): Update Stackdriver fake to support traces and edges retrieval.
  test/envoye2e/stackdriver_plugin/cmd/Makefile
  test/envoye2e/stackdriver_plugin/fake_stackdriver.go
Labels: cla: yes, size/M

#2902 Fix container name as app_container in telemetry v2
  extensions/common/proto_util.cc
  extensions/common/proto_util_test.cc
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
Labels: cherrypick/release-1.5, cherrypick/release-1.6, cla: yes, size/S

#2906 Add two missing stackdriver integration test to test inventory
  test/envoye2e/inventory.go
Labels: cla: yes, size/XS

#2909 fix build for clang 10
  extensions/common/istio_dimensions_test.cc
  src/envoy/http/mixer/filter.cc
Labels: cla: yes, size/M

#2904 Remove Istio JWT filter
  repositories.bzl
  src/envoy/BUILD
  src/envoy/http/authn/BUILD
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/authn_utils.cc
  src/envoy/http/jwt_auth/BUILD
  src/envoy/http/jwt_auth/ImplementationNotes.md
  src/envoy/http/jwt_auth/README.md
  src/envoy/http/jwt_auth/auth_store.h
  src/envoy/http/jwt_auth/http_filter.cc
  src/envoy/http/jwt_auth/http_filter.h
  src/envoy/http/jwt_auth/http_filter_factory.cc
  src/envoy/http/jwt_auth/integration_test/envoy.conf
  src/envoy/http/jwt_auth/integration_test/envoy.conf.jwk
  src/envoy/http/jwt_auth/integration_test/envoy_allow_missing_or_failed_jwt.conf.jwk
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
  src/envoy/http/jwt_auth/jwt.cc
  src/envoy/http/jwt_auth/jwt.h
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator.h
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/jwt_auth/jwt_test.cc
  src/envoy/http/jwt_auth/pubkey_cache.h
  src/envoy/http/jwt_auth/sample/correct_jwt
  src/envoy/http/jwt_auth/sample/envoy.conf
  src/envoy/http/jwt_auth/sample/fake_issuer.go
  src/envoy/http/jwt_auth/sample/invalid_jwt
  src/envoy/http/jwt_auth/sample/pubkey.jwk
  src/envoy/http/jwt_auth/token_extractor.cc
  src/envoy/http/jwt_auth/token_extractor.h
  src/envoy/http/jwt_auth/token_extractor_test.cc
  src/envoy/http/jwt_auth/tools/jwk_generator.py
  src/envoy/http/jwt_auth/tools/jwt_generator.py
  src/envoy/http/mixer/BUILD
  src/envoy/http/mixer/check_data.cc
  src/envoy/utils/filter_names.cc
  test/integration/BUILD
  test/integration/exchanged_token_integration_test.cc
  test/integration/istio_http_integration_test.cc
Labels: cla: yes, size/XXL

#2907 [release-1.6] Fix container name as app_container in telemetry v2
  extensions/common/proto_util.cc
  extensions/common/proto_util_test.cc
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
Labels: cla: yes, size/S

#2908 Rename kForwardWhitelist variable to kForwardAllowlist
  src/istio/control/http/attributes_builder.cc
Labels: cla: yes, size/XS

#2911 Update envoy sha
  WORKSPACE
  src/envoy/http/authn/origin_authenticator.cc
Labels: cla: yes, size/S

#2914 Pre-compile the .wasm files for V8.
  Makefile.core.mk
  scripts/release-binary.sh
  test/envoye2e/stats_plugin/stats_test.go
  testdata/filters/stats_inbound.yaml.tmpl
  testdata/filters/stats_outbound.yaml.tmpl
  testdata/listener/client.yaml.tmpl
  testdata/listener/server.yaml.tmpl
Labels: cla: yes, size/S

#2896 Integration Test for AttributeGen WASM Filter
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/README.md
  test/envoye2e/stats_plugin/stats_test.go
  testdata/filters/attributegen.yaml.tmpl
  testdata/filters/stats_outbound.yaml.tmpl
  testdata/metric/server_request_total.yaml.tmpl
  testdata/stats/request_classification_config.yaml
Labels: cla: yes, ok-to-test, size/L

#2913 abseil: destroy wasm un-compatible repository
  WORKSPACE
  bazel/patches/absl.patch
  extensions/BUILD
  extensions/common/BUILD
  extensions/metadata_exchange/BUILD
  extensions/metadata_exchange/plugin.cc
Labels: cla: yes, size/M

#2910 Fill in unknown for stackdriver metric empty labels
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/metric/record.cc
  testdata/stackdriver/client_request_count.yaml.tmpl
  testdata/stackdriver/client_tcp_connection_count.yaml.tmpl
  testdata/stackdriver/gce_client_request_count.yaml.tmpl
  testdata/stackdriver/gce_server_request_count.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
  testdata/stackdriver/server_tcp_connection_count.yaml.tmpl
Labels: cla: yes, size/L

#2916 Add hooks for custom Istio Wasm extensions.
  WORKSPACE
  src/envoy/BUILD
  src/envoy/extensions/wasm/BUILD
  src/envoy/extensions/wasm/context.h
  src/envoy/extensions/wasm/wasm.cc
Labels: cla: yes, size/L

#2920 [release-1.6] Fill in unknown for stackdriver metric empty labels (#2910)
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/metric/record.cc
  testdata/stackdriver/client_request_count.yaml.tmpl
  testdata/stackdriver/gce_client_request_count.yaml.tmpl
  testdata/stackdriver/gce_server_request_count.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
Labels: cla: yes, size/L

#2921 Update Envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2901 Bind lifetime of http metadata to DownstreamRequest
  extensions/metadata_exchange/plugin.cc
  extensions/stats/plugin.cc
Labels: cla: yes, size/S

#2923 update envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2919 Add option to enable Log Compression for stackdriver access logs
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/config/v1alpha1/BUILD
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/stackdriver.cc
Labels: cla: yes, size/S

#2925 Update common-files manually
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: cla: yes, size/M

#2922 Add connection_id in stackdriver access log
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  test/envoye2e/stackdriver_plugin/stackdriver.go
Labels: cla: yes, size/S

#2929 Update Envoy SHA to match istio/envoy release-1.7 branch
  WORKSPACE
Labels: cla: yes, do-not-merge, size/S

#2930 Revert "Update Envoy SHA to match istio/envoy release-1.7 branch (#29…
  WORKSPACE
Labels: cla: yes, size/S

#2932 Set release managers as CODEOWNERS for release-1.7
  CODEOWNERS
Labels: cla: yes, size/XS

#2926 Use root context to differentiate stream direction in stats filter
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
Labels: cla: yes, size/S

#2934 Automator: update common-files@release-1.7 in istio/proxy@release-1.7
  out/.env
Labels: auto-merge, cla: yes, size/XS

#2928 Update Bazel version
  .bazelversion
Labels: cla: yes, size/XS

#2937 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/run.sh
  out/.env
Labels: auto-merge, cla: yes, size/S

#2938 Update Envoy SHA to match istio/envoy release-1.7 branch
  WORKSPACE
Labels: cla: yes, size/S

#2915 Consider 2xx and 3xx status codes as success when deciding to log or not
  extensions/access_log_policy/plugin.cc
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
Labels: cla: yes, ok-to-test, size/XS

#2940 Updates for 1.7
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
  src/envoy/http/mixer/README.md
  src/envoy/utils/filter_names.cc
  src/istio/mixerclient/create_global_dictionary.py
  test/integration/exchanged_token_integration_test.cc
  test/integration/istio_http_integration_test_with_envoy_jwt_filter.cc
  tools/deb/test/run_pilot_test.sh
Labels: cla: yes, size/M

#2942 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  out/.env
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2935 [release-1.7] Use root context to differentiate stream direction in stats filter
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
Labels: cla: yes, size/S

#2943 [release-1.6] update envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2944 Ignore the out/ dir
  .gitignore
  out/.env
Labels: cla: yes, size/XS

#2945 [release-1.7] Ignore the out/ dir
  .gitignore
  out/.env
Labels: cla: yes, size/XS

#2946 Bump Envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2924 This PR outputs binaries with BUILD_W_C=1
  Makefile.core.mk
Labels: cla: yes, size/XS

#2951 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2949 Add extra fields in stackdriver access logs to match envoy access logs
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  test/envoye2e/stackdriver_plugin/stackdriver.go
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry_sampled.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry_on_no_mx.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry_on_open.yaml.tmpl
Labels: cla: yes, size/L

#2953 update envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2948 Update check_repository script to check ENVOY_SHA in workspace file file
  WORKSPACE
  scripts/check-repository.sh
Labels: cla: yes, size/XS
