Repository istio/proxy, pull requests merged in 2020-08, with the labels that each got.

#2957 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2959 Automator: update common-files@release-1.7 in istio/proxy@release-1.7
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#2962 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2963 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2964 Fix Blackthrough Passthrough clusters destination service name refactoring
  extensions/common/context.cc
Labels: cla: yes, size/XS

#2958 [release-1.7] Update Envoy-WASM SHA to latest.
  WORKSPACE
Labels: cla: yes, size/XS

#2961 Set TextPayload for TCP Access Log
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger.h
  testdata/stackdriver/server_tcp_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry_on_no_mx.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry_on_open.yaml.tmpl
Labels: cherrypick/release-1.7, cla: yes, size/M

#2968 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2967 [release-1.7] Set TextPayload for TCP Access Log
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger.h
  testdata/stackdriver/server_tcp_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry_on_no_mx.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry_on_open.yaml.tmpl
Labels: cla: yes, release-notes-none, size/M

#2969 [release-1.7] Update Envoy-WASM SHA to latest with bugfixes.
  WORKSPACE
Labels: cla: yes, size/XS

#2971 [release-1.7] Add extra fields in stackdriver access logs to match envoy access logs
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  test/envoye2e/stackdriver_plugin/stackdriver.go
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry_sampled.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry_on_no_mx.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry_on_open.yaml.tmpl
Labels: cla: yes, release-notes-none, size/L

#2947 [Release-1.5] Fix container name as app_container in telemetry v2 (#2902)
  extensions/common/context.cc
  extensions/common/context_test.cc
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
Labels: cla: yes, size/S

#2972 [Release-1.7] Fix Blackhole Passthrough clusters destination service name refact…
  extensions/common/context.cc
Labels: cla: yes, size/XS

#2974 Automator: update common-files@release-1.7 in istio/proxy@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2975 Automator: update common-files@release-1.7 in istio/proxy@release-1.7
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2977 build: move util to envoy_cc rule
  src/istio/utils/BUILD
  src/istio/utils/utils_test.cc
Labels: cla: yes, size/S

#2976 [release-1.7] Update Envoy-WASM SHA to latest with bugfixes.
  WORKSPACE
Labels: cla: yes, size/XS

#2956 Update Envoy-WASM SHA to latest.
  .bazelversion
  WORKSPACE
  envoy.bazelrc
  extensions/access_log_policy/plugin.cc
  extensions/access_log_policy/plugin.h
  extensions/attributegen/plugin.cc
  extensions/attributegen/plugin.h
  extensions/attributegen/plugin_test.cc
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/istio_dimensions.h
  extensions/common/json_util.cc
  extensions/common/json_util.h
  extensions/common/proto_util.cc
  extensions/common/proto_util_speed_test.cc
  extensions/common/proto_util_test.cc
  extensions/metadata_exchange/base64.h
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/stackdriver.h
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  repositories.bzl
  src/envoy/BUILD
  src/envoy/http/authn/authn_utils_test.cc
  src/envoy/tcp/sni_verifier/sni_verifier.cc
  src/envoy/utils/utils.cc
  tools/deb/BUILD
Labels: cla: yes, size/L

#2980 Update Envoy-WASM SHA to latest with C++14 fix.
  WORKSPACE
Labels: cla: yes, size/XS

#2979 Update Envoy-WASM SHA to latest.
  WORKSPACE
  envoy.bazelrc
Labels: cla: yes, size/S

#2982 Bump Envoy
  WORKSPACE
Labels: cla: yes, size/XS

#2984 use antlr 472
  WORKSPACE
Labels: cla: yes, size/XS

#2985 Create the VM context as an IstioContext for consistency.
  src/envoy/extensions/wasm/wasm.cc
Labels: cla: yes, size/XS

#2983 use antlr 472
  WORKSPACE
Labels: cla: yes, size/XS

#2986 tests: fix parallel testing
  test/envoye2e/driver/scenario.go
  test/envoye2e/env/utils.go
  test/envoye2e/http_metadata_exchange/exchange_test.go
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  test/envoye2e/stats_plugin/README.md
  test/envoye2e/stats_plugin/stats_test.go
  testdata/bootstrap/client.yaml.tmpl
  testdata/bootstrap/server.yaml.tmpl
  testdata/filters/mx_inbound.yaml.tmpl
  testdata/filters/mx_outbound.yaml.tmpl
  testdata/filters/stackdriver_inbound.yaml.tmpl
  testdata/filters/stackdriver_outbound.yaml.tmpl
  testdata/filters/stats_inbound.yaml.tmpl
  testdata/filters/stats_outbound.yaml.tmpl
  testdata/listener/client.yaml.tmpl
  testdata/listener/server.yaml.tmpl
  testdata/listener/tcp_client.yaml.tmpl
  testdata/listener/tcp_server.yaml.tmpl
  testdata/stats/client_config_customized.yaml.tmpl
Labels: cla: yes, size/L

#2987 test: add ANTLR parser crash regression test
  WORKSPACE
  test/envoye2e/driver/envoy.go
  test/envoye2e/stats_plugin/stats_test.go
Labels: cla: yes, size/M

#2990 [Release-1.7] Update Envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2989 Update Proxy SHA and add test for rbac filter
  WORKSPACE
  test/envoye2e/stats_plugin/stats_test.go
  testdata/filters/rbac.yaml.tmpl
  testdata/metric/server_request_total.yaml.tmpl
Labels: cla: yes, size/M

#2991 Fix clang-10 compatibility: designated initializers are a C++20 exten…
  extensions/attributegen/plugin_test.cc
  extensions/common/istio_dimensions.h
  extensions/common/istio_dimensions_test.cc
  extensions/stats/plugin.cc
Labels: cla: yes, size/L

#2939 Add support for Wasm distribution failure mode stats.
  src/envoy/extensions/wasm/BUILD
  src/envoy/extensions/wasm/wasm.cc
Labels: cla: yes, size/L

#2970 Add audit log stream to stackdriver filter
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger.h
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  test/envoye2e/inventory.go
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/filters/rbac_log.yaml.tmpl
  testdata/filters/stackdriver_inbound.yaml.tmpl
  testdata/filters/stackdriver_outbound.yaml.tmpl
  testdata/stackdriver/server_audit_log.yaml.tmpl
  testdata/stackdriver/server_audit_log_entry.yaml.tmpl
Labels: cla: yes, size/XL

#2954 Basic Auth extension implementation and integration test
  Makefile.core.mk
  extensions/BUILD
  extensions/basic_auth/BUILD
  extensions/basic_auth/config.cc
  extensions/basic_auth/config.proto
  extensions/basic_auth/plugin.cc
  extensions/basic_auth/plugin.h
  scripts/release-binary.sh
  src/envoy/BUILD
  test/envoye2e/basic_auth/basic_auth_test.go
  test/envoye2e/env/utils.go
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/filters/basicauth.yaml.tmpl
  testdata/filters/basicauth_configuration_data.json
Labels: cla: yes, ok-to-test, size/XL

#2865 Initial centos build
  Makefile.core.mk
  prow/proxy-presubmit-centos-release.sh
  scripts/release-binary.sh
Labels: cla: yes, size/M

#2993 Update stackdriver filter to fallback to default mesh id format when not specified
  extensions/common/proto_util.cc
  extensions/common/proto_util.h
  extensions/stackdriver/stackdriver.cc
  testdata/client_node_metadata.json.tmpl
  testdata/gce_client_node_metadata.json.tmpl
  testdata/gce_server_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
  testdata/stackdriver/client_access_log.yaml.tmpl
  testdata/stackdriver/client_gateway_access_log.yaml.tmpl
  testdata/stackdriver/client_request_count.yaml.tmpl
  testdata/stackdriver/client_tcp_connection_count.yaml.tmpl
  testdata/stackdriver/gateway_access_log.yaml.tmpl
  testdata/stackdriver/gce_client_request_count.yaml.tmpl
  testdata/stackdriver/gce_server_request_count.yaml.tmpl
  testdata/stackdriver/gce_traffic_assertion.yaml.tmpl
  testdata/stackdriver/server_access_log.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
  testdata/stackdriver/server_tcp_connection_count.yaml.tmpl
  testdata/stackdriver/traffic_assertion.yaml.tmpl
Labels: cla: yes, size/M
