Repository istio/proxy, pull requests merged in 2020-01, with the labels that each got.

#2617 Update authn filter to use first spiffe san
  src/envoy/utils/utils.cc
  src/envoy/utils/utils_test.cc
Labels: cla: yes, size/M

#2618 deflake lru cache test (#2607)
  src/istio/utils/simple_lru_cache_test.cc
Labels: cla: yes, size/XS

#2616 [release-1.4] Extract service name from request host and cluster name (#2548)
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/metric/record.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  scripts/check-style.sh
  testdata/metric/client_request_total.yaml.tmpl
  testdata/stackdriver/client_request_count.yaml.tmpl
Labels: cla: yes, size/L

#2619 update envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2520 Enable TCP Metrics in Stats Plugin
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
  test/envoye2e/env/tcp_envoy_conf.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: cla: yes, size/L

#2602 Add support for Access Log Policy Filter
  extensions/access_log_policy/BUILD
  extensions/access_log_policy/Makefile
  extensions/access_log_policy/README.md
  extensions/access_log_policy/build_wasm.sh
  extensions/access_log_policy/config.cc
  extensions/access_log_policy/config/v1alpha1/BUILD
  extensions/access_log_policy/config/v1alpha1/access_log_policy_config.proto
  extensions/access_log_policy/plugin.cc
  extensions/access_log_policy/plugin.h
  extensions/common/BUILD
  extensions/common/context.h
  extensions/common/istio_dimensions.h
  extensions/common/istio_dimensions_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  src/envoy/BUILD
  test/envoye2e/driver/stackdriver.go
  test/envoye2e/env/setup.go
  test/envoye2e/stackdriver_plugin/fake_stackdriver/fake_stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/XL

#2620 Fix access logging plugin to be WASM compatible
  extensions/access_log_policy/plugin.cc
  extensions/access_log_policy/plugin.h
Labels: cla: yes, size/M

#2609 Update proxy to envoy-wasm@9cf22b8 (12/19)
  .bazelversion
  WORKSPACE
  envoy.bazelrc
  src/envoy/http/alpn/alpn_test.cc
  src/envoy/utils/stats.cc
Labels: cla: yes, size/M

#2622 Update envoy wasm sha
  WORKSPACE
  extensions/access_log_policy/plugin.cc
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/node_info_cache.cc
  extensions/metadata_exchange/plugin.cc
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/metric/record.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stats/plugin.cc
Labels: cla: yes, size/L

#2621 Check generated wasm file at presubmit
  .gitignore
  Makefile.core.mk
  extensions/access_log_policy/Makefile
  extensions/metadata_exchange/Makefile
  extensions/metadata_exchange/plugin.wasm
  extensions/stats/Makefile
  extensions/stats/plugin.wasm
  prow/proxy-presubmit-wasm.sh
  scripts/generate-wasm.sh
  test/envoye2e/env/ports.go
  test/envoye2e/stats/stats_xds_test.go
Labels: cla: yes, size/L

#2623 Push generated wasm files in postsubmit
  Makefile.core.mk
  scripts/generate-wasm.sh
Labels: cla: yes, size/M

#2625 Add extra labels to sd logging
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger.h
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stats/plugin.wasm
  test/envoye2e/driver/stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  testdata/stackdriver/gateway_access_log.yaml.tmpl
  testdata/stackdriver/server_access_log.yaml.tmpl
Labels: cla: yes, size/L

#2627 Simplify trace sampled condition
  extensions/common/context.cc
Labels: cla: yes, size/XS

#2630 Update common file, including license
  LICENSE
  Makefile
  Makefile.overrides.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/S

#2632 cherry-pick of #2462
  repositories.bzl
  src/istio/control/http/request_handler_impl.cc
  src/istio/control/http/request_handler_impl_test.cc
  src/istio/control/http/service_context.h
Labels: cla: yes, size/M

#2631 Merge envoy-wasm for v1.13.0.
  .bazelversion
  WORKSPACE
  envoy.bazelrc
  extensions/access_log_policy/config.cc
  extensions/access_log_policy/plugin.cc
  extensions/access_log_policy/plugin.h
  extensions/metadata_exchange/build_wasm.sh
  extensions/metadata_exchange/config.cc
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  extensions/metadata_exchange/plugin.wasm
  extensions/stackdriver/edges/mesh_edges_service_client.cc
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/stackdriver.h
  extensions/stackdriver/stackdriver_plugin_factory.cc
  extensions/stats/build_wasm.sh
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/plugin.wasm
  go.sum
  scripts/generate-wasm.sh
  src/envoy/http/alpn/config.cc
  src/envoy/http/alpn/config.h
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/filter_context.h
  src/envoy/http/authn/filter_context_test.cc
  src/envoy/http/authn/http_filter_factory.cc
  src/envoy/http/authn/origin_authenticator_test.cc
  src/envoy/http/authn/peer_authenticator_test.cc
  src/envoy/http/jwt_auth/http_filter_factory.cc
  src/envoy/http/mixer/check_data.cc
  src/envoy/http/mixer/check_data.h
  src/envoy/http/mixer/filter_factory.cc
  src/envoy/tcp/forward_downstream_sni/config.h
  src/envoy/tcp/metadata_exchange/config.h
  src/envoy/tcp/metadata_exchange/metadata_exchange_test.cc
  src/envoy/tcp/mixer/filter_factory.cc
  src/envoy/tcp/sni_verifier/config.h
  src/envoy/tcp/tcp_cluster_rewrite/config.h
  src/envoy/utils/authn.cc
  src/envoy/utils/authn.h
  src/envoy/utils/grpc_transport.cc
  src/envoy/utils/mixer_control.cc
  src/envoy/utils/mixer_control.h
  src/envoy/utils/mixer_control_test.cc
  src/envoy/utils/utils.cc
  src/envoy/utils/utils.h
  test/integration/exchanged_token_integration_test.cc
  test/integration/int_server.h
  test/integration/istio_http_integration_test.cc
  test/integration/istio_http_integration_test_with_envoy_jwt_filter.cc
  test/integration/mixer_fault_test.cc
Labels: cla: yes, size/L

#2633 bump SHA
  WORKSPACE
  prow/proxy-common.inc
Labels: cla: yes, size/M

#2634 Update Envoy-WASM SHA to latest.
  WORKSPACE
Labels: cla: yes, size/XS

#2628 [release-1.4] Add extra labels to sd logging
  extensions/common/context.cc
  extensions/common/context.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger.h
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/stackdriver.cc
  test/envoye2e/driver/stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
  testdata/stackdriver/server_access_log.yaml.tmpl
Labels: cla: yes, size/L

#2636 Do not skip os version check in presubmit release-test
  Makefile.core.mk
Labels: cla: yes, size/XS

#2641 Update CODEOWNERS and master refs to release-1.5
  CODEOWNERS
  common/.commonfiles.sha
  common/Makefile.common.mk
  tools/deb/test/run_pilot_test.sh
Labels: cla: yes, size/S

#2643 [release-1.3] Update API SHA in istio.deps to match repositories.bzl
  istio.deps
Labels: cla: yes, size/XS

#2629 Add TCP Metrics in stats filter similar to Istio 1.4
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/node_info_cache.cc
  extensions/common/node_info_cache.h
  extensions/metadata_exchange/plugin.wasm
  extensions/stackdriver/stackdriver.cc
  extensions/stats/BUILD
  extensions/stats/config.proto
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/plugin.wasm
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange.h
  test/envoye2e/env/ports.go
  test/envoye2e/env/setup.go
  test/envoye2e/env/tcp_envoy_conf.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  test/envoye2e/tcp_metadata_exchange/testoutput/client.yaml
  test/envoye2e/tcp_metadata_exchange/testoutput/server.yaml
Labels: cherrypick/release-1.5, cla: yes, size/XL

#2642 Fix missing response size
  WORKSPACE
Labels: cla: yes, size/XS

#2645 Bound AccessLog Cache
  extensions/access_log_policy/config/v1alpha1/access_log_policy_config.proto
  extensions/access_log_policy/plugin.cc
  extensions/access_log_policy/plugin.h
Labels: cla: yes, size/M
