Repository istio/proxy, pull requests merged in 2020-06, with the labels that each got.

#2866 Fix flaky integration test
  src/envoy/http/jwt_auth/integration_test/http_filter_integration_test.cc
Labels: cla: yes, size/XS

#2867 [1.5] Update envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2843 Add TCP Metrics in Stackdriver
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/metric/record.cc
  extensions/stackdriver/metric/record.h
  extensions/stackdriver/metric/registry.cc
  extensions/stackdriver/metric/registry.h
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  test/envoye2e/stackdriver_plugin/stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/filters/client_stats_network_filter.yaml.tmpl
  testdata/filters/server_stats_network_filter.yaml.tmpl
  testdata/filters/stackdriver_network_inbound.yaml.tmpl
  testdata/filters/stackdriver_network_outbound.yaml.tmpl
  testdata/stackdriver/client_tcp_connection_count.yaml.tmpl
  testdata/stackdriver/server_tcp_connection_count.yaml.tmpl
Labels: cla: yes, size/XL

#2873 Update sha cve
  Makefile.core.mk
  WORKSPACE
Labels: cla: yes, size/S

#2874 Merge 1.5.5 security patch
  WORKSPACE
Labels: cla: yes, size/XS

#2875 [release-1.4] Update envoy sha
  WORKSPACE
Labels: cla: yes, size/XS

#2878 Do not fail wasm build sdk image push
  scripts/generate-wasm.sh
Labels: cherrypick/release-1.5, cla: yes

#2880 Support dash in name
  scripts/generate-wasm.sh
Labels: cla: yes, size/XS

#2879 [release-1.6] fix early deletion of wasm state schema
  WORKSPACE
  test/envoye2e/stats_plugin/stats_xds_test.go
Labels: cla: yes, size/L

#2882 [release-1.5] cherry-pick wasm build fixes
  scripts/generate-wasm.sh
Labels: cla: yes, size/S

#2881 [release-1.6] make wasm build able to reference a local envoy folder
  scripts/generate-wasm.sh
Labels: cla: yes, size/S

#2870 fix(stackdriver): map grpc status codes into http domain for metrics
  extensions/stackdriver/metric/record.cc
Labels: cla: yes, size/M

#2884 [release-1.6] fix(stackdriver): map grpc status codes into http domain for metrics
  extensions/stackdriver/metric/record.cc
Labels: cla: yes, size/M
