Repository istio/proxy, pull requests merged in 2020-04, with the labels that each got.

#2787 deps: update go-control-plane, switch to v3 xDS
  Makefile.core.mk
  go.mod
  go.sum
  test/envoye2e/basic_flow/basic_xds_test.go
  test/envoye2e/driver/envoy.go
  test/envoye2e/driver/scenario.go
  test/envoye2e/driver/xds.go
  test/envoye2e/env/envoy_conf.go
  test/envoye2e/env/tcp_envoy_conf.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  test/envoye2e/stats_plugin/stats_plugin_grpc_test.go
  test/envoye2e/stats_plugin/stats_plugin_test.go
  test/envoye2e/stats_plugin/stats_xds_test.go
  testdata/bootstrap/client.yaml.tmpl
  testdata/bootstrap/server.yaml.tmpl
  testdata/transport_socket/client.yaml.tmpl
  testdata/transport_socket/server.yaml.tmpl
Labels: cla: yes, size/L

#2777 Decide unhealthy connection on presence of no response flags
  extensions/stats/plugin.cc
Labels: cherrypick/release-1.5, cla: yes, size/XS

#2786 Add tracing support in fake stackdriver
  go.mod
  go.sum
  test/envoye2e/driver/fake_stackdriver.go
  test/envoye2e/driver/stackdriver.go
  test/envoye2e/stackdriver_plugin/cmd/Makefile
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/L

#2792 Fix telemetry v2 for blackhole and passthrough clusters
  extensions/common/context.cc
Labels: cherrypick/release-1.5, cla: yes, size/S

#2795 feat(stackdriver): use app container for k8s_container when appropriate
  extensions/common/context.cc
  extensions/common/context_test.cc
  extensions/common/node_info.proto
  extensions/stackdriver/common/utils.cc
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
  testdata/stackdriver/gateway_access_log.yaml.tmpl
  testdata/stackdriver/server_access_log.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
Labels: cla: yes, size/M

#2793 [release-1.5] Fix telemetry v2 for blackhole and passthrough clusters
  extensions/common/context.cc
Labels: cla: yes, size/S

#2790 call proxy_done only when there is no inflight call
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/log/exporter.h
Labels: cla: yes, size/M

#2796 disable RBE for real
  prow/proxy-common.inc
Labels: cla: yes, size/M

#2797 Attempt to fix post-submit #2
  Makefile.core.mk
  prow/proxy-common.inc
Labels: cla: yes, size/M

#2798 fix(edges): increase timeout for meshtelemetry API calls
  extensions/stackdriver/edges/mesh_edges_service_client.cc
Labels: cla: yes, size/XS

#2802 cleanup: remove unused code
  .gitignore
  Makefile.core.mk
  extensions/access_log_policy/plugin.cc
  extensions/common/BUILD
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/context_speed_test.cc
  extensions/common/context_test.cc
  extensions/common/node_info.proto
  extensions/common/node_info_cache.cc
  extensions/common/node_info_cache.h
  extensions/metadata_exchange/Makefile
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stats/BUILD
  extensions/stats/Makefile
  extensions/stats/plugin.cc
  extensions/stats/proxy_expr.h
  test/envoye2e/driver/fake_stackdriver.go
Labels: cla: yes, size/XL

#2808 [release-1.4] Update to latest Envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2811 Update envoy sha to pick zipkin tracing fix
  WORKSPACE
Labels: cla: yes, size/XS

#2791 [release-1.5] Decide unhealthy connection on presence of no response flags
  extensions/stats/plugin.cc
Labels: cla: yes, size/XS

#2812 [release-1.5] feat(stackdriver): use app container for k8s_container when appropriate
  extensions/common/context.cc
  extensions/common/context_test.cc
  extensions/common/node_info.proto
  extensions/stackdriver/common/utils.cc
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
  testdata/stackdriver/gateway_access_log.yaml.tmpl
  testdata/stackdriver/server_access_log.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
Labels: cla: yes, size/M

#2813 [release-1.5] fix(edges): increase timeout for meshtelemetry API calls
  extensions/stackdriver/edges/mesh_edges_service_client.cc
Labels: cla: yes, size/XS

#2814 Change Error Log in AccessLog Plugin from Stackdriver to AccessLog
  extensions/access_log_policy/plugin.cc
Labels: cla: yes, size/XS

#2767 fix(stackdriver): support turning off http size metrics
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/metric/record.cc
  extensions/stackdriver/metric/record.h
  extensions/stackdriver/stackdriver.cc
Labels: cla: yes, size/L

#2804 feat(edges): add support for canonical service labels
  extensions/common/context.h
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edges.proto
  extensions/stackdriver/metric/record.cc
  extensions/stats/plugin.cc
  test/envoye2e/stackdriver_plugin/edges/edges.pb.go
  testdata/stackdriver/traffic_assertion.yaml.tmpl
Labels: cla: yes, size/L

#2803 add gen doc for extension protos
  Makefile.core.mk
  common-protos/google/protobuf/duration.proto
  common-protos/google/protobuf/wrappers.proto
  extensions/metadata_exchange/config.pb.html
  extensions/metadata_exchange/config.proto
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.pb.html
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stats/config.pb.html
  extensions/stats/config.proto
Labels: cla: yes, size/L

#2818 feat(stackdriver): add canonical service info to logs
  extensions/stackdriver/log/logger.cc
  testdata/stackdriver/gateway_access_log.yaml.tmpl
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
Labels: cla: yes, size/M

#2819 add period to description
  extensions/stats/config.pb.html
  extensions/stats/config.proto
Labels: cla: yes, size/XS

#2821 Remove directional root context in metadata exchange filter
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  test/envoye2e/stats_plugin/stats_xds_test.go
Labels: cla: yes, size/S

#2805 feat(node_info): add cluster_id to node_info
  extensions/common/context.cc
  extensions/common/context_test.cc
  extensions/common/node_info.fbs
Labels: cla: yes, size/XS

#2816 feat(stackdriver): derive owners from platform_meta for gce instances
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/metric/record.cc
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  testdata/gce_client_node_metadata.json.tmpl
  testdata/gce_server_node_metadata.json.tmpl
  testdata/stackdriver/gce_client_request_count.yaml.tmpl
  testdata/stackdriver/gce_server_request_count.yaml.tmpl
Labels: cla: yes, size/L

#2817 update envoy to 1.14.1
  .gitignore
  Makefile.core.mk
  WORKSPACE
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/context_speed_test.cc
  extensions/metadata_exchange/BUILD
  extensions/metadata_exchange/Makefile
  extensions/metadata_exchange/declare_property.proto
  extensions/metadata_exchange/plugin.cc
  extensions/stackdriver/edges/mesh_edges_service_client.cc
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stats/plugin.cc
  scripts/generate-wasm.sh
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator.h
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange.h
  testdata/metric/client_request_total_customized.yaml.tmpl
  testdata/stats/client_config.yaml
  testdata/stats/client_config_customized.yaml
  testdata/stats/client_config_disable_header_fallback.yaml
Labels: cla: yes, size/L

#2801 CEL based v2 attribute generation: Request Classification.
  extensions/attributegen/.gitignore
  extensions/attributegen/BUILD
  extensions/attributegen/Makefile
  extensions/attributegen/build_wasm.sh
  extensions/attributegen/config.proto
  extensions/attributegen/plugin.cc
  extensions/attributegen/plugin.h
  extensions/attributegen/plugin_test.cc
  extensions/attributegen/testdata/BUILD
  extensions/attributegen/testdata/operation.json
  extensions/attributegen/testdata/responseCode.json
  extensions/attributegen/testdata/server.yaml
  src/envoy/BUILD
Labels: cla: yes, do-not-merge, size/XXL

#2823 add attribute auto-gen docs
  Makefile.core.mk
  extensions/attributegen/config.pb.html
Labels: cla: yes, size/XS

#2807 Remove protobuf from stats extension
  .gitignore
  Makefile.core.mk
  WORKSPACE
  extensions/common/BUILD
  extensions/common/context.cc
  extensions/common/context.h
  extensions/common/json_util.cc
  extensions/common/json_util.h
  extensions/common/proto_util.cc
  extensions/common/proto_util.h
  extensions/common/proto_util_speed_test.cc
  extensions/common/proto_util_test.cc
  extensions/metadata_exchange/BUILD
  extensions/metadata_exchange/Makefile
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  extensions/stackdriver/BUILD
  extensions/stackdriver/edges/BUILD
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stats/BUILD
  extensions/stats/Makefile
  extensions/stats/config.proto
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  scripts/generate-wasm.sh
  src/envoy/tcp/metadata_exchange/BUILD
  src/envoy/tcp/metadata_exchange/metadata_exchange.h
  test/envoye2e/http_metadata_exchange/exchange_xds_test.go
  test/envoye2e/http_metadata_exchange/http_metadata_exchange_test.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  test/envoye2e/stats_plugin/stats_xds_test.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  testdata/listener/client.yaml.tmpl
  testdata/listener/server.yaml.tmpl
  testdata/stats/server_config.yaml
Labels: cla: yes, size/XL

#2825 Update envoy sha
  WORKSPACE
  extensions/attributegen/plugin_test.cc
Labels: cla: yes, size/S

#2827 update 16 owner and common files
  CODEOWNERS
  common/.commonfiles.sha
  common/Makefile.common.mk
  tools/deb/test/run_pilot_test.sh
Labels: cla: yes, size/S

#2824 Add documentation for access log plugin
  Makefile.core.mk
  extensions/access_log_policy/config/v1alpha1/.gitignore
  extensions/access_log_policy/config/v1alpha1/access_log_policy_config.pb.html
  extensions/access_log_policy/config/v1alpha1/access_log_policy_config.proto
  extensions/common/context.h
  extensions/metadata_exchange/config.pb.html
Labels: cla: yes, size/S

#2829 Fix error during doc generation
  extensions/attributegen/config.pb.html
  extensions/attributegen/config.proto
  extensions/metadata_exchange/declare_property.pb.html
Labels: cherrypick/release-1.6, cla: yes, size/XS

#2830 [release-1.6] Fix error during doc generation
  extensions/attributegen/config.pb.html
  extensions/attributegen/config.proto
  extensions/metadata_exchange/declare_property.pb.html
Labels: cla: yes, size/XS

#2831 fix location tag, update proto format
  extensions/access_log_policy/config/v1alpha1/access_log_policy_config.pb.html
  extensions/access_log_policy/config/v1alpha1/access_log_policy_config.proto
  extensions/attributegen/config.pb.html
  extensions/attributegen/config.proto
  extensions/metadata_exchange/config.pb.html
  extensions/metadata_exchange/config.proto
  extensions/metadata_exchange/declare_property.pb.html
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.pb.html
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
Labels: cla: yes, size/S

#2828 [release-1.6] Add documentation for access log plugin
  Makefile.core.mk
  extensions/access_log_policy/config/v1alpha1/.gitignore
  extensions/access_log_policy/config/v1alpha1/access_log_policy_config.pb.html
  extensions/access_log_policy/config/v1alpha1/access_log_policy_config.proto
  extensions/common/context.h
  extensions/metadata_exchange/config.pb.html
Labels: cla: yes, size/S

#2833 [release-1.6] fix location tag, update proto format (#2831)
  extensions/access_log_policy/config/v1alpha1/access_log_policy_config.pb.html
  extensions/access_log_policy/config/v1alpha1/access_log_policy_config.proto
  extensions/attributegen/config.pb.html
  extensions/attributegen/config.proto
  extensions/metadata_exchange/config.pb.html
  extensions/metadata_exchange/config.proto
  extensions/metadata_exchange/declare_property.pb.html
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.pb.html
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
Labels: cla: yes, size/S

#2834 Fix type url in TCP Exchange test
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: cherrypick/release-1.6, cla: yes, size/S

#2835 [release-1.6] Fix type url in TCP Exchange test
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: cla: yes, size/S
