Repository istio/proxy, pull requests merged in 2020-03, with the labels that each got.

#2730 cleanup: deprecate empty proto as config
  src/envoy/tcp/forward_downstream_sni/BUILD
  src/envoy/tcp/forward_downstream_sni/config.cc
  src/envoy/tcp/forward_downstream_sni/config.proto
  src/envoy/tcp/sni_verifier/BUILD
  src/envoy/tcp/sni_verifier/config.cc
  src/envoy/tcp/sni_verifier/config.proto
Labels: cla: yes, size/M

#2740 add owners to telemetry extensions
  CODEOWNERS
Labels: cla: yes, size/XS

#2739 Add stackdriver stub param
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/edges/mesh_edges_service_client.cc
  extensions/stackdriver/edges/mesh_edges_service_client.h
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/log/exporter.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/metric/registry.cc
  extensions/stackdriver/metric/registry.h
  extensions/stackdriver/metric/registry_test.cc
  extensions/stackdriver/stackdriver.cc
  testdata/client_node_metadata.json.tmpl
  testdata/server_node_metadata.json.tmpl
Labels: cla: yes, size/L

#2742 Remove not getting TCP Metrics for unknown peers and Add Context in onTick calls
  WORKSPACE
  extensions/stats/plugin.cc
Labels: cherrypick/release-1.5, cla: yes, size/S

#2746 [Release-1.5] Remove not getting TCP Metrics for unknown peers and Add Context in o…
  WORKSPACE
  extensions/stats/plugin.cc
  src/envoy/tcp/sni_verifier/sni_verifier_test.cc
Labels: cla: yes, size/S

#2752 Add telemetry v2 wasm runtime example config
  extensions/stats/testdata/telemetry-v2-wasm.yaml
Labels: cla: yes, size/L

#2753 Add a test for TCP metrics for a long running TCP connection
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: cla: yes, size/L

#2755 override image name (IMAGE_NAME) only
  Makefile
  Makefile.core.mk
  Makefile.overrides.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  scripts/check-build-tools-proxy.sh
Labels: cherrypick/release-1.5, cla: yes, size/M

#2754 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#2757 Add log entry fetch endpoint to fake sd
  test/envoye2e/driver/fake_stackdriver.go
  test/envoye2e/stackdriver_plugin/cmd/Makefile
Labels: cla: yes, size/S

#2759 Add dummy "gen" target
  Makefile.core.mk
Labels: cla: yes, size/XS

#2756 [release-1.5] override image name (IMAGE_NAME) only
  Makefile
  Makefile.core.mk
  Makefile.overrides.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  scripts/check-build-tools-proxy.sh
Labels: cla: yes, size/M

#2762 Update Envoy-WASM SHA
  WORKSPACE
  src/envoy/http/authn/authenticator_base_test.cc
  src/envoy/http/authn/filter_context.h
  src/envoy/http/authn/filter_context_test.cc
  src/envoy/http/authn/origin_authenticator.cc
  src/envoy/http/authn/origin_authenticator_test.cc
  src/envoy/http/authn/peer_authenticator_test.cc
  src/envoy/http/jwt_auth/jwt_authenticator.cc
  src/envoy/http/jwt_auth/jwt_authenticator.h
  src/envoy/http/jwt_auth/jwt_authenticator_test.cc
  src/envoy/http/jwt_auth/token_extractor.cc
  src/envoy/http/jwt_auth/token_extractor.h
  src/envoy/http/jwt_auth/token_extractor_test.cc
  src/envoy/http/mixer/check_data.cc
  src/envoy/http/mixer/check_data.h
  src/envoy/http/mixer/filter.cc
  src/envoy/http/mixer/filter.h
  src/envoy/http/mixer/report_data.h
  src/envoy/tcp/sni_verifier/sni_verifier_test.cc
Labels: cla: yes, size/L

#2763 Use onLog for TCP stats
  extensions/stats/plugin.h
Labels: cla: yes, size/M

#2764 [release-1.5] Use onLog for TCP stats
  WORKSPACE
  extensions/stats/plugin.h
Labels: cla: yes, size/M

#2685 Add check for gRPC status in access log filter
  extensions/access_log_policy/plugin.cc
  extensions/access_log_policy/plugin.h
  src/envoy/tcp/metadata_exchange/metadata_exchange.cc
  src/envoy/tcp/metadata_exchange/metadata_exchange.h
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/M

#2766 Fix seg fault in mixer tcp after upgrading envoy-wasm sha
  src/envoy/tcp/mixer/filter.cc
Labels: cla: yes, size/XS

#2765 fix(stackdriver): use more appropriate buckets for bytes
  extensions/stackdriver/metric/registry.cc
Labels: cla: yes, size/S

#2771 Full Revert of STS changes after Istio 1.4.5
  WORKSPACE
  extensions/stackdriver/common/BUILD
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/config/v1alpha1/stackdriver_plugin_config.proto
  extensions/stackdriver/edges/BUILD
  extensions/stackdriver/edges/edge_reporter.cc
  extensions/stackdriver/edges/edge_reporter.h
  extensions/stackdriver/edges/edge_reporter_test.cc
  extensions/stackdriver/edges/mesh_edges_service_client.cc
  extensions/stackdriver/edges/mesh_edges_service_client.h
  extensions/stackdriver/log/BUILD
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/log/exporter.h
  extensions/stackdriver/metric/BUILD
  extensions/stackdriver/metric/record.cc
  extensions/stackdriver/metric/registry.cc
  extensions/stackdriver/metric/registry.h
  extensions/stackdriver/stackdriver.cc
  go.sum
  test/envoye2e/driver/stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver_plugin_test.go
Labels: cla: yes, size/XL

#2773 Update Envoy SHA to latest and enable TLSv1.3 in sni_verifier. (#17)
  WORKSPACE
  src/envoy/tcp/sni_verifier/sni_verifier.cc
  src/envoy/tcp/sni_verifier/sni_verifier.h
  src/envoy/tcp/sni_verifier/sni_verifier_test.cc
Labels: cla: yes, size/M

#2775 Update Envoy SHA.
  WORKSPACE
Labels: cla: yes, size/XS

#2768 [release-1.5] fix(stackdriver): use more appropriate buckets for bytes
  extensions/stackdriver/metric/registry.cc
Labels: cla: yes, size/S

#2774 increase life span for data in tcp cluster rewrite
  .gitignore
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite_test.cc
Labels: cherrypick/release-1.5, cla: yes, size/M

#2776 [release-1.5] increase life span for data in tcp cluster rewrite
  .gitignore
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite_test.cc
Labels: cla: yes, size/M

#2778 [Release-1.5] Update Envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2779 Update Envoy SHA
  WORKSPACE
Labels: cla: yes, size/XS

#2731 add x-goog-user-project header to stackdriver call out
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/metric/registry.cc
  extensions/stackdriver/stackdriver.cc
  test/envoye2e/driver/fake_stackdriver.go
Labels: cla: yes, size/M

#2781 Automator: update common-files@release-1.5 in istio/proxy@release-1.5
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#2780 Flush log entries in on done
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/log/exporter.h
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/log/logger.h
  extensions/stackdriver/log/logger_test.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stackdriver/stackdriver.h
  test/envoye2e/env/ports.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
Labels: cla: yes, size/L

#2782 fix and deflake SD reload test
  test/envoye2e/driver/xds.go
  test/envoye2e/env/utils.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  test/envoye2e/stats/stats_xds_test.go
Labels: cla: yes, size/M

#2747 Fix building with gcc
  Makefile.core.mk
Labels: cla: yes, ok-to-test, size/S

#2785 Add configurable monitoring endpoint
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/utils.h
  extensions/stackdriver/metric/registry.cc
  extensions/stackdriver/stackdriver.cc
Labels: cla: yes, size/M

#2789 wasm: remove free symbol export
  extensions/metadata_exchange/Makefile
  extensions/stats/Makefile
Labels: cla: yes, ok-to-test, size/XS

#2788 metadata: respond with the metadata only if the request includes the metadata
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  test/envoye2e/basic_flow/basic_xds_test.go
  test/envoye2e/driver/check.go
  test/envoye2e/env/ports.go
  test/envoye2e/http_metadata_exchange/exchange_xds_test.go
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  test/envoye2e/stats/stats_xds_test.go
Labels: cla: yes, size/L

#2783 Improve Wasm plugins stats
  extensions/stackdriver/common/BUILD
  extensions/stackdriver/common/metrics.cc
  extensions/stackdriver/common/metrics.h
  extensions/stackdriver/edges/BUILD
  extensions/stackdriver/edges/mesh_edges_service_client.cc
  extensions/stackdriver/edges/mesh_edges_service_client.h
  extensions/stackdriver/log/BUILD
  extensions/stackdriver/log/exporter.cc
  extensions/stackdriver/stackdriver.cc
  extensions/stats/plugin.h
  test/envoye2e/stackdriver_plugin/stackdriver_xds_test.go
  testdata/bootstrap/stats.yaml.tmpl
  testdata/metric/stackdriver_callout_metric.yaml.tmpl
Labels: cla: yes, size/L
