Repository istio/proxy, pull requests merged in 2021-12, with the labels that each got.

#3611 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3612 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3610 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3613 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3614 fix string includes for header
  extensions/stackdriver/common/constants.h
Labels: cla: yes, size/XS

#3615 simplify visibility of common stackdriver targets
  extensions/stackdriver/common/BUILD
Labels: cla: yes, size/S

#3616 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3617 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3618 Automator: update common-files@release-1.12 in istio/proxy@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3619 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#3620 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3621 delete BTS upstream extension code
  src/envoy/upstreams/http/metadata/BUILD
  src/envoy/upstreams/http/metadata/config.cc
  src/envoy/upstreams/http/metadata/config.h
  src/envoy/upstreams/http/metadata/integration_test.cc
  src/envoy/upstreams/http/metadata/upstream_request.cc
  src/envoy/upstreams/http/metadata/upstream_request.h
  src/envoy/upstreams/http/metadata/upstream_request_test.cc
Labels: size/L

#3622 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3623 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3624 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3625 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3626 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3627 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3628 Automator: update common-files@release-1.12 in istio/proxy@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3629 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3631 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3632 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3633 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3634 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3636 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3639 add envoy.access_loggers.extension_filters.cel
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#3637 Refactor Makefile to reduce copy-pasted rules
  Makefile.core.mk
Labels: ok-to-test, size/M

#3641 fix build
  WORKSPACE
  src/envoy/http/alpn/alpn_filter.cc
  src/envoy/http/alpn/alpn_test.cc
Labels: size/S

#3635 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3642 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3570 Fix lint errors with updated hadolint version
  tools/extensionserver/Dockerfile
Labels: cla: yes, size/XS
