Repository istio/proxy, pull requests merged in 2021-11, with the labels that each got.

#3557 Update to envoyproxy v1.20 and update extensions config
  .bazelversion
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
  envoy.bazelrc
Labels: cla: yes, size/M

#3561 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3562 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3563 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3560 contrib: enable all contrib extensions
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
Labels: cla: yes, size/S

#3564 BUILD: import pip3 bazel dep
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
Labels: cla: yes, size/XS

#3565 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3566 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
  envoy.bazelrc
Labels: cla: yes, size/S, auto-merge

#3567 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3568 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3569 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3571 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3572 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3573 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3574 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3575 Automator: update common-files@release-1.12 in istio/proxy@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3576 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3534 Export the cache to correct arch location
  Makefile.core.mk
Labels: cla: yes, ok-to-test, size/XS

#3577 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3578 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3580 feat(stackdriver): add more detailed logging around overrides
  extensions/stackdriver/stackdriver.cc
Labels: cla: yes, size/XS

#3579 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: cla: yes, size/M, auto-merge, release-notes-none

#3581 Automator: update common-files@master in istio/proxy@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3583 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3582 [release-1.12] feat(stackdriver): add more detailed logging around overrides
  extensions/stackdriver/stackdriver.cc
Labels: cla: yes, size/XS, release-notes-none

#3584 Use sigs.k8s.io/yaml instead of ghodss
  go.mod
  go.sum
  test/envoye2e/driver/resource.go
  test/envoye2e/driver/scenario.go
  tools/extensionserver/config.go
Labels: cla: yes, size/S

#3585 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: cla: yes, size/XS, auto-merge

#3586 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3587 Automator: update common-files@release-1.12 in istio/proxy@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3588 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3590 Automator: update common-files@release-1.11 in istio/proxy@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3589 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3592 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: cla: yes, size/S, auto-merge, release-notes-none

#3593 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3594 Fix release postsubmit since we moved to workload identity and are not using GOOGLE_APPLICATION_CREDENTIALS anymore
  prow/proxy-postsubmit-centos.sh
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/S, cherrypick/release-1.8, cherrypick/release-1.9, cherrypick/release-1.10, cherrypick/release-1.11, cherrypick/release-1.12

#3595 [release-1.8] Fix release postsubmit since we moved to workload identity and are not using GOOGLE_APPLICATION_CREDENTIALS anymore
  prow/proxy-postsubmit-centos.sh
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/S, release-notes-none

#3600 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3596 [release-1.9] Fix release postsubmit since we moved to workload identity and are not using GOOGLE_APPLICATION_CREDENTIALS anymore
  prow/proxy-postsubmit-centos.sh
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/S, auto-merge, release-notes-none

#3601 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3598 [release-1.11] Fix release postsubmit since we moved to workload identity and are not using GOOGLE_APPLICATION_CREDENTIALS anymore
  prow/proxy-postsubmit-centos.sh
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/S, release-notes-none

#3602 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3603 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3604 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3599 [release-1.12] Fix release postsubmit since we moved to workload identity and are not using GOOGLE_APPLICATION_CREDENTIALS anymore
  prow/proxy-postsubmit-centos.sh
  prow/proxy-postsubmit.sh
Labels: cla: yes, size/S, release-notes-none

#3605 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3606 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3607 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3608 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3609 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge
