Repository istio/proxy, pull requests merged in 2021-09, with the labels that each got.

#3475 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3476 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3478 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3479 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3480 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3481 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3477 clear route cache after JWT validation
  bazel/repositories.bzl
  src/envoy/http/authn/http_filter.cc
Labels: cla: yes, size/S

#3483 Automator: update envoy@ in istio/proxy@release-1.11
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3482 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3484 Automator: update common-files@release-1.10 in istio/proxy@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3485 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3487 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3486 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3488 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3489 Automator: update common-files@release-1.9 in istio/proxy@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3490 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3492 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3493 Update Envoy SHA to 09-13.
  WORKSPACE
  extensions/stackdriver/common/metrics.cc
  src/envoy/BUILD
  src/envoy/extensions/wasm/BUILD
  src/envoy/extensions/wasm/wasm.cc
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/metric/stackdriver_callout_metric.yaml.tmpl
  testdata/metric/stackdriver_gateway_callout_metric.yaml.tmpl
Labels: cla: yes, size/L

#3491 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3494 test: enhance metrics check failure message.
  test/envoye2e/driver/stats.go
Labels: cla: yes, size/XS

#3496 Automator: update common-files@release-1.11 in istio/proxy@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3495 build: Run v8://build only when required
  Makefile.core.mk
Labels: cla: yes, ok-to-test, size/S

#3497 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3498 Automator: update common-files@release-1.10 in istio/proxy@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#3499 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3500 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3502 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3503 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3504 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3501 Allow skipping reporting of individual prometheus metrics
  extensions/stats/config.proto
  extensions/stats/plugin.cc
  test/envoye2e/driver/stats.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/stats/client_config_customized.yaml.tmpl
Labels: cla: yes, size/M

#3507 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3508 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3509 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3510 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3511 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge

#3514 Update Envoy SHA 0930.
  WORKSPACE
  envoy.bazelrc
  extensions/attributegen/testdata/server.yaml
  extensions/stackdriver/testdata/stackdriver_filter.yaml
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/istio/stats_filter.yaml
  extensions/stats/testdata/server.yaml
  src/envoy/http/authn/sample/APToken/aptoken-envoy.conf
  testdata/listener/client.yaml.tmpl
  testdata/listener/server.yaml.tmpl
  testdata/testdata.gen.go
  tools/extensionserver/envoyfilter.yaml
Labels: cla: yes, size/M

#3515 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: cla: yes, size/XS, auto-merge
