Repository istio/proxy, pull requests merged in 2021-04, with the labels that each got.

#3267 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3268 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3269 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3270 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3271 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3272 [release-1.10] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#3273 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3278 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3274 Automator: update common-files@release-1.10 in istio/proxy@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3276 Automator: update common-files@release-1.9 in istio/proxy@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3275 Automator: update common-files@release-1.8 in istio/proxy@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3277 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3279 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3280 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: auto-merge, cla: yes, size/S

#3281 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3283 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3285 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3284 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3288 Manual update of Envoy - with change needed for new build image
  WORKSPACE
  envoy.bazelrc
  scripts/check-style.sh
Labels: cla: yes, size/S

#3287 [release-1.10] Update Envoy version - Manual CP of #3284
  WORKSPACE
Labels: cla: yes, size/XS

#3289 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3290 Automator: update envoy@release-1.9 in istio/proxy@release-1.9
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3292 Automator: update envoy@release-1.8 in istio/proxy@release-1.8
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3294 Update Envoy SHA to v1.18.2.
  WORKSPACE
  envoy.bazelrc
  src/envoy/http/authn/http_filter_integration_test.cc
  test/integration/exchanged_token_integration_test.cc
  test/integration/istio_http_integration_test_with_envoy_jwt_filter.cc
Labels: cla: yes, size/M

#3293 Update Envoy SHA to latest.
  WORKSPACE
  envoy.bazelrc
  src/envoy/http/authn/http_filter_integration_test.cc
  test/integration/exchanged_token_integration_test.cc
  test/integration/istio_http_integration_test_with_envoy_jwt_filter.cc
Labels: cla: yes, size/M

#3296 Fix workspace for 1.10
  WORKSPACE
Labels: cla: yes, size/XS

#3297 Automator: update envoy@release-1.10 in istio/proxy@release-1.10
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3299 Automator: update common-files@release-1.10 in istio/proxy@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3302 Update to use latest commit of envoyproxy/envoy release/v1.18 branch
  WORKSPACE
  scripts/update_envoy.sh
Labels: cla: yes, size/S

#3301 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3303 Automator: update envoy@ in istio/proxy@release-1.10
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3305 Automator: update envoy@ in istio/proxy@release-1.10
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3304 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3300 Automator: update common-files@release-1.9 in istio/proxy@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3307 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3306 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3308 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3311 Fix sha verification breakage
  bazel/repositories.bzl
Labels: cherrypick/release-1.10, cherrypick/release-1.9, cla: yes, flag/needs-backport, size/XS

#3309 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3315 scripts: fix downloading clang-format
  scripts/check-style.sh
Labels: cla: yes, size/XS

#3316 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3317 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3318 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3313 [release-1.10] Fix sha verification breakage
  bazel/repositories.bzl
Labels: cla: yes, release-notes-none, size/XS
