Repository istio/proxy, pull requests merged in 2021-07, with the labels that each got.

#3397 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3399 Automator: update common-files@release-1.10 in istio/proxy@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3400 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3401 Automator: update common-files@release-1.9 in istio/proxy@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3402 Add explicit build dependency for authenticator extension
  src/envoy/http/authn/BUILD
Labels: cla: yes, size/XS

#3404 wasm: delete unused code.
  src/envoy/extensions/wasm/BUILD
  src/envoy/extensions/wasm/context.h
  src/envoy/extensions/wasm/wasm.cc
Labels: cla: yes, ok-to-test, size/L

#3405 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3395 Update Envoy SHA to 07-12.
  WORKSPACE
  envoy.bazelrc
  extensions/attributegen/plugin_test.cc
  testdata/bootstrap/client.yaml.tmpl
  testdata/bootstrap/server.yaml.tmpl
  testdata/testdata.gen.go
Labels: cla: yes, size/S

#3406 Bump envoy to fix a crash
  WORKSPACE
Labels: cla: yes, size/XS

#3408 Automator: update common-files@release-1.9 in istio/proxy@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3407 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3411 Bump Envoy SHA
  WORKSPACE
  extensions/attributegen/BUILD
Labels: cla: yes, size/XS

#3409 Automator: update common-files@release-1.10 in istio/proxy@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3390 [release-1.10] Update response flag parsing.
  extensions/common/context.h
  extensions/common/util.cc
  extensions/common/util_test.cc
Labels: cla: yes, release-notes-none, size/M

#3413 wasm: remove unused Istio specific Wasm code under src.
  src/envoy/extensions/wasm/BUILD
  src/envoy/extensions/wasm/wasm.cc
Labels: cla: yes, ok-to-test, size/L

#3414 [release-1.11] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#3415 Automator: update common-files@release-1.11 in istio/proxy@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3412 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3416 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3417 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3418 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3419 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3420 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3421 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3422 Automator: update common-files@release-1.10 in istio/proxy@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3424 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3426 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: auto-merge, cla: yes, size/XS

#3427 Automator: update common-files@release-1.11 in istio/proxy@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3423 Automator: update envoy@ in istio/proxy@release-1.10
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3428 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: auto-merge, cla: yes, size/XS

#3429 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#3430 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3431 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3432 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3433 Bump envoy to 1.19.0 final
  WORKSPACE
Labels: cla: yes, size/XS

#3425 Automator: update envoy@release-1.9 in istio/proxy@release-1.9
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3434 Automator: update envoy@ in istio/proxy@release-1.10
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3435 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3436 Fix link for CEL expression builtin attributes
  extensions/attributegen/config.pb.html
  extensions/attributegen/config.proto
Labels: cla: yes, size/XS

#3437 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: auto-merge, cla: yes, size/XS

#3438 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: auto-merge, cla: yes, size/XS
