Repository istio/proxy, pull requests merged in 2022-04, with the labels that each got.

#3798 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3799 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3800 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3658 stats: fix crash on invalid json
  extensions/stats/plugin.cc
Labels: ok-to-test, size/XS, lifecycle/automatically-closed

#3801 build fixes
  WORKSPACE
  envoy.bazelrc
  extensions/common/BUILD
  extensions/stackdriver/common/BUILD
  extensions/stackdriver/log/BUILD
  extensions/stackdriver/metric/BUILD
  extensions/stats/BUILD
  src/envoy/tcp/metadata_exchange/BUILD
  src/envoy/tcp/metadata_exchange/config.h
  test/envoye2e/driver/envoy.go
  testdata/bootstrap/server.yaml.tmpl
  testdata/listener/client.yaml.tmpl
  testdata/listener/server.yaml.tmpl
  testdata/listener/tcp_client.yaml.tmpl
  testdata/listener/tcp_server.yaml.tmpl
Labels: size/M

#3795 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3802 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#3803 Automator: update envoy@ in istio/proxy@master
  .bazelversion
  WORKSPACE
Labels: size/XS, auto-merge

#3805 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3806 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3807 Automator: update common-files@release-1.13 in istio/proxy@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3808 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3809 Automator: update common-files@release-1.12 in istio/proxy@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3811 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3812 Test of update_envoy adding mobile platforms.
  WORKSPACE
  bazel/platform_mappings
  envoy.bazelrc
Labels: size/M

#3813 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3810 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3815 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#3814 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3816 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3817 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#3818 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#3819 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3822 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3821 [release-1.14] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#3824 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3823 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3825 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3826 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/M, auto-merge, release-notes-none

#3827 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#3829 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3830 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3831 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/S, auto-merge, release-notes-none

#3832 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3833 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3835 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3834 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3836 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3837 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#3838 Automator: update envoy@ in istio/proxy@release-1.14
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#3839 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3841 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3842 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge
