Repository istio/proxy, pull requests merged in 2022-07, with the labels that each got.

#3917 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3918 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3919 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3922 tests: deflake
  README.md
  test/envoye2e/env/inventory.go
  test/envoye2e/inventory.go
Labels: size/L

#3921 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3923 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3924 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3925 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3926 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3927 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3928 release: make flags configurable
  Makefile.core.mk
Labels: size/XS, cherrypick/release-1.14

#3929 [release-1.14] release: make flags configurable
  Makefile.core.mk
Labels: size/XS, release-notes-none

#3930 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#3931 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3932 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3934 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3933 release: allow publishing without check
  scripts/release-binary.sh
Labels: size/XS

#3936 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3938 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3937 release: fixed missed location for `${ARCH_SUFFIX}`
  scripts/release-binary.sh
Labels: size/XS

#3940 Update Envoy SHA to latest.
  WORKSPACE
Labels: size/XS

#3941 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3942 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3943 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#3945 Automator: update common-files@release-1.13 in istio/proxy@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3946 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3949 Automator: update envoy@ in istio/proxy@release-1.14
  WORKSPACE
Labels: size/XS, auto-merge

#3947 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3950 deps: update envoy manually
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
  src/istio/authn/BUILD
Labels: size/XS

#3952 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3951 Automator: update envoy@ in istio/proxy@master
  .bazelversion
  WORKSPACE
Labels: size/XS, auto-merge

#3954 Fix linter errors in go code
  common/.commonfiles.sha
  common/config/.golangci.yml
  test/envoye2e/driver/resource.go
  test/envoye2e/driver/scenario.go
  test/envoye2e/http_metadata_exchange/exchange_test.go
  test/envoye2e/stackdriver_plugin/fake_stackdriver.go
  test/envoye2e/stackdriver_plugin/stackdriver.go
Labels: size/M

#3955 Automator: update common-files@release-1.13 in istio/proxy@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3956 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3957 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#3958 deflake: run asan/tsan integration tests sequentially
  Makefile.core.mk
Labels: size/XS

#3959 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3961 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3963 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3964 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3965 [release-1.14] Fix return value
  extensions/common/context.cc
Labels: size/XS

#3960 fix lint
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  test/envoye2e/driver/envoy.go
Labels: size/S

#3962 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3966 [release-1.13] Fix return value
  extensions/common/context.cc
Labels: size/XS

#3967 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3968 Automator: update envoy@ in istio/proxy@master
  .bazelversion
  WORKSPACE
Labels: size/XS, auto-merge

#3970 Automator: update envoy@ in istio/proxy@release-1.14
  WORKSPACE
Labels: size/XS, auto-merge

#3973 Remove the extra return line
  extensions/common/context.cc
Labels: size/XS

#3974 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3972 Remove the extra return line
  extensions/common/context.cc
Labels: size/XS

#3969 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3971 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3975 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3976 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3978 Automator: update envoy@ in istio/proxy@release-1.14
  WORKSPACE
Labels: size/XS, auto-merge

#3979 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge
