Repository istio/proxy, pull requests merged in 2022-03, with the labels that each got.

#3740 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3741 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3742 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3743 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3751 Automator: update common-files@release-1.11 in istio/proxy@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3750 Automator: update common-files@release-1.12 in istio/proxy@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3749 Automator: update common-files@release-1.13 in istio/proxy@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3754 Automator: update envoy@ in istio/proxy@release-1.11
  WORKSPACE
Labels: size/XS, auto-merge

#3755 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3744 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#3753 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3748 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3756 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3752 Enable CryptoMB PrivateKeyProvider extension
  bazel/extension_config/extensions_build_config.bzl
Labels: ok-to-test, size/XS

#3758 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3759 Automator: update envoy@ in istio/proxy@release-1.11
  WORKSPACE
Labels: size/XS, auto-merge

#3760 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3761 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3762 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3763 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3764 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3766 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#3765 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3767 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#3768 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#3769 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#3770 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3773 Pass shellcheck 0.8 linter
  prow/proxy-postsubmit-centos.sh
  prow/proxy-postsubmit.sh
  prow/proxy-presubmit-asan.sh
  prow/proxy-presubmit-centos-release.sh
  prow/proxy-presubmit-release.sh
  prow/proxy-presubmit-tsan.sh
  prow/proxy-presubmit-wasm.sh
  prow/proxy-presubmit.sh
  scripts/push-debian.sh
Labels: size/S

#3772 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#3774 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3775 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3771 stackdriver: add support for generic_node MR
  extensions/common/context.cc
  extensions/common/node_info.fbs
  extensions/common/proto_util.cc
  extensions/common/proto_util_test.cc
  extensions/stackdriver/common/constants.h
  extensions/stackdriver/common/utils.cc
  extensions/stackdriver/log/logger.cc
  extensions/stackdriver/metric/registry.cc
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/generic_client_node_metadata.json.tmpl
  testdata/generic_server_node_metadata.json.tmpl
  testdata/stackdriver/generic_client_request_count.yaml.tmpl
  testdata/stackdriver/generic_server_request_count.yaml.tmpl
Labels: size/L

#3778 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3780 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#3779 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/L, auto-merge, release-notes-none

#3782 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3781 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3784 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3786 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3788 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3789 Manual update of common-files for proxy
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS

#3785 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3790 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3787 Fix file name in wasm image.
  Makefile.core.mk
  bazel/wasm.bzl
  extensions/BUILD
  test/envoye2e/inventory.go
Labels: size/S

#3792 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3791 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3793 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3794 Automator: update envoy@ in istio/proxy@release-1.11
  WORKSPACE
Labels: size/XS, auto-merge

#3797 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
