Repository istio/proxy, pull requests merged in 2022-06, with the labels that each got.

#3869 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#3872 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3875 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3873 Automator: update envoy@ in istio/proxy@release-1.14
  WORKSPACE
Labels: size/XS, auto-merge

#3871 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3878 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3879 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3881 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3880 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3883 Automator: update envoy@ in istio/proxy@release-1.14
  WORKSPACE
Labels: size/XS, auto-merge

#3882 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3870 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#3884 build: attempt to fix 1.14 proxy build
  .bazelrc
Labels: size/XS

#3885 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3886 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3887 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3888 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3889 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3891 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3890 Initial support for multi-architecture builds
  scripts/release-binary.sh
Labels: size/S

#3893 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3894 Automator: update envoy@ in istio/proxy@release-1.14
  WORKSPACE
Labels: size/XS, auto-merge

#3895 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3897 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3898 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#3899 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3896 Update Envoy and change dynamo filter to contrib
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
Labels: size/S

#3901 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3903 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3892 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3906 codeowners: switch default to policies and telemetry maintainers
  CODEOWNERS
Labels: size/XS

#3907 context: skip missing peer info
  extensions/common/context.cc
Labels: size/XS

#3909 Automator: update common-files@release-1.14 in istio/proxy@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3910 Automator: update common-files@release-1.13 in istio/proxy@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3908 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3911 Automator: update common-files@release-1.12 in istio/proxy@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3912 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3914 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#3913 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge
