Repository istio/proxy, pull requests merged in 2022-02, with the labels that each got.

#3688 Automator: update envoy@ in istio/proxy@master
  .bazelversion
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#3690 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3691 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3692 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3693 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3694 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3695 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3696 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3697 Automator: update common-files@release-1.12 in istio/proxy@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3698 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#3699 Update Envoy SHA to latest with Bazel rules for V8.
  Makefile.core.mk
  WORKSPACE
  envoy.bazelrc
  scripts/push-debian.sh
  scripts/release-binary.sh
  tools/deb/test/build_docker.sh
Labels: size/S

#3700 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3703 [release-1.13] Update to fix lint-go when using new common-files updates
  test/envoye2e/basic_flow/basic_test.go
  test/envoye2e/driver/envoy.go
  test/envoye2e/driver/xds.go
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  test/envoye2e/stackdriver_plugin/sts.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/testdata.gen.go
  tools/extensionserver/server.go
Labels: size/L, release-notes-none

#3702 Automator: update common-files@release-1.13 in istio/proxy@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3705 Automator: update common-files@release-1.13 in istio/proxy@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#3706 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3707 Fix build breakage
  WORKSPACE
  extensions/attributegen/plugin_test.cc
  extensions/common/proto_util_speed_test.cc
  src/envoy/http/alpn/alpn_test.cc
  src/envoy/tcp/forward_downstream_sni/forward_downstream_sni_test.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite.cc
  src/envoy/tcp/tcp_cluster_rewrite/tcp_cluster_rewrite_test.cc
Labels: size/S

#3709 Automator: update common-files@release-1.11 in istio/proxy@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3704 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#3711 deps: remove NOT_REACHED_GCOVR_EXCL_LINE
  WORKSPACE
  src/envoy/http/authn/authenticator_base.cc
Labels: size/XS

#3689 [master] extensions: sync full envoy extension list with envoy release 1.21
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, release-notes-none

#3713 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3714 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3715 Automator: update envoy@ in istio/proxy@release-1.11
  WORKSPACE
Labels: size/XS, auto-merge

#3718 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3719 Automator: update envoy@ in istio/proxy@release-1.11
  WORKSPACE
Labels: size/XS, auto-merge

#3717 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3724 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3723 Automator: update envoy@ in istio/proxy@release-1.11
  WORKSPACE
Labels: size/XS, auto-merge

#3722 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3726 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3727 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3712 enable sip_proxy extension
  bazel/extension_config/extensions_build_config.bzl
Labels: ok-to-test, size/XS

#3729 Automator: update envoy@ in istio/proxy@release-1.11
  WORKSPACE
Labels: size/XS, auto-merge

#3730 Automator: update envoy@ in istio/proxy@release-1.13
  WORKSPACE
Labels: size/XS, auto-merge

#3728 Automator: update envoy@ in istio/proxy@release-1.12
  WORKSPACE
Labels: size/XS, auto-merge

#3731 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3732 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3733 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/M, auto-merge, release-notes-none

#3720 Push Wasm extensions as OCI image at postsubmit.
  Makefile.core.mk
  bazel/wasm.bzl
  extensions/BUILD
  scripts/release-binary.sh
  tools/bazel_get_workspace_status
Labels: size/M

#3721 Use RBE when prow runs with workload identity.
  prow/proxy-common.inc
Labels: size/S

#3736 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#3737 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#3735 Fix Wasm image push postsubmit.
  scripts/release-binary.sh
Labels: size/XS

#3739 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3738 Automator: update common-files@release-1.12 in istio/proxy@release-1.12
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none
