Repository istio/proxy, pull requests merged in 2023-02, with the labels that each got.

#4398 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4399 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4400 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4401 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4402 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4403 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4404 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4405 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4407 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4408 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4409 connect: prefer endpoint metadata
  source/extensions/filters/listener/set_internal_dst_address/filter.cc
Labels: size/M

#4411 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4414 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#4412 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4413 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4415 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4416 Manually update envoy
  WORKSPACE
  envoy.bazelrc
  source/extensions/filters/network/metadata_exchange/metadata_exchange_test.cc
  source/extensions/filters/network/sni_verifier/sni_verifier_test.cc
Labels: size/S

#4417 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4418 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4419 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4420 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4421 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4422 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4423 connect_authority: always hash shared state
  source/extensions/filters/http/connect_authority/BUILD
  source/extensions/filters/http/connect_authority/config.proto
  source/extensions/filters/http/connect_authority/filter.cc
  source/extensions/filters/http/connect_authority/filter.h
  source/extensions/filters/listener/set_internal_dst_address/BUILD
  source/extensions/filters/listener/set_internal_dst_address/filter.cc
  source/extensions/filters/listener/set_internal_dst_address/filter.h
  source/extensions/filters/network/istio_authn/config.cc
  test/envoye2e/basic_flow/basic_test.go
  testdata/cluster/tcp_passthrough.yaml.tmpl
  testdata/listener/client_passthrough.yaml.tmpl
  testdata/listener/tcp_passthrough.yaml.tmpl
Labels: size/L

#4424 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4425 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4426 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4428 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4429 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4430 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4432 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#4433 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4431 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4434 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4435 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4436 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4438 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4437 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4439 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4440 Automator: update common-files@release-1.15 in istio/proxy@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4441 Point to upstream Envoy docs for build instructions
  CONTRIBUTING.md
Labels: size/XS

#4442 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4444 connect_baggage: hash peer baggage
  source/extensions/filters/http/connect_baggage/filter.cc
Labels: size/S

#4445 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4443 istio_authn: only share for tunneling
  source/extensions/filters/network/istio_authn/config.cc
  source/extensions/filters/network/istio_authn/config.h
  source/extensions/filters/network/istio_authn/config.proto
  source/extensions/filters/network/istio_authn/config_test.cc
  testdata/listener/terminate_connect.yaml.tmpl
Labels: size/M, cherrypick/release-1.17

#4446 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4448 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4449 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4450 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4451 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4452 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#4447 manual cherrypick of #4443
  source/extensions/filters/network/istio_authn/config.cc
  source/extensions/filters/network/istio_authn/config.h
  source/extensions/filters/network/istio_authn/config.proto
  source/extensions/filters/network/istio_authn/config_test.cc
  testdata/listener/terminate_connect.yaml.tmpl
Labels: size/M

#4454 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4453 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4456 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4457 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4455 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4458 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4459 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4460 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4461 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4462 wasm: remove stats and attributegen from the tree
  BUILD
  Makefile.core.mk
  extensions/BUILD
  extensions/attributegen/.gitignore
  extensions/attributegen/BUILD
  extensions/attributegen/config.pb.html
  extensions/attributegen/config.proto
  extensions/attributegen/plugin.cc
  extensions/attributegen/plugin.h
  extensions/attributegen/plugin_test.cc
  extensions/attributegen/testdata/BUILD
  extensions/attributegen/testdata/operation.json
  extensions/attributegen/testdata/responseCode.json
  extensions/attributegen/testdata/server.yaml
  extensions/stats/BUILD
  extensions/stats/config.pb.html
  extensions/stats/plugin.cc
  extensions/stats/plugin.h
  extensions/stats/plugin_test.cc
  extensions/stats/run_test.sh
  extensions/stats/testdata/client.yaml
  extensions/stats/testdata/istio/metadata-exchange_filter.yaml
  extensions/stats/testdata/istio/stats_filter.yaml
  extensions/stats/testdata/server.yaml
  source/extensions/common/BUILD
  source/extensions/filters/http/authn/BUILD
  source/extensions/filters/http/istio_stats/BUILD
  source/extensions/filters/http/istio_stats/config.proto
  source/extensions/filters/http/istio_stats/istio_stats.h
  test/envoye2e/env/utils.go
  test/envoye2e/env/wasm.go
  test/envoye2e/inventory.go
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  test/envoye2e/stats_plugin/stats_test.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  testdata/filters/attributegen.yaml.tmpl
Labels: size/XXL

#4465 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4466 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4467 fix
  scripts/release-binary.sh
Labels: size/XS

#4463 enable http golang filter extension.
  bazel/extension_config/extensions_build_config.bzl
Labels: ok-to-test, size/XS

#4468 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4469 make: use bazel info bin path for exportcache
  Makefile.core.mk
Labels: ok-to-test, size/XS

#4471 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4472 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4473 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#4474 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4476 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4255 waypoint: metadata discovery service client
  BUILD
  go.mod
  go.sum
  source/extensions/common/workload_discovery/BUILD
  source/extensions/common/workload_discovery/api.cc
  source/extensions/common/workload_discovery/api.h
  source/extensions/common/workload_discovery/discovery.proto
  source/extensions/common/workload_discovery/extension.proto
  source/extensions/filters/http/istio_stats/BUILD
  source/extensions/filters/http/istio_stats/istio_stats.cc
  test/envoye2e/driver/xds.go
  test/envoye2e/stats_plugin/stats_test.go
  test/envoye2e/workloadapi/discovery.pb.go
  testdata/bootstrap/server.yaml.tmpl
Labels: size/XL, lifecycle/automatically-closed

#4475 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4477 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4478 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge
