Repository istio/proxy, pull requests merged in 2023-06, with the labels that each got.

#4695 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4697 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4696 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4699 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4700 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#4701 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4698 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4702 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#4703 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4706 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4704 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4705 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4691 update workload api to use repeated addresses
  source/extensions/common/workload_discovery/api.cc
  source/extensions/common/workload_discovery/discovery.proto
  test/envoye2e/driver/xds.go
  test/envoye2e/stats_plugin/stats_test.go
  test/envoye2e/workloadapi/discovery.pb.go
Labels: size/L

#4707 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4708 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4709 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4710 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#4713 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#4712 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4711 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4714 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#4715 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4716 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#4717 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4719 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#4721 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#4722 Add proxy_version label to SD metrics
  extensions/stackdriver/metric/record.cc
  extensions/stackdriver/metric/registry.cc
  extensions/stackdriver/metric/registry.h
  testdata/stackdriver/client_request_count.yaml.tmpl
  testdata/stackdriver/client_tcp_connection_count.yaml.tmpl
  testdata/stackdriver/client_tcp_received_bytes_count.yaml.tmpl
  testdata/stackdriver/gce_client_request_count.yaml.tmpl
  testdata/stackdriver/gce_server_request_count.yaml.tmpl
  testdata/stackdriver/generic_client_request_count.yaml.tmpl
  testdata/stackdriver/generic_server_request_count.yaml.tmpl
  testdata/stackdriver/server_request_count.yaml.tmpl
  testdata/stackdriver/server_request_count_source_unknown.yaml.tmpl
  testdata/stackdriver/server_tcp_connection_count.yaml.tmpl
  testdata/stackdriver/server_tcp_received_bytes_count.yaml.tmpl
Labels: ok-to-test, size/S

#4724 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4725 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#4726 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#4729 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#4731 fix ARM format script
  Makefile.core.mk
  extensions/BUILD
  scripts/check-style.sh
Labels: size/M

#4732 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4733 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4727 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4735 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#4734 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#4737 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4736 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4738 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4739 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4741 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4742 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4743 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#4744 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#4746 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4748 Cleanup obsolete image pushing
  Makefile.core.mk
  bazel/bazel_get_workspace_status
  bazel/wasm.bzl
  extensions/BUILD
  scripts/release-binary.sh
Labels: size/M, cherrypick/release-1.18

#4750 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4745 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4752 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4753 Remove extraneous release-binary option
  Makefile.core.mk
  scripts/release-binary.sh
Labels: size/XS

#4754 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4755 enable network golang filter extension
  bazel/extension_config/extensions_build_config.bzl
Labels: ok-to-test, size/XS

#4757 infra: allow better proxy override
  prow/proxy-common.inc
Labels: size/S, cherrypick/release-1.16, cherrypick/release-1.17, cherrypick/release-1.18

#4761 [release-1.18] infra: allow better proxy override
  prow/proxy-common.inc
Labels: size/S, release-notes-none

#4760 [release-1.17] infra: allow better proxy override
  prow/proxy-common.inc
Labels: size/S, release-notes-none

#4749 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4759 [release-1.16] infra: allow better proxy override
  prow/proxy-common.inc
Labels: size/S, release-notes-none

#4762 build: fix RBE enablement
  prow/proxy-common.inc
Labels: size/M, release-notes-none, cherrypick/release-1.16, cherrypick/release-1.17, cherrypick/release-1.18

#4768 Disable CPU limit
  prow/proxy-common.inc
Labels: size/XS, release-notes-none, cherrypick/release-1.16, cherrypick/release-1.17, cherrypick/release-1.18

#4767 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge
