Repository istio/proxy, pull requests merged in 2023-11, with the labels that each got.

#5112 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#5111 sync with upstream
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
  envoy.bazelrc
Labels: size/M

#5113 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5117 move extension check to postsubmit
  scripts/check-style.sh
  scripts/release-binary.sh
Labels: size/M

#5118 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5119 rollback to 1029
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
  envoy.bazelrc
Labels: size/S

#5120 rollback to 10-27
  WORKSPACE
  envoy.bazelrc
Labels: size/XS

#5116 update envoy with specified SHA
  scripts/update_envoy.sh
Labels: size/XS

#5122 rollback 1025
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
Labels: size/S

#5124 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5123 update to 10-26
  WORKSPACE
Labels: size/XS

#5126 debug: continue bisecting to 10-25
  WORKSPACE
Labels: size/XS

#5127 debug: continue bisecting
  WORKSPACE
Labels: size/XS

#5128 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5125 fix postsubmit job and update to latest
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
  envoy.bazelrc
  scripts/update_envoy.sh
Labels: size/M

#5129 build: fix minor compilation and compliance issues
  BUILD
  extensions/access_log_policy/BUILD
  extensions/access_log_policy/config/v1alpha1/BUILD
  extensions/common/BUILD
  extensions/common/wasm/json_util.cc
  extensions/stackdriver/BUILD
  extensions/stackdriver/common/BUILD
  extensions/stackdriver/config/v1alpha1/BUILD
  extensions/stackdriver/log/BUILD
  extensions/stackdriver/metric/BUILD
  source/extensions/common/BUILD
  source/extensions/common/workload_discovery/BUILD
  source/extensions/filters/http/alpn/BUILD
  source/extensions/filters/http/authn/BUILD
  source/extensions/filters/http/istio_stats/BUILD
  source/extensions/filters/http/peer_metadata/BUILD
  source/extensions/filters/network/metadata_exchange/BUILD
  source/extensions/filters/network/metadata_exchange/config/BUILD
  src/istio/authn/BUILD
  src/istio/utils/BUILD
  test/integration/BUILD
Labels: size/L

#5115 code cleanup: remove vestiges of baggage header, and fix delta xDS for WDS
  source/extensions/common/workload_discovery/api.cc
  source/extensions/filters/http/peer_metadata/config.proto
  source/extensions/filters/http/peer_metadata/filter.cc
  source/extensions/filters/http/peer_metadata/filter.h
  source/extensions/filters/http/peer_metadata/filter_test.cc
  test/envoye2e/driver/xds.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/listener/internal_outbound.yaml.tmpl
  testdata/listener/terminate_connect.yaml.tmpl
Labels: size/L

#5130 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5131 test revert
  WORKSPACE
  external/patch.diff
Labels: size/L

#5132 Automator: update common-files@release-1.19 in istio/proxy@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5136 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5137 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5138 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5139 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#5142 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5141 Update envoy
  WORKSPACE
  external/patch.diff
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/L

#5144 enable grpc_field_extraction filter
  bazel/extension_config/extensions_build_config.bzl
  tools/extension-check/wellknown-extensions
Labels: size/XS

#5143 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5146 [Release-1.20] enable grpc_field_extraction filter
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#5147 [Release-1.19] enable grpc_field_extraction filter
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#5148 build: apply buildifer recommendations
  extensions/common/BUILD
  extensions/common/wasm/BUILD
  extensions/common/wasm/base64.h
  extensions/stackdriver/common/BUILD
  extensions/stackdriver/log/BUILD
  extensions/stackdriver/metric/BUILD
  source/extensions/filters/http/peer_metadata/BUILD
Labels: size/L

#5152 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5153 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5150 use absl::StatusOr
  WORKSPACE
  source/extensions/filters/http/alpn/config.cc
  source/extensions/filters/http/alpn/config.h
  source/extensions/filters/http/alpn/config_test.cc
  source/extensions/filters/http/authn/http_filter_factory.cc
  source/extensions/filters/http/peer_metadata/filter_test.cc
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
Labels: size/S

#5155 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5151 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5156 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5157 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5158 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5159 Automator: update common-files@release-1.20 in istio/proxy@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5154 osx support
  .bazelrc
Labels: size/S

#5160 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5164 use DELTA_GRPC
  WORKSPACE
  bazel/repositories.bzl
  source/extensions/filters/http/alpn/BUILD
  source/extensions/filters/http/alpn/alpn_filter.h
  source/extensions/filters/http/alpn/config.h
  source/extensions/filters/http/alpn/config.proto
  test/envoye2e/driver/extensionserver.go
  testdata/bootstrap/client.yaml.tmpl
  testdata/bootstrap/server.yaml.tmpl
  testdata/filters/extension_config_inbound.yaml.tmpl
  testdata/filters/extension_config_outbound.yaml.tmpl
Labels: size/L

#5162 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5161 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#5165 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5166 enable TestStackdriverRbacTCPDryRun
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
Labels: size/XS

#5163 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#5167 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5170 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5169 update envoy
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#5172 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5173 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5175 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5174 Enable zstd
  bazel/extension_config/extensions_build_config.bzl
  tools/extension-check/wellknown-extensions
Labels: size/XS, cherrypick/release-1.18, cherrypick/release-1.19, cherrypick/release-1.20

#5176 stackdriver fake: use json
  test/envoye2e/stackdriver_plugin/cmd/Makefile
  test/envoye2e/stackdriver_plugin/fake_stackdriver.go
Labels: size/S, release-notes-none

#5180 [release 1.20] enable zstd
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#5177 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5179 [Release 1.19] enable zstd
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#5178 [Release 1.18] enable zstd
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#5181 build: fix proto use since they are duplicated in istio/api
  source/extensions/filters/http/alpn/BUILD
  source/extensions/filters/http/istio_stats/BUILD
  source/extensions/filters/http/istio_stats/istio_stats.cc
  source/extensions/filters/http/istio_stats/istio_stats.h
  source/extensions/filters/http/peer_metadata/BUILD
  source/extensions/filters/http/peer_metadata/filter.cc
  source/extensions/filters/http/peer_metadata/filter.h
Labels: size/L

#5182 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none
