Repository istio/proxy, pull requests merged in 2023-10, with the labels that each got.

#4980 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#4979 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4981 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4983 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none

#4985 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4984 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4982 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4987 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4986 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4989 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4990 http mx: fix regression
  source/extensions/filters/http/peer_metadata/filter.cc
  source/extensions/filters/http/peer_metadata/filter.h
  source/extensions/filters/http/peer_metadata/filter_test.cc
  test/envoye2e/http_metadata_exchange/exchange_test.go
Labels: size/L, cherrypick/release-1.19

#4993 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4994 tcp mx: implement WDS fallback
  source/extensions/common/workload_discovery/api.cc
  source/extensions/filters/network/metadata_exchange/BUILD
  source/extensions/filters/network/metadata_exchange/config.cc
  source/extensions/filters/network/metadata_exchange/config/metadata_exchange.proto
  source/extensions/filters/network/metadata_exchange/metadata_exchange.cc
  source/extensions/filters/network/metadata_exchange/metadata_exchange.h
  source/extensions/filters/network/metadata_exchange/metadata_exchange_test.cc
  test/envoye2e/inventory.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  testdata/bootstrap/client.yaml.tmpl
  testdata/cluster/tcp_client.yaml.tmpl
  testdata/filters/client_mx_network_filter.yaml.tmpl
  testdata/filters/server_mx_network_filter.yaml.tmpl
  testdata/metric/tcp_client_connection_close.yaml.tmpl
  testdata/metric/tcp_client_connection_open.yaml.tmpl
  testdata/metric/tcp_client_received_bytes.yaml.tmpl
  testdata/metric/tcp_client_sent_bytes.yaml.tmpl
  testdata/metric/tcp_server_connection_close.yaml.tmpl
  testdata/metric/tcp_server_connection_open.yaml.tmpl
  testdata/metric/tcp_server_received_bytes.yaml.tmpl
  testdata/metric/tcp_server_sent_bytes.yaml.tmpl
Labels: size/L

#4992 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4995 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#4988 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4997 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4998 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4991 http mx: fix regression (#4990)
  source/extensions/filters/http/peer_metadata/filter.cc
  source/extensions/filters/http/peer_metadata/filter.h
  source/extensions/filters/http/peer_metadata/filter_test.cc
  test/envoye2e/http_metadata_exchange/exchange_test.go
Labels: size/L

#5000 Automator: update common-files@release-1.19 in istio/proxy@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5002 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5001 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#4999 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5003 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#4996 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5004 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#5005 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#5006 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5007 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5010 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#5011 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5008 add file system http cache filter
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, cherrypick/release-1.17, cherrypick/release-1.18, cherrypick/release-1.19

#5015 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5017 Release 1.18.4 patch
  WORKSPACE
Labels: size/XS

#5019 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5021 Update golang.org/x/net and grpc-go
  go.mod
  go.sum
Labels: size/M

#5023 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5024 Automator: update common-files@release-1.19 in istio/proxy@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5026 [release-1.18] Manually update envoy to use envoyproxy
  WORKSPACE
Labels: size/XS

#5020 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#5027 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5014 [release-1.19] add file system http cache filter
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, release-notes-none

#5025 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5013 [release-1.18] add file system http cache filter
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, release-notes-none

#5030 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5031 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#5029 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#5032 replace connect authority with set_filter_state
  BUILD
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
  source/extensions/filters/http/connect_authority/BUILD
  source/extensions/filters/http/connect_authority/config.proto
  source/extensions/filters/http/connect_authority/filter.cc
  source/extensions/filters/http/connect_authority/filter.h
  testdata/listener/client_passthrough.yaml.tmpl
  testdata/listener/tcp_passthrough.yaml.tmpl
Labels: size/L

#5034 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#5033 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5035 enable connect_grpc_bridge filter
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, cherrypick/release-1.18, cherrypick/release-1.19

#5038 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5041 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5039 Add CEL formatter to build
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, release-notes-none

#5037 [release-1.19] enable connect_grpc_bridge filter
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, release-notes-none

#5042 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5040 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#5043 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5044 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#5045 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5046 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#5049 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5050 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5048 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#5052 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5053 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#5054 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#5055 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5057 [release-1.20] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#5058 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#5059 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5061 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#5062 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5063 Automator: update common-files@release-1.20 in istio/proxy@release-1.20
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#5060 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5064 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5066 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5069 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#5065 [release-1.20] Update go-control-plane
  go.mod
  go.sum
Labels: size/XS

#5068 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#5070 Automator: update common-files@release-1.20 in istio/proxy@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5072 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5071 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5067 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5073 Add envoy.resource_monitors.downstream_connections
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#5074 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5076 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5075 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5077 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5078 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#5079 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5080 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5084 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5082 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#5083 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5081 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#5088 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5087 turn previously removed BAZEL_BIN_PATH in to target-specific variable to fix exportcache builds
  Makefile.core.mk
Labels: ok-to-test, size/XS, cherrypick/release-1.19, cherrypick/release-1.20

#5090 [release-1.20] turn previously removed BAZEL_BIN_PATH in to target-specific variable to fix exportcache builds
  Makefile.core.mk
Labels: size/XS, release-notes-none

#5091 [release-1.19] turn previously removed BAZEL_BIN_PATH in to target-specific variable to fix exportcache builds
  Makefile.core.mk
Labels: size/XS, release-notes-none

#5036 [release-1.18] enable connect_grpc_bridge filter
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, release-notes-none

#5092 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5089 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5095 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#5096 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5097 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5098 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5099 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#5093 tool for checking extension build config
  go.mod
  go.sum
  scripts/check-style.sh
  tools/extension-check/README.md
  tools/extension-check/main.go
  tools/extension-check/wellknown-extensions
Labels: size/L

#5101 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#5102 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5100 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5103 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5104 fix update_envoy.sh
  scripts/update_envoy.sh
Labels: size/XS, cherrypick/release-1.18, cherrypick/release-1.19, cherrypick/release-1.20

#5107 [release-1.20] fix update_envoy.sh
  scripts/update_envoy.sh
Labels: size/XS, release-notes-none

#5105 [release-1.18] fix update_envoy.sh
  scripts/update_envoy.sh
Labels: size/XS, release-notes-none

#5106 [release-1.19] fix update_envoy.sh
  scripts/update_envoy.sh
Labels: size/XS, release-notes-none

#5110 test: use 127.0.0.3 for backend
  test/envoye2e/driver/tcp.go
  test/envoye2e/env/grpc.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/bootstrap/server.yaml.tmpl
  testdata/cluster/tcp_server.yaml.tmpl
Labels: size/S

#5109 Automator: update common-files@master in istio/proxy@master
  LICENSE
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
