Repository istio/proxy, pull requests merged in 2023-05, with the labels that each got.

#4630 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4629 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4628 Fix sha used in go-control-plane for release-1.18
  go.mod
  go.sum
Labels: size/XS

#4633 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4636 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4635 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4634 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4637 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#4638 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4624 [release-1.18] stats: fix destination service name for service entries
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/XS, release-notes-none

#4639 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4640 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4641 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4643 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4644 stats: fix concurrent config write race for custom metrics
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/L, cherrypick/release-1.18

#4646 [release-1.18] stats: fix concurrent config write race for custom metrics
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/L, release-notes-none

#4619 [release-1.18] stats: implement metric expiry
  source/extensions/filters/http/istio_stats/config.proto
  source/extensions/filters/http/istio_stats/istio_stats.cc
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/stats/client_config_expiry.yaml
Labels: size/L, release-notes-none

#4645 manual cherry pick of https://github.com/istio/proxy/pull/4644
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/L

#4642 fix build
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
  envoy.bazelrc
Labels: size/S

#4647 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4648 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#4649 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4650 add missing lb extensions
  bazel/extension_config/extensions_build_config.bzl
Labels: size/S

#4653 [CNCF graduation] Add security tab for Istio repos
  .github/SECURITY.md
Labels: size/XS

#4652 update envoy & fix python tool chain
  .bazelversion
  WORKSPACE
Labels: size/S

#4654 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4655 Automator: update envoy@ in istio/proxy@master
  .bazelversion
  WORKSPACE
Labels: size/XS, auto-merge

#4656 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4657 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4658 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#4659 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4660 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4662 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4661 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4663 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4664 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4665 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4668 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4667 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4666 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4669 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4670 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#4672 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4677 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#4676 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#4671 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4678 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4679 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4680 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#4674 updates to workload API per design doc
  source/extensions/common/workload_discovery/api.cc
  source/extensions/common/workload_discovery/discovery.proto
  test/envoye2e/driver/xds.go
  test/envoye2e/workloadapi/discovery.pb.go
Labels: size/L

#4682 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4683 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4684 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4685 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4687 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4688 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4690 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4692 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4694 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge
