Repository istio/proxy, pull requests merged in 2023-08, with the labels that each got.

#4850 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4783 Skip alpn rewrite if alpnOverride filter metadata is false
  source/extensions/filters/http/alpn/alpn_filter.cc
  source/extensions/filters/http/alpn/alpn_test.cc
Labels: size/M

#4849 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4853 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4856 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4861 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4855 sync health_checkers extensions
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, cherrypick/release-1.18, cherrypick/release-1.19

#4860 [release-1.19] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#4864 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4862 [release-1.18] sync health_checkers extensions
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, release-notes-none

#4863 [release-1.19] sync health_checkers extensions
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS, release-notes-none

#4866 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4867 Automator: update common-files@release-1.19 in istio/proxy@release-1.19
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4868 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4865 Fix skipping ALPN overwriting
  source/extensions/filters/http/alpn/alpn_filter.cc
  source/extensions/filters/http/alpn/alpn_test.cc
Labels: size/M

#4869 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4870 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#4871 config subscription bazel settings
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#4873 Automator: update common-files@release-1.19 in istio/proxy@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4874 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/M, auto-merge

#4875 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4876 metadata exchange: fix cache data race
  source/extensions/filters/http/peer_metadata/config.proto
  source/extensions/filters/http/peer_metadata/filter.cc
  source/extensions/filters/http/peer_metadata/filter.h
  source/extensions/filters/http/peer_metadata/filter_test.cc
  test/envoye2e/driver/check.go
  test/envoye2e/http_metadata_exchange/exchange_test.go
  test/envoye2e/inventory.go
Labels: size/L

#4872 Use go-control-plane from last 1.27 cut
  go.mod
  go.sum
Labels: size/XS

#4877 [release-1.19] metadata exchange: fix cache data race
  source/extensions/filters/http/peer_metadata/config.proto
  source/extensions/filters/http/peer_metadata/filter.cc
  source/extensions/filters/http/peer_metadata/filter.h
  source/extensions/filters/http/peer_metadata/filter_test.cc
  test/envoye2e/driver/check.go
  test/envoye2e/http_metadata_exchange/exchange_test.go
  test/envoye2e/inventory.go
Labels: size/L, release-notes-none

#4835 metadata_exchange: stop waiting for data when upstream closes
  source/extensions/filters/network/metadata_exchange/metadata_exchange.cc
  test/envoye2e/driver/tcp.go
  test/envoye2e/inventory.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: ok-to-test, size/L

#4879 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4884 Automator: update common-files@release-1.19 in istio/proxy@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4883 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4882 manual backport https://github.com/istio/proxy/pull/4835
  source/extensions/filters/network/metadata_exchange/metadata_exchange.cc
  test/envoye2e/driver/tcp.go
  test/envoye2e/inventory.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: size/L

#4880 [release-1.19] metadata_exchange: stop waiting for data when upstream closes
  source/extensions/filters/network/metadata_exchange/metadata_exchange.cc
  test/envoye2e/driver/tcp.go
  test/envoye2e/inventory.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
Labels: size/L, release-notes-none

#4885 metadata_exchange: fix layered TCP/HTTP write conflict
  extensions/common/context.cc
  extensions/common/context.h
  source/extensions/filters/http/istio_stats/istio_stats.cc
  source/extensions/filters/http/peer_metadata/filter.cc
  source/extensions/filters/http/peer_metadata/filter.h
  source/extensions/filters/network/metadata_exchange/metadata_exchange.cc
  test/envoye2e/http_metadata_exchange/exchange_test.go
  testdata/metric/envoy_bug_failures.yaml
Labels: size/M

#4887 [release-1.19] metadata_exchange: fix layered TCP/HTTP write conflict
  extensions/common/context.cc
  extensions/common/context.h
  source/extensions/filters/http/istio_stats/istio_stats.cc
  source/extensions/filters/http/peer_metadata/filter.cc
  source/extensions/filters/http/peer_metadata/filter.h
  source/extensions/filters/network/metadata_exchange/metadata_exchange.cc
  test/envoye2e/http_metadata_exchange/exchange_test.go
  testdata/metric/envoy_bug_failures.yaml
Labels: size/M, release-notes-none

#4886 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#4890 [release-1.19] Fix skipping ALPN overwriting
  source/extensions/filters/http/alpn/alpn_filter.cc
  source/extensions/filters/http/alpn/alpn_test.cc
Labels: size/M, release-notes-none

#4891 build: remove wasm metadata exchange
  BUILD
  Makefile.core.mk
  extensions/BUILD
  extensions/metadata_exchange/BUILD
  extensions/metadata_exchange/config.cc
  extensions/metadata_exchange/config.pb.html
  extensions/metadata_exchange/config.proto
  extensions/metadata_exchange/declare_property.pb.html
  extensions/metadata_exchange/declare_property.proto
  extensions/metadata_exchange/plugin.cc
  extensions/metadata_exchange/plugin.h
  scripts/release-binary.sh
  test/envoye2e/http_metadata_exchange/exchange_test.go
  test/envoye2e/otel/otel_test.go
  testdata/filters/mx_inbound.yaml.tmpl
  testdata/filters/mx_outbound.yaml.tmpl
Labels: size/XL

#4892 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#4894 build: fix envoy build
  .bazelversion
  Makefile.core.mk
  WORKSPACE
  envoy.bazelrc
  extensions/common/BUILD
  scripts/release-binary.sh
Labels: size/M

#4896 Update dependencies for proxy
  go.mod
  go.sum
Labels: size/M

#4897 Automator: update envoy@ in istio/proxy@master
  .bazelversion
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#4898 Automator: update common-files@release-1.19 in istio/proxy@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4893 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4899 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4901 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#4900 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4902 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#4904 test: use 127.0.0.2 for server IP to support WDS lookup
  test/envoye2e/basic_flow/basic_test.go
  test/envoye2e/driver/check.go
  test/envoye2e/http_metadata_exchange/exchange_test.go
  test/envoye2e/stackdriver_plugin/stackdriver_test.go
  testdata/bootstrap/client.yaml.tmpl
  testdata/cluster/internal_outbound.yaml.tmpl
  testdata/cluster/server.yaml.tmpl
  testdata/cluster/tcp_client.yaml.tmpl
  testdata/listener/server.yaml.tmpl
  testdata/listener/tcp_server.yaml.tmpl
  testdata/listener/terminate_connect.yaml.tmpl
  testdata/metric/basic_flow_server_requests.yaml.tmpl
  testdata/stackdriver/gateway_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_audit_log_entry.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry.yaml.tmpl
  testdata/stackdriver/server_tcp_access_log_entry_on_open.yaml.tmpl
  testdata/stackdriver/utf8_server_access_log_entry.yaml.tmpl
Labels: size/M

#4903 Automator: update envoy@ in istio/proxy@release-1.19
  .bazelversion
  WORKSPACE
  envoy.bazelrc
Labels: size/L, auto-merge

#4906 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#4907 istio_stats: cleanup fallback
  source/extensions/filters/http/istio_stats/istio_stats.cc
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  testdata/filters/server_authn_network_filter.yaml.tmpl
Labels: size/S

#4909 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4908 Automator: update envoy@ in istio/proxy@release-1.18
  .bazelversion
  WORKSPACE
  envoy.bazelrc
Labels: size/L, auto-merge

#4911 wds: backfill app name and app version
  source/extensions/common/workload_discovery/api.cc
Labels: size/XS

#4912 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#4913 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#4915 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4916 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4914 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#4917 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#4918 fix envoy build
  WORKSPACE
  source/extensions/filters/network/metadata_exchange/config.cc
  source/extensions/filters/network/metadata_exchange/config.h
Labels: size/S

#4895 do not send mx headers for services out of mesh
  source/extensions/filters/http/peer_metadata/config.proto
  source/extensions/filters/http/peer_metadata/filter.cc
  source/extensions/filters/http/peer_metadata/filter.h
  source/extensions/filters/http/peer_metadata/filter_test.cc
Labels: size/L

#4919 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4920 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4922 configure sanitized build
  .bazelrc
  .devcontainer/devcontainer.json
  Makefile.core.mk
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  scripts/check-style.sh
  scripts/release-binary.sh
Labels: size/M

#4925 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4927 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
