Repository istio/proxy, pull requests merged in 2023-03, with the labels that each got.

#4479 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4480 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4482 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4483 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#4481 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4484 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4486 Automator: update common-files@master in istio/proxy@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#4487 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4485 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4488 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4489 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4490 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4491 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4492 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4493 Run update_deps equivalent to get latest go_control_plane
  go.mod
  go.sum
Labels: size/L

#4494 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4496 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4498 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4500 Automator: update common-files@release-1.15 in istio/proxy@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4499 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4497 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4501 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#4502 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4504 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4506 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4508 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4507 Automator: update go dependencies@ in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#4509 Automator: update envoy@ in istio/proxy@master
  .bazelversion
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4510 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4511 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4514 Automator: update common-files@release-1.15 in istio/proxy@release-1.15
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#4513 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4516 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#4515 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#4512 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/M, auto-merge, release-notes-none

#4517 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4518 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4520 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4519 algin tcp_reporting_duration default value
  source/extensions/filters/http/istio_stats/config.proto
Labels: size/XS, cherrypick/release-1.17

#4521 update envoy and workload proto
  bazel/extension_config/extensions_build_config.bzl
  source/extensions/common/workload_discovery/api.cc
  source/extensions/common/workload_discovery/discovery.proto
Labels: size/M

#4523 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4524 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4526 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4525 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4527 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4529 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#4530 Automator: update common-files@release-1.15 in istio/proxy@release-1.15
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#4531 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#4522 [release-1.17] algin tcp_reporting_duration default value
  extensions/stats/config.proto
Labels: size/XS, release-notes-none

#4533 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4528 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4534 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4532 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4536 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4537 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4540 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4539 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4541 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4542 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: size/L, auto-merge, release-notes-none

#4543 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4544 Try and fix erorrs with updated Envoy
  WORKSPACE
  envoy.bazelrc
  source/extensions/filters/http/authn/http_filter_integration_test.cc
  test/integration/exchanged_token_integration_test.cc
  test/integration/istio_http_integration_test_with_envoy_jwt_filter.cc
Labels: size/S

#4547 stats: implement grpc message counts
  source/extensions/filters/http/istio_stats/BUILD
  source/extensions/filters/http/istio_stats/istio_stats.cc
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
Labels: size/L
