Repository istio/proxy, pull requests merged in 2023-01, with the labels that each got.

#4307 workload-env-default
  prow/proxy-common.inc
Labels: size/XS

#4309 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4310 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#4308 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4313 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4314 Update Envoy
  .bazelversion
  WORKSPACE
  bazel/repositories.bzl
  envoy.bazelrc
Labels: size/S

#4316 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4317 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4319 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4321 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4320 enable DLB connection balance extension
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#4322 telemetry: propagate downstream peer from baggage
  BUILD
  source/extensions/filters/http/connect_baggage/BUILD
  source/extensions/filters/http/connect_baggage/config.proto
  source/extensions/filters/http/connect_baggage/filter.cc
  source/extensions/filters/http/connect_baggage/filter.h
  testdata/listener/internal_outbound.yaml.tmpl
  testdata/listener/terminate_connect.yaml.tmpl
  testdata/metric/server_waypoint_proxy_connect_request_total.yaml.tmpl
Labels: size/L

#4323 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4324 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4326 baggage: allow propagation
  source/extensions/filters/http/connect_baggage/config.proto
  source/extensions/filters/http/connect_baggage/filter.cc
  source/extensions/filters/http/connect_baggage/filter.h
Labels: size/M

#4325 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4327 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4329 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4330 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#4331 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4332 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4333 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4334 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4337 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4336 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4338 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4343 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4346 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4347 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4351 [release-1.17] Automated branch step4
  CODEOWNERS
Labels: size/XS, release-notes-none

#4350 [release-1.17] Fix branch for common_files
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS

#4352 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4349 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4354 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4361 stats: fix issue with customization
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/M, cherrypick/release-1.17

#4362 [release-1.17] stats: fix issue with customization
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/M, release-notes-none

#4363 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4365 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4366 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4367 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4369 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4374 Automator: update common-files@release-1.15 in istio/proxy@release-1.15
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#4370 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4372 [release-1.16] update envoy + manual cherry pick of #4286
  WORKSPACE
  extensions/stats/config.proto
  source/extensions/filters/http/istio_stats/istio_stats.cc
  source/extensions/filters/network/sni_verifier/sni_verifier_test.cc
  test/envoye2e/stats_plugin/stats_test.go
  testdata/stats/client_config_customized.yaml.tmpl
Labels: size/L

#4379 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4380 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4378 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#4382 connect: undo some changes https://github.com/istio/proxy/pull/4377
  source/extensions/filters/http/connect_authority/config.proto
  source/extensions/filters/http/connect_authority/filter.cc
  source/extensions/filters/http/connect_authority/filter.h
  source/extensions/filters/listener/set_internal_dst_address/filter.cc
  source/extensions/filters/listener/set_internal_dst_address/filter.h
  testdata/cluster/internal_outbound.yaml.tmpl
  testdata/cluster/original_dst.yaml.tmpl
  testdata/listener/client_passthrough.yaml.tmpl
Labels: size/M

#4384 Automator: update common-files@release-1.15 in istio/proxy@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4385 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#4386 connect: simplify extensions
  source/extensions/filters/http/connect_authority/filter.cc
  source/extensions/filters/http/connect_baggage/config.proto
  source/extensions/filters/http/connect_baggage/filter.cc
  source/extensions/filters/http/connect_baggage/filter.h
  source/extensions/filters/network/istio_authn/config.cc
Labels: size/M

#4373 StatefulSession: include HeaderBasedSessionState extension
  bazel/extension_config/extensions_build_config.bzl
Labels: ok-to-test, size/XS

#4388 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4390 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#4391 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4392 Automator: update envoy@ in istio/proxy@release-1.15
  WORKSPACE
Labels: size/XS, auto-merge

#4393 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4396 connect: share authority twice
  source/extensions/filters/http/connect_authority/filter.cc
Labels: size/XS
