Repository istio/proxy, pull requests merged in 2023-04, with the labels that each got.

#4549 Update for https://github.com/envoyproxy/envoy/pull/26195
  WORKSPACE
  source/extensions/filters/http/connect_authority/filter.cc
  source/extensions/filters/http/connect_baggage/filter.cc
  source/extensions/filters/network/istio_authn/config.h
Labels: size/S

#4551 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4550 [release-1.17] stats: implement grpc message counts
  source/extensions/filters/http/istio_stats/BUILD
  source/extensions/filters/http/istio_stats/istio_stats.cc
  test/envoye2e/env/utils.go
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
Labels: size/L

#4552 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4554 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4553 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#4560 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4561 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/S, auto-merge, release-notes-none

#4563 Update Envoy and add changes that came from the private build
  WORKSPACE
  testdata/stackdriver/utf8_client_access_log_entry.yaml.tmpl
  testdata/stackdriver/utf8_server_access_log_entry.yaml.tmpl
Labels: size/XS

#4565 [release-1.15] Update envoy-proxy
  WORKSPACE
  testdata/stackdriver/utf8_client_access_log_entry.yaml.tmpl
  testdata/stackdriver/utf8_server_access_log_entry.yaml.tmpl
Labels: size/XS

#4566 [release-1.16] Update envoyproxy
  WORKSPACE
  testdata/stackdriver/utf8_client_access_log_entry.yaml.tmpl
  testdata/stackdriver/utf8_server_access_log_entry.yaml.tmpl
Labels: size/XS

#4570 Automator: update common-files@release-1.17 in istio/proxy@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4569 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4571 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4572 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4573 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4575 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4576 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4578 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4583 Update envoyproxy
  WORKSPACE
  testdata/stackdriver/utf8_client_access_log_entry.yaml.tmpl
  testdata/stackdriver/utf8_server_access_log_entry.yaml.tmpl
Labels: size/XS

#4585 [release-1.16] update envoy proxy
  WORKSPACE
  testdata/stackdriver/utf8_client_access_log_entry.yaml.tmpl
  testdata/stackdriver/utf8_server_access_log_entry.yaml.tmpl
Labels: size/XS

#4584 [release-1.17] update envoy for latest patches
  WORKSPACE
  testdata/stackdriver/utf8_client_access_log_entry.yaml.tmpl
  testdata/stackdriver/utf8_server_access_log_entry.yaml.tmpl
Labels: size/XS

#4586 Automator: update common-files@release-1.16 in istio/proxy@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4587 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4588 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4591 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#4590 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4592 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#4593 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4595 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4596 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4594 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4598 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4597 stats: implement metric expiry
  source/extensions/filters/http/istio_stats/config.proto
  source/extensions/filters/http/istio_stats/istio_stats.cc
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/stats/client_config_expiry.yaml
Labels: size/L

#4599 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4601 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4602 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4605 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4606 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4603 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#4607 [release-1.18] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#4610 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#4609 Automator: update common-files@release-1.18 in istio/proxy@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#4611 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4612 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4613 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4614 Automator: update envoy@ in istio/proxy@release-1.18
  WORKSPACE
Labels: size/XS, auto-merge

#4615 bazel: mark tests as large
  source/extensions/filters/http/authn/BUILD
  test/integration/BUILD
Labels: size/XS

#4618 Automator: update envoy@ in istio/proxy@release-1.16
  WORKSPACE
Labels: size/XS, auto-merge

#4617 Automator: update envoy@ in istio/proxy@release-1.17
  WORKSPACE
Labels: size/XS, auto-merge

#4620 fix build
  WORKSPACE
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/S

#4622 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#4623 stats: fix destination service name for service entries
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: cherrypick/release-1.17, cherrypick/release-1.18

#4621 enable open telemetry stat sink
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#4625 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#4627 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none
