Repository istio/proxy, pull requests merged in 2024-10, with the labels that each got.

#5843 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5844 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5847 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
  envoy.bazelrc
Labels: size/M, auto-merge

#5846 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
  envoy.bazelrc
Labels: size/M, auto-merge

#5845 refactor follow-up
  extensions/common/metadata_object.cc
  extensions/common/metadata_object.h
  extensions/common/metadata_object_test.cc
Labels: size/L

#5849 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5848 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5850 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5851 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5853 fix build due to upstream changes
  WORKSPACE
  extensions/common/metadata_object.cc
  extensions/common/metadata_object.h
  extensions/common/metadata_object_test.cc
Labels: size/L

#5854 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5856 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5857 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5858 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5859 Automator: update common-files@release-1.23 in istio/proxy@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5860 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5862 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5863 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5866 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5867 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5868 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5869 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5870 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5861 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5865 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5871 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5872 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5873 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5874 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5876 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5875 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5877 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5878 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5880 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5881 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5882 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5883 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#5885 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5886 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5888 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5887 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5889 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5890 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5891 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#5893 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5894 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#5896 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5898 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5899 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5900 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5902 manual step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#5903 Automator: update common-files@release-1.24 in istio/proxy@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5897 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5905 Automator: update common-files@release-1.24 in istio/proxy@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5904 [release-1.24] Automated branching step 4
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#5906 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5909 Automator: update common-files@release-1.24 in istio/proxy@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5908 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5907 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge
