Repository istio/proxy, pull requests merged in 2024-12, with the labels that each got.

#5969 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5970 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5971 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5972 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5973 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5975 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#5976 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5974 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5977 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#5978 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5980 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5982 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5984 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#5985 Automator: update common-files@release-1.24 in istio/proxy@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5983 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#5986 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5987 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5988 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#5990 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5991 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#5989 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5992 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#5993 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5994 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5995 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5996 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5997 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5998 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5999 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6000 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6001 Automator: update common-files@release-1.24 in istio/proxy@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5963 Add compdb script
  tools/gen_compilation_database.py
  tools/vscode/refresh_compdb.sh
Labels: size/L

#6002 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6003 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#5736 [release-1.23] Add missing `$BAZEL_STARTUP_ARGS` to `bazel info` command
  Makefile.core.mk
Labels: size/XS, release-notes-none

#6005 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#6004 Cleanup deadcode from stackdriver tests
  testdata/certs/stackdriver.key
  testdata/certs/stackdriver.pem
  testdata/filters/stackdriver_inbound.yaml.tmpl
  testdata/filters/stackdriver_inbound_logs_filter.yaml.tmpl
  testdata/filters/stackdriver_network_inbound.yaml.tmpl
  testdata/filters/stackdriver_network_outbound.yaml.tmpl
  testdata/filters/stackdriver_outbound.yaml.tmpl
  testdata/filters/stackdriver_outbound_logs_filter.yaml.tmpl
  testdata/metric/stackdriver_callout_metric.yaml.tmpl
  testdata/metric/stackdriver_gateway_callout_metric.yaml.tmpl
Labels: size/L, release-notes-none

#6006 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6009 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#6008 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6011 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6012 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#6010 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#6015 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#6016 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6017 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6018 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#6021 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#6020 update envoy and fix build
  WORKSPACE
  envoy.bazelrc
  scripts/update_envoy.sh
Labels: size/S

#6022 Automator: update envoy@ in istio/proxy@master
  envoy.bazelrc
Labels: size/XS, auto-merge

#6024 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6025 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6026 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6027 Make lint and update docs
  source/extensions/filters/http/alpn/config.pb.html
  source/extensions/filters/http/istio_stats/config.pb.html
  source/extensions/filters/http/peer_metadata/config.pb.html
  source/extensions/filters/network/metadata_exchange/config/metadata_exchange.pb.html
  test/envoye2e/driver/otel.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  testdata/testdata.gen.go
Labels: size/S

#6029 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6031 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#6032 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5968 Fix tcp telemetry for service-oriented waypoints
  source/extensions/filters/network/metadata_exchange/BUILD
  source/extensions/filters/network/metadata_exchange/metadata_exchange.cc
  test/envoye2e/basic_flow/basic_test.go
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/filters/mx_waypoint_tcp.yaml.tmpl
  testdata/listener/tcp_client.yaml.tmpl
  testdata/listener/tcp_waypoint_server.yaml.tmpl
  testdata/metric/server_waypoint_proxy_connect_connections_opened_total.yaml.tmpl
  testdata/testdata.gen.go
Labels: size/L

#6033 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6034 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#6037 [release-1.24] Fix tcp telemetry for service-oriented waypoints
  source/extensions/filters/network/metadata_exchange/BUILD
  source/extensions/filters/network/metadata_exchange/metadata_exchange.cc
  test/envoye2e/basic_flow/basic_test.go
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/filters/mx_waypoint_tcp.yaml.tmpl
  testdata/listener/tcp_client.yaml.tmpl
  testdata/listener/tcp_waypoint_server.yaml.tmpl
  testdata/metric/server_waypoint_proxy_connect_connections_opened_total.yaml.tmpl
  testdata/testdata.gen.go
Labels: size/L
