Repository istio/proxy, pull requests merged in 2024-06, with the labels that each got.

#5582 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/S, auto-merge, release-notes-none

#5583 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5584 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5585 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5581 disable extension check tool
  WORKSPACE
  scripts/release-binary.sh
Labels: size/M

#5586 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#5587 Automator: update common-files@release-1.20 in istio/proxy@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5590 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5591 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5576 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5594 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5592 correct peer_unkown key
  source/extensions/filters/http/istio_stats/istio_stats.cc
  source/extensions/filters/network/metadata_exchange/metadata_exchange.cc
Labels: size/S

#5589 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5588 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5596 [release-1.22] correct peer_unkown key
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/XS, cherrypick/release-1.20, cherrypick/release-1.21

#5597 [release-1.20] correct peer_unkown key
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/XS, release-notes-none

#5598 [release-1.21] correct peer_unkown key
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/XS, release-notes-none

#5600 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5601 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5602 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5603 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5599 add test for tcp_reporting_duration
  test/envoye2e/driver/stats.go
  test/envoye2e/driver/tcp.go
  test/envoye2e/inventory.go
  test/envoye2e/tcp_metadata_exchange/tcp_metadata_exchange_test.go
  testdata/cluster/tcp_client_unknown.yaml.tmpl
  testdata/metric/tcp_client_sent_bytes_unknown.yaml.tmpl
Labels: size/L

#5604 Allow versionless cluster name match in stats
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/XS, release-notes-none

#5605 [release-1.22] Allow versionless cluster name match in stats
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/XS, release-notes-none

#5606 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5607 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5608 Automator: update common-files@release-1.21 in istio/proxy@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5609 Automator: update common-files@release-1.22 in istio/proxy@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5610 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5611 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#5612 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5613 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5614 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5615 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5616 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5618 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#5617 Use cluster metadata for destination_service_name
  source/extensions/filters/http/istio_stats/istio_stats.cc
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/bootstrap/client_cluster_metadata_precedence.yaml.tmpl
  testdata/metric/client_request_total_cluster_metadata_precedence.yaml.tmpl
Labels: size/L

#5619 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5620 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5621 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5622 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5623 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5624 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5625 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5628 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5627 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5626 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5629 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5631 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5632 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#5633 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5634 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#5630 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5635 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5637 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5636 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5639 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5640 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5638 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge
