Repository istio/proxy, pull requests merged in 2024-01, with the labels that each got.

#5237 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5235 Sync core extension
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
Labels: size/S

#5239 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5242 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5244 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5240 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5246 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5247 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#5248 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5245 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5249 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5250 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5251 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5252 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#5253 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5254 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5257 Automator: update common-files@release-1.20 in istio/proxy@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5258 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5256 Automator: update common-files@release-1.19 in istio/proxy@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5259 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5260 ambient: remove custom objects to store principals
  source/extensions/common/BUILD
  source/extensions/common/filter_objects.h
  source/extensions/filters/http/istio_stats/BUILD
  source/extensions/filters/http/istio_stats/istio_stats.cc
  testdata/listener/terminate_connect.yaml.tmpl
Labels: size/L

#5262 update envoy
  WORKSPACE
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/S

#5261 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5263 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5264 Automator: update common-files@release-1.20 in istio/proxy@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5265 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5266 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#5267 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5268 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5270 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#5271 Automator: update envoy@ in istio/proxy@release-1.19
  WORKSPACE
Labels: size/XS, auto-merge

#5272 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5273 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5269 enable json_to_metadata filter
  bazel/extension_config/extensions_build_config.bzl
  tools/extension-check/wellknown-extensions
Labels: ok-to-test, size/XS

#5274 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5275 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5276 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5277 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5278 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5279 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5280 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5283 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5282 [release-1.21] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#5281 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5285 Automator: update common-files@release-1.21 in istio/proxy@release-1.21
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5286 update go-control-plane
  go.mod
  go.sum
Labels: size/XS

#5287 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5288 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5289 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5290 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5291 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5292 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5293 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5294 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge
