Repository istio/proxy, pull requests merged in 2024-07, with the labels that each got.

#5641 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5642 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5643 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5644 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5646 Automator: update envoy@ in istio/proxy@release-1.20
  WORKSPACE
Labels: size/XS, auto-merge

#5645 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5647 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5649 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5648 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5651 Automator: update common-files@release-1.22 in istio/proxy@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5652 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5653 waypoints: fix IPv6 address lookup
  source/extensions/common/workload_discovery/api.cc
Labels: size/XS, release-notes-none

#5654 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5655 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5656 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5657 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5659 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5660 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5661 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5662 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5663 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5658 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5665 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5666 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5667 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5668 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5669 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5670 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5672 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5673 [release-1.23] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#5671 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5675 Automator: update common-files@release-1.23 in istio/proxy@release-1.23
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5674 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5676 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5677 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5678 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5679 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5680 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5681 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5682 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5683 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5684 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5685 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5686 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5687 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#5689 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5690 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5691 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5693 Automator: update common-files@master in istio/proxy@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5692 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5694 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5695 Automator: update envoy@ in istio/proxy@release-1.21
  WORKSPACE
Labels: size/XS, auto-merge

#5696 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#5698 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5699 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#5697 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5700 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5701 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#5702 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#5704 Add new fields to workload.proto
  source/extensions/common/workload_discovery/discovery.proto
Labels: size/M, release-notes-none, cherrypick/release-1.23

#5705 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#5708 Sync with upstream
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS
