Repository istio/proxy, pull requests merged in 2025-01, with the labels that each got.

#6039 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#6038 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6041 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6042 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6044 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6045 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#6047 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6046 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6023 bump bazel
  .bazelversion
  scripts/update_envoy.sh
Labels: size/XS

#6048 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6049 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#6050 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6051 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#6052 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6055 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#6056 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6057 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6058 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6059 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6060 Automator: update common-files@release-1.24 in istio/proxy@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  testdata/testdata.gen.go
Labels: size/XS, auto-merge, release-notes-none

#6061 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6062 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6063 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#6065 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6067 bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: ok-to-test, size/S

#6072 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6070 Drop protoc docs generation
  Makefile.core.mk
  source/extensions/filters/http/alpn/config.pb.html
  source/extensions/filters/http/istio_stats/config.pb.html
  source/extensions/filters/http/peer_metadata/config.pb.html
  source/extensions/filters/network/metadata_exchange/config/metadata_exchange.pb.html
Labels: size/S, release-notes-none

#6028 Add metadata fallback for client sidecar reporters
  source/extensions/filters/http/istio_stats/istio_stats.cc
  source/extensions/filters/http/peer_metadata/filter.cc
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/cluster/internal_outbound.yaml.tmpl
  testdata/filters/mx_native_outbound.yaml.tmpl
  testdata/metric/client_sidecar_connect_request_total.yaml.tmpl
Labels: size/L, cherrypick/release-1.22, cherrypick/release-1.23, cherrypick/release-1.24

#6073 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#6074 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6077 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6066 Disable spammy logs in release
  scripts/release-binary.sh
Labels: size/XS

#6078 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6079 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6080 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#6083 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6084 bazel RLQS config extension
  bazel/extension_config/extensions_build_config.bzl
Labels: ok-to-test, size/XS

#6086 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6085 bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: ok-to-test, size/S

#6087 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6088 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6090 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#6091 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#6094 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6095 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#6096 Automator: update envoy@ in istio/proxy@release-1.22
  WORKSPACE
Labels: size/XS, auto-merge

#6097 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6098 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#6075 [release-1.24] Add metadata fallback for client sidecar reporters (#6028)
  source/extensions/filters/http/istio_stats/istio_stats.cc
  source/extensions/filters/http/peer_metadata/filter.cc
  test/envoye2e/inventory.go
  test/envoye2e/stats_plugin/stats_test.go
  testdata/cluster/internal_outbound.yaml.tmpl
  testdata/filters/mx_native_outbound.yaml.tmpl
  testdata/metric/client_sidecar_connect_request_total.yaml.tmpl
Labels: size/L

#6099 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6100 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6101 mx: allow disabling unconditionally
  source/extensions/filters/http/peer_metadata/filter.cc
  source/extensions/filters/http/peer_metadata/filter.h
Labels: size/M
