Repository istio/proxy, pull requests merged in 2025-06, with the labels that each got.

#6327 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6329 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#6331 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6333 Manual Update: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS

#6335 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#6339 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#6341 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#6343 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#6342 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#6345 sync upstream
  .bazelrc
  WORKSPACE
  bazel/BUILD
  envoy.bazelrc
Labels: size/L

#6346 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6349 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#6350 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6351 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6353 Automator: update common-files@release-1.25 in istio/proxy@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6355 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6358 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6359 Automator: update common-files@release-1.26 in istio/proxy@release-1.26
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6360 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#6363 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6365 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6369 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6370 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6371 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#6376 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none
