Repository istio/proxy, pull requests merged in 2025-07, with the labels that each got.

#6377 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6378 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6379 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6380 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6381 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6382 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#6385 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6386 [release-1.27] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS

#6388 Automator: update common-files@release-1.27 in istio/proxy@release-1.27
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6389 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6392 Automator: update common-files@release-1.26 in istio/proxy@release-1.26
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#6397 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6398 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6401 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6400 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6406 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6407 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6409 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#6410 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6412 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6413 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6414 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6415 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6419 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6417 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6420 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6421 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6422 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6424 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6425 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6426 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6428 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6429 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6430 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#6431 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6433 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6432 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6436 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6437 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6438 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6440 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6445 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6442 Automator: update envoy@ in istio/proxy@release-1.27
  .bazelversion
  WORKSPACE
Labels: size/XS, auto-merge

#6441 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6443 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6447 Automator: update envoy@ in istio/proxy@release-1.26
  .bazelversion
  WORKSPACE
Labels: size/XS, auto-merge

#6449 Automator: update envoy@ in istio/proxy@release-1.25
  .bazelversion
  WORKSPACE
Labels: size/XS, auto-merge

#6446 Automator: update envoy@ in istio/proxy@master
  .bazelversion
  WORKSPACE
Labels: size/XS, auto-merge

#6452 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6453 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge
