Repository istio/proxy, pull requests merged in 2025-05, with the labels that each got.

#6269 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6270 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6271 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6272 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6273 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#6274 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6275 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6276 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6277 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#6278 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6280 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6281 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6282 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6284 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6283 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6285 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6286 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6288 Automator: update envoy@ in istio/proxy@release-1.23
  WORKSPACE
Labels: size/XS, auto-merge

#6289 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6290 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6293 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6294 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#6295 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6296 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6298 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6299 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6300 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6301 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6302 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6303 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6304 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6306 Sync with upstream
  WORKSPACE
  source/extensions/filters/network/metadata_exchange/BUILD
Labels: size/XS

#6307 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#6308 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6311 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6314 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#6315 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/S, auto-merge

#6316 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#6317 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#6319 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6318 Enable envoy.resource_monitors.cpu_utilization
  bazel/extension_config/extensions_build_config.bzl
Labels: ok-to-test, size/XS

#6324 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge
