Repository istio/proxy, pull requests merged in 2025-09, with the labels that each got.

#6520 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6521 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6525 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6526 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6527 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6528 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6529 stats: utilize expiration
  go.mod
  go.sum
  source/extensions/filters/http/istio_stats/config.proto
  source/extensions/filters/http/istio_stats/istio_stats.cc
  test/envoye2e/stats_plugin/stats_test.go
  testdata/bootstrap/stats_expiry.yaml.tmpl
  testdata/stats/client_config_expiry.yaml
Labels: size/L

#6531 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6538 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6542 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6544 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6549 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6551 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6553 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
  envoy.bazelrc
Labels: size/XS, auto-merge

#6555 [release-1.27] Fix a couple of compiler warnings
  extensions/common/metadata_object.cc
Labels: size/XS, release-notes-none

#6556 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6557 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6558 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6561 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6562 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6564 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6568 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6570 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6571 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6573 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none
