Repository istio/proxy, pull requests merged in 2025-08, with the labels that each got.

#6457 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6458 Update envoy
  WORKSPACE
  envoy.bazelrc
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/S

#6460 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/XS, auto-merge, release-notes-none

#6461 update envoy
  WORKSPACE
  bazel/extension_config/extensions_build_config.bzl
Labels: size/XS

#6466 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6467 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6473 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6475 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6477 Automator: update envoy@ in istio/proxy@release-1.24
  WORKSPACE
Labels: size/XS, auto-merge

#6478 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6480 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/M, auto-merge, release-notes-none

#6484 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6487 Replace ProtobufWkt with Protobuf namespace
  WORKSPACE
  extensions/common/metadata_object.cc
  source/extensions/filters/http/istio_stats/istio_stats.cc
  source/extensions/filters/http/peer_metadata/filter_test.cc
  source/extensions/filters/network/metadata_exchange/metadata_exchange.cc
  source/extensions/filters/network/metadata_exchange/metadata_exchange_test.cc
Labels: size/M

#6488 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6489 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6490 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6491 Automator: update go-control-plane in istio/proxy@master
  go.mod
  go.sum
Labels: size/S, auto-merge, release-notes-none

#6498 Automator: update envoy@ in istio/proxy@release-1.26
  WORKSPACE
Labels: size/XS, auto-merge

#6499 Automator: update common-files@release-1.26 in istio/proxy@release-1.26
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6502 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6501 Automator: update envoy@ in istio/proxy@release-1.25
  WORKSPACE
Labels: size/XS, auto-merge

#6503 Automator: update envoy@ in istio/proxy@release-1.27
  WORKSPACE
Labels: size/XS, auto-merge

#6506 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6507 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6510 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6511 Automator: update envoy@ in istio/proxy@master
  WORKSPACE
Labels: size/XS, auto-merge

#6516 Automator: update common-files@master in istio/proxy@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#6517 Automator: update common-files@master in istio/proxy@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#6518 sync with upstream
  WORKSPACE
  source/extensions/filters/http/istio_stats/istio_stats.cc
Labels: size/M
